"""Frequency words part 4 — B2 words (~500).

Compact format: (word, translation, pos, cefr)
"""

_W4 = [
    ("abide","соблюдать","verb","B2"),("abound","изобиловать","verb","B2"),("abrupt","резкий","adj","B2"),
    ("absurd","абсурдный","adj","B2"),("abundant","обильный","adj","B2"),("accelerate","ускорять","verb","B2"),
    ("accessible","доступный","adj","B2"),("accomplish","выполнять","verb","B2"),("accumulate","накапливать","verb","B2"),
    ("accurate","точный","adj","B2"),("acknowledge","признавать","verb","B2"),("acquire","приобретать","verb","B2"),
    ("adequate","адекватный","adj","B2"),("adhere","придерживаться","verb","B2"),("adjacent","смежный","adj","B2"),
    ("administer","управлять","verb","B2"),("admirable","достойный восхищения","adj","B2"),("advent","прибытие","noun","B2"),
    ("adverse","неблагоприятный","adj","B2"),("aesthetic","эстетический","adj","B2"),("affiliation","аффилиация","noun","B2"),
    ("affirm","утверждать","verb","B2"),("aftermath","последствия","noun","B2"),("aggravate","усугублять","verb","B2"),
    ("aggregate","совокупный","adj","B2"),("ailment","недуг","noun","B2"),("airway","воздушный путь","noun","B2"),
    ("albeit","хотя","conj","B2"),("algorithm","алгоритм","noun","B2"),("alien","чужой","adj","B2"),
    ("allegation","заявление","noun","B2"),("allege","утверждать","verb","B2"),("alleviate","облегчать","verb","B2"),
    ("alliance","альянс","noun","B2"),("allocate","распределять","verb","B2"),("allot","выделять","verb","B2"),
    ("allowance","надбавка","noun","B2"),("alloy","сплав","noun","B2"),("allude","намекать","verb","B2"),
    ("allure","привлекать","verb","B2"),("almighty","всемогущий","adj","B2"),("alter","изменять","verb","B2"),
    ("alternate","чередоваться","verb","B2"),("alternative","альтернатива","noun","B2"),("amateur","любитель","noun","B2"),
    ("ambiguity","двусмысленность","noun","B2"),("ambiguous","двусмысленный","adj","B2"),("amend","вносить поправки","verb","B2"),
    ("amid","среди","prep","B2"),("ample","достаточный","adj","B2"),("amplify","усиливать","verb","B2"),
    ("analogy","аналогия","noun","B2"),("analyze","анализировать","verb","B2"),("anecdote","анекдот","noun","B2"),
    ("angular","угловой","adj","B2"),("anonymous","анонимный","adj","B2"),("anticipate","предвосхищать","verb","B2"),
    ("antique","антикварный","adj","B2"),("appalling","ужасающий","adj","B2"),("appealing","привлекательный","adj","B2"),
    ("appendix","приложение","noun","B2"),("appraise","оценивать","verb","B2"),("appreciate","ценить","verb","B2"),
    ("apprehend","арестовывать","verb","B2"),("appropriate","соответствующий","adj","B2"),("arbitrary","произвольный","adj","B2"),
    ("architect","архитектор","noun","B2"),("archive","архив","noun","B2"),("arid","засушливый","adj","B2"),
    ("aristocracy","аристократия","noun","B2"),("arouse","пробуждать","verb","B2"),("array","массив","noun","B2"),
    ("arrogant","высокомерный","adj","B2"),("articulate","чётко выражать","verb","B2"),("artifact","артефакт","noun","B2"),
    ("ascend","подниматься","verb","B2"),("aspiration","стремление","noun","B2"),("assimilate","усваивать","verb","B2"),
    ("assumption","предположение","noun","B2"),("assurance","уверенность","noun","B2"),("astonish","изумлять","verb","B2"),
    ("astronomer","астроном","noun","B2"),("asylum","убежище","noun","B2"),("attain","достигать","verb","B2"),
    ("attribute","приписывать","verb","B2"),("audit","аудит","noun","B2"),("augment","увеличивать","verb","B2"),
    ("authentic","подлинный","adj","B2"),("autobiography","автобиография","noun","B2"),("automate","автоматизировать","verb","B2"),
    ("autonomous","автономный","adj","B2"),("avail","польза","noun","B2"),("avert","предотвращать","verb","B2"),
    ("aviation","авиация","noun","B2"),("awe","трепет","noun","B2"),("backdrop","фон","noun","B2"),
    ("baffle","ставить в тупик","verb","B2"),("bald","лысый","adj","B2"),("barter","бартер","noun","B2"),
    ("battered","потрёпанный","adj","B2"),("belongings","вещи","noun","B2"),("benchmark","эталон","noun","B2"),
    ("beneficial","полезный","adj","B2"),("bilateral","двусторонний","adj","B2"),("bitter","горький","adj","B2"),
    ("bizarre","странный","adj","B2"),("bleak","мрачный","adj","B2"),("bliss","блаженство","noun","B2"),
    ("blockade","блокада","noun","B2"),("blueprint","план","noun","B2"),("blunder","ошибка","noun","B2"),
    ("blunt","тупой","adj","B2"),("blur","размывать","verb","B2"),("boost","повышать","verb","B2"),
    ("borrow","заимствовать","verb","B2"),("bourbon","бурбон","noun","B2"),("breach","нарушение","noun","B2"),
    ("breakthrough","прорыв","noun","B2"),("bribe","взятка","noun","B2"),("brink","край","noun","B2"),
    ("brisk","бодрый","adj","B2"),("brittle","хрупкий","adj","B2"),("browse","просматривать","verb","B2"),
    ("brutal","жестокий","adj","B2"),("bygone","прошлый","adj","B2"),("bylaw","устав","noun","B2"),
    ("calamity","бедствие","noun","B2"),("callous","бесчувственный","adj","B2"),("caliber","калибр","noun","B2"),
    ("candid","искренний","adj","B2"),("caption","подпись","noun","B2"),("carnival","карнавал","noun","B2"),
    ("casual","небрежный","adj","B2"),("cater","обслуживать","verb","B2"),("census","перепись","noun","B2"),
    ("chaos","хаос","noun","B2"),("chill","озноб","noun","B2"),("circuit","схема","noun","B2"),
    ("cognitive","когнитивный","adj","B2"),("coherent","связный","adj","B2"),("coincide","совпадать","verb","B2"),
    ("collaborate","сотрудничать","verb","B2"),("collective","коллективный","adj","B2"),("comet","комета","noun","B2"),
    ("commemorate","увековечивать","verb","B2"),("commence","начинать","verb","B2"),("commodity","товар","noun","B2"),
    ("commonplace","обыденный","adj","B2"),("commute","ездить","verb","B2"),("compact","компактный","adj","B2"),
    ("comparison","сравнение","noun","B2"),("competent","компетентный","adj","B2"),("compile","составлять","verb","B2"),
    ("complaint","жалоба","noun","B2"),("complement","дополнять","verb","B2"),("complexity","сложность","noun","B2"),
    ("compliance","соответствие","noun","B2"),("complicate","усложнять","verb","B2"),("compliment","комплимент","noun","B2"),
    ("composer","композитор","noun","B2"),("comprehensive","исчерпывающий","adj","B2"),("comprise","состоять из","verb","B2"),
    ("compromise","компромисс","noun","B2"),("compulsory","обязательный","adj","B2"),("conceal","скрывать","verb","B2"),
    ("concede","уступать","verb","B2"),("conceive","замышлять","verb","B2"),("concentrate","концентрировать","verb","B2"),
    ("condemn","осуждать","verb","B2"),("confer","совещаться","verb","B2"),("confess","признаваться","verb","B2"),
    ("confidential","конфиденциальный","adj","B2"),("configuration","конфигурация","noun","B2"),("conform","соответствовать","verb","B2"),
    ("confront","противостоять","verb","B2"),("confuse","путать","verb","B2"),("conjunction","союз","noun","B2"),
    ("conquest","завоевание","noun","B2"),("conscience","совесть","noun","B2"),("conscious","сознательный","adj","B2"),
    ("consensus","консенсус","noun","B2"),("consequently","следовательно","adv","B2"),("conservation","сохранение","noun","B2"),
    ("considerable","значительный","adj","B2"),("consideration","соображение","noun","B2"),("consistent","последовательный","adj","B2"),
    ("constantly","постоянно","adv","B2"),("constitution","конституция","noun","B2"),("consumption","потребление","noun","B2"),
    ("contemporary","современник","noun","B2"),("continual","непрерывный","adj","B2"),("continuous","непрерывный","adj","B2"),
    ("controversial","спорный","adj","B2"),("controversy","полемика","noun","B2"),("conventional","обычный","adj","B2"),
    ("conversion","превращение","noun","B2"),("convert","превращать","verb","B2"),("convey","передавать","verb","B2"),
    ("conviction","убеждение","noun","B2"),("cooperation","сотрудничество","noun","B2"),("coordinate","координировать","verb","B2"),
    ("correspond","соответствовать","verb","B2"),("corrupt","коррумпированный","adj","B2"),("counterpart","коллега","noun","B2"),
    ("courtesy","вежливость","noun","B2"),("crucial","решающий","adj","B2"),("cruise","круиз","noun","B2"),
    ("crush","давить","verb","B2"),("curiosity","любопытство","noun","B2"),("curriculum","учебный план","noun","B2"),
    ("deception","обман","noun","B2"),("deduction","вычет","noun","B2"),("deficiency","недостаток","noun","B2"),
    ("deficit","дефицит","noun","B2"),("delegation","делегация","noun","B2"),("deliberate","преднамеренный","adj","B2"),
    ("denial","отрицание","noun","B2"),("denote","обозначать","verb","B2"),("denounce","денонсировать","verb","B2"),
    ("depletion","истощение","noun","B2"),("deposition","показание","noun","B2"),("deprive","лишать","verb","B2"),
    ("derivative","производный","adj","B2"),("descendant","потомок","noun","B2"),("designation","обозначение","noun","B2"),
    ("despise","презирать","verb","B2"),("destiny","судьба","noun","B2"),("deter","удерживать","verb","B2"),
    ("deteriorate","ухудшаться","verb","B2"),("devastate","опустошать","verb","B2"),("deviation","отклонение","noun","B2"),
    ("devotion","преданность","noun","B2"),("diagnose","диагностировать","verb","B2"),("dictator","диктатор","noun","B2"),
    ("dilemma","дилемма","noun","B2"),("diminish","уменьшать","verb","B2"),("disability","инвалидность","noun","B2"),
    ("discern","различать","verb","B2"),("disclose","раскрывать","verb","B2"),("discourse","дискурс","noun","B2"),
    ("discretion","благоразумие","noun","B2"),("disgrace","позор","noun","B2"),("disguise","маскировка","noun","B2"),
    ("disillusion","разочарование","noun","B2"),("dismantle","демонтировать","verb","B2"),("disparity","неравенство","noun","B2"),
    ("disperse","рассеивать","verb","B2"),("displace","перемещать","verb","B2"),("dispose","располагать","verb","B2"),
    ("disposition","расположение","noun","B2"),("dispute","спор","noun","B2"),("disrupt","нарушать","verb","B2"),
    ("dissolve","растворять","verb","B2"),("distort","искажать","verb","B2"),("diversion","отвлечение","noun","B2"),
    ("diversity","разнообразие","noun","B2"),("divine","божественный","adj","B2"),("doctrine","доктрина","noun","B2"),
    ("domain","область","noun","B2"),("dominant","господствующий","adj","B2"),("doubtful","сомнительный","adj","B2"),
    ("drainage","дренаж","noun","B2"),("dramatic","драматический","adj","B2"),("drastic","радикальный","adj","B2"),
    ("drawback","недостаток","noun","B2"),("dread","страх","noun","B2"),("durable","прочный","adj","B2"),
    ("dwelling","жилище","noun","B2"),("eccentric","эксцентричный","adj","B2"),("eclipse","затмение","noun","B2"),
    ("ecosystem","экосистема","noun","B2"),("elaborate","разрабатывать","verb","B2"),("eligible","подходящий","adj","B2"),
    ("eloquent","красноречивый","adj","B2"),("embark","отправляться","verb","B2"),("embody","воплощать","verb","B2"),
    ("emigrate","эмигрировать","verb","B2"),("emission","выброс","noun","B2"),("emperor","император","noun","B2"),
    ("empire","империя","noun","B2"),("empirical","эмпирический","adj","B2"),("enact","принять закон","verb","B2"),
    ("enclose","окружать","verb","B2"),("encompass","охватывать","verb","B2"),("encounter","встреча","noun","B2"),
    ("endurance","выносливость","noun","B2"),("enforce","принуждать","verb","B2"),("engagement","помолвка","noun","B2"),
    ("enlighten","просвещать","verb","B2"),("enrich","обогащать","verb","B2"),("ensemble","ансамбль","noun","B2"),
    ("entail","влечь за собой","verb","B2"),("enthusiastic","энтузиастичный","adj","B2"),("entity","сущность","noun","B2"),
    ("entwine","переплетать","verb","B2"),("envoy","посланник","noun","B2"),("epidemic","эпидемия","noun","B2"),
    ("epoch","эпоха","noun","B2"),("equator","экватор","noun","B2"),("equilibrium","равновесие","noun","B2"),
    ("erode","разрушать","verb","B2"),("essence","сущность","noun","B2"),("eternal","вечный","adj","B2"),
    ("evacuate","эвакуировать","verb","B2"),("evident","очевидный","adj","B2"),("exalt","возвышать","verb","B2"),
    ("exception","исключение","noun","B2"),("excessive","чрезмерный","adj","B2"),("excrete","выделять","verb","B2"),
    ("exemplify","иллюстрировать","verb","B2"),("exert","прилагать","verb","B2"),("exile","изгнание","noun","B2"),
    ("expansion","расширение","noun","B2"),("expedition","экспедиция","noun","B2"),("expel","исключать","verb","B2"),
    ("expenditure","расход","noun","B2"),("expertise","экспертиза","noun","B2"),("explicit","явный","adj","B2"),
    ("exploit","эксплуатировать","verb","B2"),("exquisite","изысканный","adj","B2"),("exterior","внешний","adj","B2"),
    ("extinct","вымерший","adj","B2"),("extract","извлекать","verb","B2"),("extravagant","экстравагантный","adj","B2"),
    ("fabricate","изготовлять","verb","B2"),("facilitate","облегчать","verb","B2"),("famine","голод","noun","B2"),
    ("fascinate","очаровывать","verb","B2"),("feasible","осуществимый","adj","B2"),("feeble","слабый","adj","B2"),
    ("feminine","женственный","adj","B2"),("fertile","плодородный","adj","B2"),("fierce","свирепый","adj","B2"),
    ("fluctuate","колебаться","verb","B2"),("foremost","первый","adj","B2"),("forfeit","лишать","verb","B2"),
    ("formidable","грозный","adj","B2"),("fortify","укреплять","verb","B2"),("fragile","хрупкий","adj","B2"),
    ("friction","трение","noun","B2"),("fulfill","выполнять","verb","B2"),("garrison","гарнизон","noun","B2"),
    ("generate","генерировать","verb","B2"),("genuine","подлинный","adj","B2"),("glorify","прославлять","verb","B2"),
    ("grandeur","величие","noun","B2"),("gratitude","благодарность","noun","B2"),("grievance","жалоба","noun","B2"),
    ("grim","мрачный","adj","B2"),("gruesome","ужасный","adj","B2"),("guidelines","руководящие принципы","noun","B2"),
    ("habitable","пригодный для жилья","adj","B2"),("hardship","лишение","noun","B2"),("hasten","торопиться","verb","B2"),
    ("haunt","преследовать","verb","B2"),("hectic","беспокойный","adj","B2"),("horrify","ужасать","verb","B2"),
    ("humiliate","унижать","verb","B2"),("hypocrisy","лицемерие","noun","B2"),("identical","идентичный","adj","B2"),
    ("ideology","идеология","noun","B2"),("illuminate","освещать","verb","B2"),("immense","огромный","adj","B2"),
    ("immortal","бессмертный","adj","B2"),("impartial","беспристрастный","adj","B2"),("imperative","повелительный","adj","B2"),
    ("implement","осуществлять","verb","B2"),("implication","подтекст","noun","B2"),("implicit","неявный","adj","B2"),
    ("impose","налагать","verb","B2"),("impulse","импульс","noun","B2"),("inadequate","неадекватный","adj","B2"),
    ("incentive","стимул","noun","B2"),("incidence","частота","noun","B2"),("incline","наклон","noun","B2"),
    ("incorporate","включать","verb","B2"),("incredible","невероятный","adj","B2"),("incur","навлекать","verb","B2"),
    ("indefinite","неопределённый","adj","B2"),("indifference","безразличие","noun","B2"),("indignant","возмущённый","adj","B2"),
    ("indulge","предаваться","verb","B2"),("inevitable","неизбежный","adj","B2"),("infectious","заразный","adj","B2"),
    ("infer","выводить","verb","B2"),("inferior","худший","adj","B2"),("inflict","наносить","verb","B2"),
    ("inhabit","обитать","verb","B2"),("inherent","присущий","adj","B2"),("inhibit","подавлять","verb","B2"),
    ("initiate","начинать","verb","B2"),("innate","врождённый","adj","B2"),("innovation","нововведение","noun","B2"),
    ("innumerable","бесчисленный","adj","B2"),("insane","безумный","adj","B2"),("insight","проницательность","noun","B2"),
    ("instinct","инстинкт","noun","B2"),("intact","неповреждённый","adj","B2"),("integral","неотъемлемый","adj","B2"),
    ("integrate","интегрировать","verb","B2"),("integrity","целостность","noun","B2"),("intensify","усиливать","verb","B2"),
    ("intent","намерение","noun","B2"),("interfere","вмешиваться","verb","B2"),("intermittent","прерывистый","adj","B2"),
    ("intervene","вмешиваться","verb","B2"),("intimate","близкий","adj","B2"),("intricate","сложный","adj","B2"),
    ("intrinsic","внутренний","adj","B2"),("invalid","недействительный","adj","B2"),("inventive","изобретательный","adj","B2"),
    ("invert","переворачивать","verb","B2"),("investigate","расследовать","verb","B2"),("irony","ирония","noun","B2"),
    ("irrelevant","неуместный","adj","B2"),("irreversible","необратимый","adj","B2"),("isolate","изолировать","verb","B2"),
    ("jeopardize","подвергать опасности","verb","B2"),("judicial","судебный","adj","B2"),("jurisdiction","юрисдикция","noun","B2"),
    ("justification","оправдание","noun","B2"),("juvenile","юный","adj","B2"),("kindle","разжигать","verb","B2"),
    ("knack","сноровка","noun","B2"),("lament","скорбеть","verb","B2"),("latent","скрытый","adj","B2"),
    ("lavish","роскошный","adj","B2"),("legacy","наследие","noun","B2"),("legitimate","законный","adj","B2"),
    ("lenient","снисходительный","adj","B2"),("lethal","смертельный","adj","B2"),("linger","задерживаться","verb","B2"),
    ("literacy","грамотность","noun","B2"),("luminous","светящийся","adj","B2"),("magnify","увеличивать","verb","B2"),
    ("magnitude","величина","noun","B2"),("majesty","величество","noun","B2"),("malignant","злокачественный","adj","B2"),
    ("manipulate","манипулировать","verb","B2"),("mansion","особняк","noun","B2"),("maritime","морской","adj","B2"),
    ("martial","военный","adj","B2"),("masculine","мужской","adj","B2"),("massive","массивный","adj","B2"),
    ("mature","зрелый","adj","B2"),("maximize","максимизировать","verb","B2"),("meadow","луг","noun","B2"),
    ("meditate","размышлять","verb","B2"),("melancholy","меланхолия","noun","B2"),("memorable","запоминающийся","adj","B2"),
    ("menace","угроза","noun","B2"),("merge","сливать","verb","B2"),("metaphor","метафора","noun","B2"),
    ("midst","середина","noun","B2"),("militant","воинственный","adj","B2"),("minimize","минимизировать","verb","B2"),
    ("minute","мелкий","adj","B2"),("misery","страдание","noun","B2"),("mission","миссия","noun","B2"),
    ("moan","стон","noun","B2"),("modify","модифицировать","verb","B2"),("monarch","монарх","noun","B2"),
    ("monetary","денежный","adj","B2"),("monopoly","монополия","noun","B2"),("monument","памятник","noun","B2"),
    ("morale","боевой дух","noun","B2"),("mortgage","ипотека","noun","B2"),("motif","мотив","noun","B2"),
    ("municipal","муниципальный","adj","B2"),("mutual","взаимный","adj","B2"),("mystery","тайна","noun","B2"),
    ("myth","миф","noun","B2"),("narrative","повествование","noun","B2"),("nasty","мерзкий","adj","B2"),
    ("navigate","навигировать","verb","B2"),("negotiate","вести переговоры","verb","B2"),("neutral","нейтральный","adj","B2"),
    ("nominate","выдвигать","verb","B2"),("notorious","печально известный","adj","B2"),("novelty","новинка","noun","B2"),
    ("nurture","воспитывать","verb","B2"),("obscure","неясный","adj","B2"),("observatory","обсерватория","noun","B2"),
    ("obsess","одержимость","verb","B2"),("obstruct","препятствовать","verb","B2"),("offensive","оскорбительный","adj","B2"),
    ("offset","компенсировать","verb","B2"),("ominous","зловещий","adj","B2"),("omit","пропускать","verb","B2"),
    ("onset","начало","noun","B2"),("opaque","непрозрачный","adj","B2"),("oppress","угнетать","verb","B2"),
    ("optimism","оптимизм","noun","B2"),("orient","ориентировать","verb","B2"),("originate","происходить","verb","B2"),
    ("outbreak","вспышка","noun","B2"),("outlook","перспектива","noun","B2"),("outrage","возмущение","noun","B2"),
    ("outskirts","окраина","noun","B2"),("overall","в целом","adj","B2"),("overcome","преодолевать","verb","B2"),
    ("overlap","перекрывать","verb","B2"),("overlook","не замечать","verb","B2"),("overwhelm","переполнять","verb","B2"),
    ("pamphlet","памфлет","noun","B2"),("paradise","рай","noun","B2"),("paradox","парадокс","noun","B2"),
    ("parallel","параллель","noun","B2"),("paralyze","парализовать","verb","B2"),("partial","частичный","adj","B2"),
    ("participate","участвовать","verb","B2"),("passion","страсть","noun","B2"),("passive","пассивный","adj","B2"),
    ("patent","патент","noun","B2"),("patriot","патриот","noun","B2"),("patrol","патруль","noun","B2"),
    ("patron","покровитель","noun","B2"),("pave","мостить","verb","B2"),("peasant","крестьянин","noun","B2"),
    ("penalty","штраф","noun","B2"),("pending","в ожидании","adj","B2"),("perceive","воспринимать","verb","B2"),
    ("permanent","постоянный","adj","B2"),("permeate","проникать","verb","B2"),("permit","разрешение","noun","B2"),
    ("perpetual","вечный","adj","B2"),("perplex","озадачивать","verb","B2"),("persist","упорствовать","verb","B2"),
    ("personnel","персонал","noun","B2"),("perspective","перспектива","noun","B2"),("pessimism","пессимизм","noun","B2"),
    ("petition","петиция","noun","B2"),("phenomenon","феномен","noun","B2"),("philosophy","философия","noun","B2"),
    ("picturesque","живописный","adj","B2"),("pioneer","пионер","noun","B2"),("plague","чума","noun","B2"),
    ("plausible","правдоподобный","adj","B2"),("pledge","залог","noun","B2"),("plunge","нырять","verb","B2"),
    ("poignant","трогательный","adj","B2"),("pollute","загрязнять","verb","B2"),("pomp","пышность","noun","B2"),
    ("portray","изображать","verb","B2"),("postpone","откладывать","verb","B2"),("potent","сильнодействующий","adj","B2"),
    ("potential","потенциальный","adj","B2"),("practitioner","практик","noun","B2"),("precaution","мера предосторожности","noun","B2"),
    ("precede","предшествовать","verb","B2"),("precious","драгоценный","adj","B2"),("precise","точный","adj","B2"),
    ("predecessor","предшественник","noun","B2"),("predominant","преобладающий","adj","B2"),("prejudice","предубеждение","noun","B2"),
    ("preliminary","предварительный","adj","B2"),("premature","преждевременный","adj","B2"),("premise","предпосылка","noun","B2"),
    ("premium","премия","noun","B2"),("prescribe","предписывать","verb","B2"),("preserve","сохранять","verb","B2"),
    ("preside","председательствовать","verb","B2"),("prestige","престиж","noun","B2"),("presume","предполагать","verb","B2"),
    ("prevail","преобладать","verb","B2"),("prevalent","распространённый","adj","B2"),("prevention","предотвращение","noun","B2"),
    ("prey","добыча","noun","B2"),("primary","первичный","adj","B2"),("prime","главный","adj","B2"),
    ("primitive","примитивный","adj","B2"),("principal","главный","adj","B2"),("prior","предшествующий","adj","B2"),
    ("privilege","привилегия","noun","B2"),("probe","зонд","noun","B2"),("procedure","процедура","noun","B2"),
    ("proclaim","провозглашать","verb","B2"),("productive","продуктивный","adj","B2"),("profound","глубокий","adj","B2"),
    ("progressive","прогрессивный","adj","B2"),("prohibit","запрещать","verb","B2"),("projector","проектор","noun","B2"),
    ("prolong","продлевать","verb","B2"),("prominent","выдающийся","adj","B2"),("promote","продвигать","verb","B2"),
    ("prompt","быстрый","adj","B2"),("prone","склонный","adj","B2"),("propaganda","пропаганда","noun","B2"),
    ("propel","двигать","verb","B2"),("proportion","пропорция","noun","B2"),("proposition","предложение","noun","B2"),
    ("prose","проза","noun","B2"),("prosecute","судить","verb","B2"),("prosper","процветать","verb","B2"),
    ("prosperity","процветание","noun","B2"),("protocol","протокол","noun","B2"),("provoke","провоцировать","verb","B2"),
    ("puberty","половое созревание","noun","B2"),("publicize","рекламировать","verb","B2"),("punctual","пунктуальный","adj","B2"),
    ("purchase","покупка","noun","B2"),("pursue","преследовать","verb","B2"),("puzzle","головоломка","noun","B2"),
    ("quench","утолять","verb","B2"),("quest","поиск","noun","B2"),("quiver","дрожать","verb","B2"),
    ("quota","квота","noun","B2"),("radical","радикальный","adj","B2"),("rage","ярость","noun","B2"),
    ("raid","набег","noun","B2"),("rational","рациональный","adj","B2"),("ravage","опустошать","verb","B2"),
    ("realm","царство","noun","B2"),("reap","жать","verb","B2"),("reassure","успокаивать","verb","B2"),
    ("rebel","мятежник","noun","B2"),("rebellion","мятеж","noun","B2"),("recession","спад","noun","B2"),
    ("recipient","получатель","noun","B2"),("recite","декламировать","verb","B2"),("reckon","считать","verb","B2"),
    ("reclaim","возвращать","verb","B2"),("recommend","рекомендовать","verb","B2"),("reconcile","примирять","verb","B2"),
    ("recover","восстанавливать","verb","B2"),("recreation","отдых","noun","B2"),("recruit","набирать","verb","B2"),
    ("rectify","исправлять","verb","B2"),("recur","повторяться","verb","B2"),("redeem","выкупать","verb","B2"),
    ("redundant","избыточный","adj","B2"),("refine","очищать","verb","B2"),("reflect","отражать","verb","B2"),
    ("reform","реформа","noun","B2"),("refuge","убежище","noun","B2"),("refund","возврат","noun","B2"),
    ("regain","возвращать","verb","B2"),("regime","режим","noun","B2"),("regulate","регулировать","verb","B2"),
    ("rehabilitation","реабилитация","noun","B2"),("reign","царствовать","verb","B2"),("reimburse","возмещать","verb","B2"),
    ("reinforce","подкреплять","verb","B2"),("relay","передавать","verb","B2"),("release","выпуск","noun","B2"),
    ("relevant","уместный","adj","B2"),("reliable","надёжный","adj","B2"),("relic","реликвия","noun","B2"),
    ("reluctant","неохотный","adj","B2"),("remainder","остаток","noun","B2"),("remedy","средство","noun","B2"),
    ("remind","напоминать","verb","B2"),("remnant","остаток","noun","B2"),("renovate","обновлять","verb","B2"),
    ("repay","отплачивать","verb","B2"),("repeal","отменять","verb","B2"),("repeatedly","неоднократно","adv","B2"),
    ("repel","отталкивать","verb","B2"),("reproduce","размножаться","verb","B2"),("republic","республика","noun","B2"),
    ("reputation","репутация","noun","B2"),("resemble","походить","verb","B2"),("resent","обижаться","verb","B2"),
    ("reside","проживать","verb","B2"),("resign","подавать в отставку","verb","B2"),("resist","сопротивляться","verb","B2"),
    ("resolution","резолюция","noun","B2"),("resolve","решать","verb","B2"),("resort","курорт","noun","B2"),
    ("respective","соответствующий","adj","B2"),("restore","восстанавливать","verb","B2"),("restrain","сдерживать","verb","B2"),
    ("restrict","ограничивать","verb","B2"),("retain","удерживать","verb","B2"),("retreat","отступление","noun","B2"),
    ("retrieve","извлекать","verb","B2"),("reveal","раскрывать","verb","B2"),("revenge","месть","noun","B2"),
    ("revenue","доход","noun","B2"),("reverse","менять на противоположный","verb","B2"),("revise","пересматривать","verb","B2"),
    ("revolt","восстание","noun","B2"),("revolve","вращаться","verb","B2"),("ridiculous","смехотворный","adj","B2"),
    ("rigid","жёсткий","adj","B2"),("robust","крепкий","adj","B2"),("romance","роман","noun","B2"),
    ("sacred","священный","adj","B2"),("safeguard","защита","noun","B2"),("sailor","моряк","noun","B2"),
    ("sanction","санкция","noun","B2"),("satellite","спутник","noun","B2"),("satisfy","удовлетворять","verb","B2"),
    ("scarcely","едва","adv","B2"),("scatter","разбрасывать","verb","B2"),("scenic","живописный","adj","B2"),
    ("scheme","схема","noun","B2"),("scholar","учёный","noun","B2"),("scorn","презрение","noun","B2"),
    ("scramble","карабкаться","verb","B2"),("scrap","обрезок","noun","B2"),("scratch","царапать","verb","B2"),
    ("screw","винт","noun","B2"),("script","сценарий","noun","B2"),("scrutiny","придирчивый осмотр","noun","B2"),
    ("seam","шов","noun","B2"),("sector","сектор","noun","B2"),("secure","безопасный","adj","B2"),
    ("seemingly","по-видимому","adv","B2"),("segregate","разделять","verb","B2"),("sensation","ощущение","noun","B2"),
    ("sentiment","чувство","noun","B2"),("sequence","последовательность","noun","B2"),("serene","безмятежный","adj","B2"),
    ("severe","суровый","adj","B2"),("shatter","разбивать","verb","B2"),("sheer","чистый","adj","B2"),
    ("shelter","укрытие","noun","B2"),("shield","щит","noun","B2"),("shrewd","проницательный","adj","B2"),
    ("shrub","кустарник","noun","B2"),("siege","осада","noun","B2"),("simultaneous","одновременный","adj","B2"),
    ("sinister","зловещий","adj","B2"),("skeptic","скептик","noun","B2"),("slavery","рабство","noun","B2"),
    ("slim","тонкий","adj","B2"),("slogan","лозунг","noun","B2"),("slot","щель","noun","B2"),
    ("slump","спад","noun","B2"),("smuggle","контрабандировать","verb","B2"),("snatch","выхватывать","verb","B2"),
    ("soar","парить","verb","B2"),("sober","трезвый","adj","B2"),("solemn","торжественный","adj","B2"),
    ("solicit","просить","verb","B2"),("solidarity","солидарность","noun","B2"),("solitary","одинокий","adj","B2"),
    ("soluble","растворимый","adj","B2"),("sophisticated","сложный","adj","B2"),("sovereign","суверенный","adj","B2"),
    ("span","размах","noun","B2"),("spark","искра","noun","B2"),("spawn","порождать","verb","B2"),
    ("specify","указывать","verb","B2"),("specimen","образец","noun","B2"),("spectacle","зрелище","noun","B2"),
    ("spectator","зритель","noun","B2"),("spectrum","спектр","noun","B2"),("speculate","размышлять","verb","B2"),
    ("sphere","сфера","noun","B2"),("spill","проливать","verb","B2"),("spiral","спираль","noun","B2"),
    ("spontaneous","спонтанный","adj","B2"),("spouse","супруг","noun","B2"),("sprawl","расползаться","verb","B2"),
    ("sprint","спринт","noun","B2"),("stagnant","застойный","adj","B2"),("stamina","выносливость","noun","B2"),
    ("startling","поразительный","adj","B2"),("stationary","неподвижный","adj","B2"),("statistical","статистический","adj","B2"),
    ("status","статус","noun","B2"),("statute","статут","noun","B2"),("steadfast","твёрдый","adj","B2"),
    ("stereotype","стереотип","noun","B2"),("stimulus","стимул","noun","B2"),("stipulate","обусловливать","verb","B2"),
    ("stir","мешать","verb","B2"),("stray","заблудиться","verb","B2"),("strenuous","напряжённый","adj","B2"),
    ("stride","шаг","noun","B2"),("strife","борьба","noun","B2"),("striking","поразительный","adj","B2"),
    ("strive","стремиться","verb","B2"),("stumble","спотыкаться","verb","B2"),("stun","оглушать","verb","B2"),
    ("sturdy","крепкий","adj","B2"),("submit","подчиняться","verb","B2"),("subordinate","подчинённый","adj","B2"),
    ("subscribe","подписываться","verb","B2"),("subsequent","последующий","adj","B2"),("substance","вещество","noun","B2"),
    ("substantial","значительный","adj","B2"),("subtle","тонкий","adj","B2"),("succeed","преуспевать","verb","B2"),
    ("successor","преемник","noun","B2"),("sue","подавать в суд","verb","B2"),("sufficient","достаточный","adj","B2"),
    ("summit","вершина","noun","B2"),("summon","вызывать","verb","B2"),("superb","превосходный","adj","B2"),
    ("superficial","поверхностный","adj","B2"),("superintendent","надзиратель","noun","B2"),("supplement","дополнение","noun","B2"),
    ("suppress","подавлять","verb","B2"),("surge","волна","noun","B2"),("surplus","излишек","noun","B2"),
    ("surrender","капитуляция","noun","B2"),("surveillance","наблюдение","noun","B2"),("susceptible","восприимчивый","adj","B2"),
    ("suspend","приостанавливать","verb","B2"),("suspense","напряжение","noun","B2"),("sustain","поддерживать","verb","B2"),
    ("sustainable","устойчивый","adj","B2"),("swamp","болото","noun","B2"),("swap","менять","verb","B2"),
    ("sympathy","сочувствие","noun","B2"),("symphony","симфония","noun","B2"),("symposium","симпозиум","noun","B2"),
    ("syndrome","синдром","noun","B2"),("synthesis","синтез","noun","B2"),("tactic","тактика","noun","B2"),
    ("tan","загар","noun","B2"),("tangle","запутывать","verb","B2"),("tariff","тариф","noun","B2"),
    ("taunt","дразнить","verb","B2"),("tedious","утомительный","adj","B2"),("temperament","темперамент","noun","B2"),
    ("tempo","темп","noun","B2"),("tempt","соблазнять","verb","B2"),("tenant","арендатор","noun","B2"),
    ("tender","нежный","adj","B2"),("tenure","полномочие","noun","B2"),("terminal","терминал","noun","B2"),
    ("terrain","местность","noun","B2"),("testimony","показание","noun","B2"),("textile","текстиль","noun","B2"),
    ("thaw","таять","verb","B2"),("theft","кража","noun","B2"),("theoretical","теоретический","adj","B2"),
    ("therapy","терапия","noun","B2"),("thereafter","после этого","adv","B2"),("thereby","тем самым","adv","B2"),
    ("thigh","бедро","noun","B2"),("thorough","тщательный","adj","B2"),("threshold","порог","noun","B2"),
    ("thrive","процветать","verb","B2"),("thrust","толчок","noun","B2"),("tick","отмечать","verb","B2"),
    ("tidy","опрятный","adj","B2"),("tilt","наклон","noun","B2"),("timber","древесина","noun","B2"),
    ("timid","робкий","adj","B2"),("tissue","ткань","noun","B2"),("tolerant","терпимый","adj","B2"),
    ("toll","пошлина","noun","B2"),("topple","свергать","verb","B2"),("torment","мука","noun","B2"),
    ("torrent","поток","noun","B2"),("torture","пытка","noun","B2"),("toss","бросать","verb","B2"),
    ("toxic","токсичный","adj","B2"),("tract","участок","noun","B2"),("tradition","традиция","noun","B2"),
    ("tragic","трагический","adj","B2"),("trait","черта","noun","B2"),("tranquil","спокойный","adj","B2"),
    ("transit","транзит","noun","B2"),("transition","переход","noun","B2"),("transparent","прозрачный","adj","B2"),
    ("transplant","пересадка","noun","B2"),("trauma","травма","noun","B2"),("tremble","дрожать","verb","B2"),
    ("tremendous","огромный","adj","B2"),("trigger","спусковой крючок","noun","B2"),("trillion","триллион","num","B2"),
    ("triumph","триумф","noun","B2"),("trolley","тележка","noun","B2"),("troop","войско","noun","B2"),
    ("truce","перемирие","noun","B2"),("trumpet","труба","noun","B2"),("truncate","усекать","verb","B2"),
    ("turbine","турбина","noun","B2"),("turmoil","смятение","noun","B2"),("turnover","оборот","noun","B2"),
    ("twilight","сумерки","noun","B2"),("twist","скручивать","verb","B2"),("tyranny","тирания","noun","B2"),
    ("unanimous","единогласный","adj","B2"),("undergo","претерпевать","verb","B2"),("underline","подчёркивать","verb","B2"),
    ("underlying","лежащий в основе","adj","B2"),("undermine","подрывать","verb","B2"),("undertake","браться за","verb","B2"),
    ("unemployment","безработица","noun","B2"),("unfold","разворачивать","verb","B2"),("uniform","однородный","adj","B2"),
    ("unify","объединять","verb","B2"),("unique","уникальный","adj","B2"),("universe","вселенная","noun","B2"),
    ("unprecedented","беспрецедентный","adj","B2"),("upbringing","воспитание","noun","B2"),("upheaval","переворот","noun","B2"),
    ("uphold","поддерживать","verb","B2"),("upright","вертикальный","adj","B2"),("uproot","выкорчёвывать","verb","B2"),
    ("upsurge","подъём","noun","B2"),("upward","вверх","adv","B2"),("urge","настоять","verb","B2"),
    ("utilize","использовать","verb","B2"),("utmost","крайний","adj","B2"),("utter","полный","adj","B2"),
    ("vacancy","вакансия","noun","B2"),("vaccine","вакцина","noun","B2"),("valid","действительный","adj","B2"),
    ("valve","клапан","noun","B2"),("vanish","исчезать","verb","B2"),("variable","переменная","noun","B2"),
    ("vast","обширный","adj","B2"),("vehicle","транспортное средство","noun","B2"),("venture","предприятие","noun","B2"),
    ("verdict","вердикт","noun","B2"),("verify","проверять","verb","B2"),("versatile","разносторонний","adj","B2"),
    ("veteran","ветеран","noun","B2"),("veto","вето","noun","B2"),("viable","жизнеспособный","adj","B2"),
    ("vigorous","энергичный","adj","B2"),("vindicate","оправдывать","verb","B2"),("vintage","винтажный","adj","B2"),
    ("viral","вирусный","adj","B2"),("virtual","виртуальный","adj","B2"),("virtue","добродетель","noun","B2"),
    ("visionary","провидец","noun","B2"),("vital","жизненно важный","adj","B2"),("vivid","яркий","adj","B2"),
    ("volcano","вулкан","noun","B2"),("volume","объём","noun","B2"),("volunteer","волонтёр","noun","B2"),
    ("vow","обет","noun","B2"),("vulgar","вульгарный","adj","B2"),("vulnerable","уязвимый","adj","B2"),
    ("wander","бродить","verb","B2"),("warehouse","склад","noun","B2"),("warfare","война","noun","B2"),
    ("warrant","ордер","noun","B2"),("warranty","гарантия","noun","B2"),("warrior","воин","noun","B2"),
    ("wary","осторожный","adj","B2"),("watershed","водораздел","noun","B2"),("weave","ткать","verb","B2"),
    ("wedge","клин","noun","B2"),("weird","странный","adj","B2"),("wharf","причал","noun","B2"),
    ("whereby","посредством чего","adv","B2"),("whisker","вибрисс","noun","B2"),("wholesale","оптовый","adj","B2"),
    ("wicked","злой","adj","B2"),("widespread","широко распространённый","adj","B2"),("wield","властвовать","verb","B2"),
    ("wildlife","дикая природа","noun","B2"),("withdraw","отзывать","verb","B2"),("withhold","удерживать","verb","B2"),
    ("withstand","выдерживать","verb","B2"),("witness","свидетель","noun","B2"),("witty","остроумный","adj","B2"),
    ("wreck","обломки","noun","B2"),("wrestle","бороться","verb","B2"),("wring","выжимать","verb","B2"),
    ("yield","уступать","verb","B2"),("zeal","рвение","noun","B2"),("zenith","зенит","noun","B2"),
    ("zone","зона","noun","B2"),("appalling","ужасающий","adj","B2"),("candid","искренний","adj","B2"),
    ("compulsory","обязательный","adj","B2"),("conscientious","добросовестный","adj","B2"),("diligent","усердный","adj","B2"),
    ("diplomat","дипломат","noun","B2"),("discreet","осторожный","adj","B2"),("eloquent","красноречивый","adj","B2"),
    ("endeavor","стараться","verb","B2"),("endure","выдерживать","verb","B2"),("enforce","принуждать","verb","B2"),
    ("futile","бесполезный","adj","B2"),("gregarious","общительный","adj","B2"),("imminent","надвигающийся","adj","B2"),
    ("impeccable","безупречный","adj","B2"),("infallible","непогрешимый","adj","B2"),("ingenious","изобретательный","adj","B2"),
    ("innate","врождённый","adj","B2"),("intrepid","бесстрашный","adj","B2"),("meticulous","тщательный","adj","B2"),
    ("novice","новичок","noun","B2"),("obstinate","упрямый","adj","B2"),("ostensible","мнимый","adj","B2"),
    ("perpetual","вечный","adj","B2"),("pervasive","всеобъемлющий","adj","B2"),("plausible","правдоподобный","adj","B2"),
    ("pragmatic","прагматичный","adj","B2"),("precarious","шаткий","adj","B2"),("predator","хищник","noun","B2"),
    ("preeminent","выдающийся","adj","B2"),("presumptuous","самонадеянный","adj","B2"),("prolific","плодовитый","adj","B2"),
    ("quaint","причудливый","adj","B2"),("quintessential","типичный","adj","B2"),("rampant","неудержимый","adj","B2"),
    ("recede","отступать","verb","B2"),("recluse","затворник","noun","B2"),("reminiscent","напоминающий","adj","B2"),
    ("repercussion","последствие","noun","B2"),("replenish","пополнять","verb","B2"),("reprehensible","предосудительный","adj","B2"),
    ("reputation","репутация","noun","B2"),("resilient","устойчивый","adj","B2"),("reverence","почтение","noun","B2"),
    ("sagacious","проницательный","adj","B2"),("scrupulous","щепетильный","adj","B2"),("seclusion","уединение","noun","B2"),
    ("sedentary","сидячий","adj","B2"),("semblance","подобие","noun","B2"),("sensual","чувственный","adj","B2"),
    ("skeptical","скептический","adj","B2"),("slothful","ленивый","adj","B2"),("snobbish","снобистский","adj","B2"),
    ("sordid","грязный","adj","B2"),("spartan","спартанский","adj","B2"),("stifle","душить","verb","B2"),
    ("stint","срок","noun","B2"),("stoic","стоический","adj","B2"),("stringent","строгий","adj","B2"),
    ("submissive","покорный","adj","B2"),("succinct","краткий","adj","B2"),("superfluous","излишний","adj","B2"),
    ("supple","гибкий","adj","B2"),("surly","угрюмый","adj","B2"),("tenacious","цепкий","adj","B2"),
    ("thrifty","бережливый","adj","B2"),("timorous","робкий","adj","B2"),("transient","преходящий","adj","B2"),
    ("trepidation","трепет","noun","B2"),("turbulent","турбулентный","adj","B2"),("unassuming","скромный","adj","B2"),
    ("unobtrusive","незаметный","adj","B2"),("unrelenting","неумолимый","adj","B2"),("vehement","страстный","adj","B2"),
    ("venerable","почтенный","adj","B2"),("vindictive","мстительный","adj","B2"),("wary","осторожный","adj","B2"),
    ("whimsical","причудливый","adj","B2"),("zealous","ревностный","adj","B2"),
]


def _gen_example(word: str, pos: str) -> str:
    w = word.lower()
    if pos == "verb":
        return f"They tend to {w} in such situations."
    elif pos == "noun":
        return f"The {w} has been widely discussed."
    elif pos == "adj":
        return f"Her approach was remarkably {w}."
    elif pos == "adv":
        return f"He responded {w} to the question."
    elif pos == "prep":
        return f"The result was achieved {w} careful planning."
    elif pos == "pron":
        return f"{word.capitalize()} is responsible for the outcome."
    elif pos == "conj":
        return f"She succeeded {w} the odds were against her."
    elif pos == "num":
        return f"The project costs {w} dollars."
    else:
        return f"This concept is {w}."


def get_frequency_words4() -> list[tuple]:
    result = []
    for word, trans, pos, cefr in _W4:
        example = _gen_example(word, pos)
        result.append((word, trans, pos, example, cefr))
    return result
