"""Frequency words part 3 — B1 words (~500).

Compact format: (word, translation, pos, cefr)
"""

_W3 = [
    ("abandon","покидать","verb","B1"),("abolish","отменять","verb","B1"),("absent","отсутствующий","adj","B1"),
    ("absolute","абсолютный","adj","B1"),("absorb","поглощать","verb","B1"),("abstract","абстрактный","adj","B1"),
    ("absurd","абсурдный","adj","B1"),("abundant","обильный","adj","B1"),("abuse","злоупотребление","noun","B1"),
    ("academic","академический","adj","B1"),("accelerate","ускорять","verb","B1"),("accessible","доступный","adj","B1"),
    ("accommodation","жильё","noun","B1"),("accompany","сопровождать","verb","B1"),("accomplish","выполнять","verb","B1"),
    ("account","счёт","noun","B1"),("accountant","бухгалтер","noun","B1"),("accumulate","накапливать","verb","B1"),
    ("accurate","точный","adj","B1"),("accuse","обвинять","verb","B1"),("accustomed","привычный","adj","B1"),
    ("achievement","достижение","noun","B1"),("acid","кислота","noun","B1"),("acknowledge","признавать","verb","B1"),
    ("acquaintance","знакомый","noun","B1"),("acquire","приобретать","verb","B1"),("acre","акр","noun","B1"),
    ("activate","активировать","verb","B1"),("adaptation","адаптация","noun","B1"),("adequate","адекватный","adj","B1"),
    ("adjust","регулировать","verb","B1"),("administer","управлять","verb","B1"),("administration","администрация","noun","B1"),
    ("admiral","адмирал","noun","B1"),("admission","допуск","noun","B1"),("adolescent","подросток","noun","B1"),
    ("adverse","неблагоприятный","adj","B1"),("aesthetic","эстетический","adj","B1"),("affair","дело","noun","B1"),
    ("affection","привязанность","noun","B1"),("afterward","впоследствии","adv","B1"),("agency","агентство","noun","B1"),
    ("agenda","повестка","noun","B1"),("aggression","агрессия","noun","B1"),("aggressive","агрессивный","adj","B1"),
    ("agitate","агитировать","verb","B1"),("aircraft","самолёт","noun","B1"),("airmail","авиапочта","noun","B1"),
    ("airplane","самолёт","noun","B1"),("alas","увы","intj","B1"),("albeit","хотя","conj","B1"),
    ("alert","бдительный","adj","B1"),("algorithm","алгоритм","noun","B1"),("alien","инопланетный","adj","B1"),
    ("alignment","выравнивание","noun","B1"),("allegation","утверждение","noun","B1"),("allege","утверждать","verb","B1"),
    ("allergy","аллергия","noun","B1"),("alliance","альянс","noun","B1"),("allocate","распределять","verb","B1"),
    ("allowance","allowance","noun","B1"),("alongside","рядом","adv","B1"),("alphabetical","алфавитный","adj","B1"),
    ("alter","изменять","verb","B1"),("alternate","чередовать","verb","B1"),("alternative","альтернатива","noun","B1"),
    ("amateur","любитель","noun","B1"),("amaze","изумлять","verb","B1"),("ambassador","посол","noun","B1"),
    ("ambulance","скорая помощь","noun","B1"),("amend","поправлять","verb","B1"),("amid","среди","prep","B1"),
    ("amount","количество","noun","B1"),("ample","обильный","adj","B1"),("analogy","аналогия","noun","B1"),
    ("analyze","анализировать","verb","B1"),("ancestor","предок","noun","B1"),("ankle","лодыжка","noun","B1"),
    ("anniversary","годовщина","noun","B1"),("anonymous","анонимный","adj","B1"),("anticipate","предвидеть","verb","B1"),
    ("anxiety","тревога","noun","B1"),("anyhow","как бы то ни было","adv","B1"),("anyway","во всяком случае","adv","B1"),
    ("apology","извинение","noun","B1"),("app","приложение","noun","B1"),("apparatus","аппарат","noun","B1"),
    ("appetite","аппетит","noun","B1"),("applaud","аплодировать","verb","B1"),("applicable","применимый","adj","B1"),
    ("applicant","соискатель","noun","B1"),("application","заявка","noun","B1"),("appreciate","оценивать","verb","B1"),
    ("approach","подход","noun","B1"),("approval","одобрение","noun","B1"),("arbitrary","произвольный","adj","B1"),
    ("architect","архитектор","noun","B1"),("archive","архив","noun","B1"),("arithmetic","арифметика","noun","B1"),
    ("array","массив","noun","B1"),("arrogant","высокомерный","adj","B1"),("artisan","ремесленник","noun","B1"),
    ("aspiration","стремление","noun","B1"),("assemble","собирать","verb","B1"),("assert","утверждать","verb","B1"),
    ("assess","оценивать","verb","B1"),("asset","актив","noun","B1"),("assistance","помощь","noun","B1"),
    ("associate","ассоциировать","verb","B1"),("association","ассоциация","noun","B1"),("assumption","предположение","noun","B1"),
    ("astonish","изумлять","verb","B1"),("astronaut","астронавт","noun","B1"),("astronomy","астрономия","noun","B1"),
    ("athlete","атлет","noun","B1"),("atlas","атлас","noun","B1"),("atom","атом","noun","B1"),
    ("attach","прикреплять","verb","B1"),("attain","достигать","verb","B1"),("attempt","попытка","noun","B1"),
    ("attorney","адвокат","noun","B1"),("attribute","атрибут","noun","B1"),("audit","аудит","noun","B1"),
    ("authentic","подлинный","adj","B1"),("autobiography","автобиография","noun","B1"),("automobile","автомобиль","noun","B1"),
    ("autonomous","автономный","adj","B1"),("available","доступный","adj","B1"),("aviation","авиация","noun","B1"),
    ("awake","проснувшийся","adj","B1"),("awareness","осведомлённость","noun","B1"),("backbone","хребет","noun","B1"),
    ("backup","резервная копия","noun","B1"),("bacteria","бактерии","noun","B1"),("badge","значок","noun","B1"),
    ("bankrupt","банкрот","adj","B1"),("banquet","банкет","noun","B1"),("barrel","бочка","noun","B1"),
    ("basin","бассейн","noun","B1"),("bearing","подшипник","noun","B1"),("behalf","от имени","noun","B1"),
    ("beloved","возлюбленный","adj","B1"),("besides","кроме того","adv","B1"),("betray","предавать","verb","B1"),
    ("beverage","напиток","noun","B1"),("beware","остерегаться","verb","B1"),("bias","предвзятость","noun","B1"),
    ("bibliography","библиография","noun","B1"),("bid","ставка","noun","B1"),("billion","миллиард","num","B1"),
    ("bind","связывать","verb","B1"),("biography","биография","noun","B1"),("biological","биологический","adj","B1"),
    ("bleed","кровоточить","verb","B1"),("blossom","цветок","noun","B1"),("blueprint","чертёж","noun","B1"),
    ("blunder","ошибка","noun","B1"),("blunt","тупой","adj","B1"),("blur","размывать","verb","B1"),
    ("board","совет","noun","B1"),("boom","бум","noun","B1"),("boost","повышать","verb","B1"),
    ("border","граница","noun","B1"),("botanical","ботанический","adj","B1"),("bound","связанный","adj","B1"),
    ("bracket","скобка","noun","B1"),("brain","мозг","noun","B1"),("breach","нарушение","noun","B1"),
    ("breakthrough","прорыв","noun","B1"),("breeze","бриз","noun","B1"),("bribe","взятка","noun","B1"),
    ("brick","кирпич","noun","B1"),("brief","краткий","adj","B1"),("brink","край","noun","B1"),
    ("brisk","бодрый","adj","B1"),("brittle","хрупкий","adj","B1"),("brochure","брошюра","noun","B1"),
    ("bronze","бронза","noun","B1"),("brow","бровь","noun","B1"),("browse","просматривать","verb","B1"),
    ("brunch","бранч","noun","B1"),("brutal","жестокий","adj","B1"),("bulletin","бюллетень","noun","B1"),
    ("bump","удар","noun","B1"),("bureaucracy","бюрократия","noun","B1"),("bust","бюст","noun","B1"),
    ("buzz","жужжание","noun","B1"),("calamity","бедствие","noun","B1"),("caliber","калибр","noun","B1"),
    ("callous","бесчувственный","adj","B1"),("candle","свеча","noun","B1"),("carnival","карнавал","noun","B1"),
    ("carve","вырезать","verb","B1"),("casino","казино","noun","B1"),("casual","небрежный","adj","B1"),
    ("cater","обслуживать","verb","B1"),("cellar","подвал","noun","B1"),("census","перепись","noun","B1"),
    ("chancellor","канцлер","noun","B1"),("chapter","глава","noun","B1"),("charm","очарование","noun","B1"),
    ("chase","погоня","noun","B1"),("chill","озноб","noun","B1"),("circulate","циркулировать","verb","B1"),
    ("cite","цитировать","verb","B1"),("civilian","гражданское лицо","noun","B1"),("clarify","уточнять","verb","B1"),
    ("clarity","ясность","noun","B1"),("clause","пункт","noun","B1"),("cognitive","когнитивный","adj","B1"),
    ("coherent","связный","adj","B1"),("coincide","совпадать","verb","B1"),("collaborate","сотрудничать","verb","B1"),
    ("collective","коллективный","adj","B1"),("comet","комета","noun","B1"),("commemorate","увековечивать","verb","B1"),
    ("commence","начинать","verb","B1"),("commodity","товар","noun","B1"),("commonplace","обыденный","adj","B1"),
    ("commute","ездить","verb","B1"),("compact","компактный","adj","B1"),("comparison","сравнение","noun","B1"),
    ("competent","компетентный","adj","B1"),("competition","соревнование","noun","B1"),("compile","составлять","verb","B1"),
    ("complaint","жалоба","noun","B1"),("complement","дополнять","verb","B1"),("complexity","сложность","noun","B1"),
    ("compliance","соответствие","noun","B1"),("complicate","усложнять","verb","B1"),("compliment","комплимент","noun","B1"),
    ("composer","композитор","noun","B1"),("comprehensive","исчерпывающий","adj","B1"),("comprise","состоять из","verb","B1"),
    ("compromise","компромисс","noun","B1"),("compulsory","обязательный","adj","B1"),("compute","вычислять","verb","B1"),
    ("conceal","скрывать","verb","B1"),("concede","уступать","verb","B1"),("conceive","замышлять","verb","B1"),
    ("concentrate","концентрировать","verb","B1"),("conclusion","заключение","noun","B1"),("condemn","осуждать","verb","B1"),
    ("condition","условие","noun","B1"),("confer","совещаться","verb","B1"),("confess","признаваться","verb","B1"),
    ("confident","уверенный","adj","B1"),("confidential","конфиденциальный","adj","B1"),("configuration","конфигурация","noun","B1"),
    ("confine","ограничивать","verb","B1"),("conform","соответствовать","verb","B1"),("confuse","путать","verb","B1"),
    ("conjunction","союз","noun","B1"),("connection","связь","noun","B1"),("conquest","завоевание","noun","B1"),
    ("conscience","совесть","noun","B1"),("conscious","сознательный","adj","B1"),("consensus","консенсус","noun","B1"),
    ("consequently","следовательно","adv","B1"),("conservation","сохранение","noun","B1"),("considerable","значительный","adj","B1"),
    ("consideration","соображение","noun","B1"),("consistent","последовательный","adj","B1"),("constantly","постоянно","adv","B1"),
    ("constitution","конституция","noun","B1"),("construction","строительство","noun","B1"),("consumer","потребитель","noun","B1"),
    ("consumption","потребление","noun","B1"),("contemporary","современник","noun","B1"),("continual","непрерывный","adj","B1"),
    ("continuous","непрерывный","adj","B1"),("contribution","вклад","noun","B1"),("controversial","спорный","adj","B1"),
    ("controversy","полемика","noun","B1"),("convenient","удобный","adj","B1"),("conventional","обычный","adj","B1"),
    ("conversion","превращение","noun","B1"),("convert","превращать","verb","B1"),("convey","передавать","verb","B1"),
    ("conviction","убеждение","noun","B1"),("cooperation","сотрудничество","noun","B1"),("coordinate","координировать","verb","B1"),
    ("core","сердцевина","noun","B1"),("correspond","соответствовать","verb","B1"),("corrupt","коррумпированный","adj","B1"),
    ("counterpart","коллега","noun","B1"),("courtesy","вежливость","noun","B1"),("crucial","решающий","adj","B1"),
    ("cruise","круиз","noun","B1"),("crush","давить","verb","B1"),("curiosity","любопытство","noun","B1"),
    ("curriculum","учебный план","noun","B1"),("cutting","черенок","noun","B1"),("deception","обман","noun","B1"),
    ("deduction","вычет","noun","B1"),("deficiency","недостаток","noun","B1"),("deficit","дефицит","noun","B1"),
    ("delegation","делегация","noun","B1"),("deliberate","преднамеренный","adj","B1"),("denial","отрицание","noun","B1"),
    ("denote","обозначать","verb","B1"),("denounce","денонсировать","verb","B1"),("departure","отправление","noun","B1"),
    ("depletion","истощение","noun","B1"),("deposition","показание","noun","B1"),("deprive","лишать","verb","B1"),
    ("derivative","производный","adj","B1"),("descendant","потомок","noun","B1"),("designation","обозначение","noun","B1"),
    ("despise","презирать","verb","B1"),("destiny","судьба","noun","B1"),("deter","удерживать","verb","B1"),
    ("deteriorate","ухудшаться","verb","B1"),("devastate","опустошать","verb","B1"),("deviation","отклонение","noun","B1"),
    ("devotion","преданность","noun","B1"),("diagnose","диагностировать","verb","B1"),("dictator","диктатор","noun","B1"),
    ("dilemma","дилемма","noun","B1"),("dimension","измерение","noun","B1"),("diminish","уменьшать","verb","B1"),
    ("disability","инвалидность","noun","B1"),("discard","отбрасывать","verb","B1"),("discern","различать","verb","B1"),
    ("disclose","раскрывать","verb","B1"),("discourse","дискурс","noun","B1"),("discretion","благоразумие","noun","B1"),
    ("disgrace","позор","noun","B1"),("disguise","маскировка","noun","B1"),("disillusion","разочарование","noun","B1"),
    ("dismantle","демонтировать","verb","B1"),("dismiss","отклонять","verb","B1"),("disparity","неравенство","noun","B1"),
    ("disperse","рассеивать","verb","B1"),("displace","перемещать","verb","B1"),("dispose","располагать","verb","B1"),
    ("disposition","расположение","noun","B1"),("dispute","спор","noun","B1"),("disrupt","нарушать","verb","B1"),
    ("dissolve","растворять","verb","B1"),("distinct","отчётливый","adj","B1"),("distinguish","различать","verb","B1"),
    ("distort","искажать","verb","B1"),("distribute","распределять","verb","B1"),("diversion","отвлечение","noun","B1"),
    ("diversity","разнообразие","noun","B1"),("divine","божественный","adj","B1"),("doctrine","доктрина","noun","B1"),
    ("domain","область","noun","B1"),("domestic","домашний","adj","B1"),("dominant","господствующий","adj","B1"),
    ("donate","жертвовать","verb","B1"),("doubtful","сомнительный","adj","B1"),("drainage","дренаж","noun","B1"),
    ("dramatic","драматический","adj","B1"),("drastic","радикальный","adj","B1"),("drawback","недостаток","noun","B1"),
    ("dread","страх","noun","B1"),("durable","прочный","adj","B1"),("dwelling","жилище","noun","B1"),
    ("eccentric","эксцентричный","adj","B1"),("eclipse","затмение","noun","B1"),("ecosystem","экосистема","noun","B1"),
    ("elaborate","разрабатывать","verb","B1"),("eligible","подходящий","adj","B1"),("eloquent","красноречивый","adj","B1"),
    ("embark","отправляться","verb","B1"),("embody","воплощать","verb","B1"),("embrace","обнимать","verb","B1"),
    ("emerge","появляться","verb","B1"),("emigrate","эмигрировать","verb","B1"),("emission","выброс","noun","B1"),
    ("emperor","император","noun","B1"),("empire","империя","noun","B1"),("empirical","эмпирический","adj","B1"),
    ("enact","принять закон","verb","B1"),("enclose","окружать","verb","B1"),("encompass","охватывать","verb","B1"),
    ("encounter","встреча","noun","B1"),("endurance","выносливость","noun","B1"),("enforce","принуждать","verb","B1"),
    ("engagement","помолвка","noun","B1"),("enhance","улучшать","verb","B1"),("enlighten","просвещать","verb","B1"),
    ("enrich","обогащать","verb","B1"),("ensemble","ансамбль","noun","B1"),("entail","влечь за собой","verb","B1"),
    ("enthusiastic","энтузиастичный","adj","B1"),("entity","сущность","noun","B1"),("entwine","переплетать","verb","B1"),
    ("envoy","посланник","noun","B1"),("epidemic","эпидемия","noun","B1"),("epoch","эпоха","noun","B1"),
    ("equator","экватор","noun","B1"),("equilibrium","равновесие","noun","B1"),("erode","разрушать","verb","B1"),
    ("essence","сущность","noun","B1"),("eternal","вечный","adj","B1"),("evacuate","эвакуировать","verb","B1"),
    ("evident","очевидный","adj","B1"),("evolution","эволюция","noun","B1"),("exaggerate","преувеличивать","verb","B1"),
    ("exalt","возвышать","verb","B1"),("exceed","превышать","verb","B1"),("exception","исключение","noun","B1"),
    ("excessive","чрезмерный","adj","B1"),("exclude","исключать","verb","B1"),("excrete","выделять","verb","B1"),
    ("execute","выполнять","verb","B1"),("exemplify","иллюстрировать","verb","B1"),("exert","прилагать","verb","B1"),
    ("exhaust","истощать","verb","B1"),("exile","изгнание","noun","B1"),("expansion","расширение","noun","B1"),
    ("expedition","экспедиция","noun","B1"),("expel","исключать","verb","B1"),("expenditure","расход","noun","B1"),
    ("expertise","экспертиза","noun","B1"),("explicit","явный","adj","B1"),("exploit","эксплуатировать","verb","B1"),
    ("expose","подвергать","verb","B1"),("exquisite","изысканный","adj","B1"),("exterior","внешний","adj","B1"),
    ("external","внешний","adj","B1"),("extinct","вымерший","adj","B1"),("extract","извлекать","verb","B1"),
    ("extravagant","экстравагантный","adj","B1"),("fabricate","изготовлять","verb","B1"),("facilitate","облегчать","verb","B1"),
    ("faculty","преподавательский состав","noun","B1"),("famine","голод","noun","B1"),("fascinate","очаровывать","verb","B1"),
    ("fatal","смертельный","adj","B1"),("feasible","осуществимый","adj","B1"),("feeble","слабый","adj","B1"),
    ("feminine","женственный","adj","B1"),("fertile","плодородный","adj","B1"),("fierce","свирепый","adj","B1"),
    ("fluctuate","колебаться","verb","B1"),("foremost","первый","adj","B1"),("forfeit","лишать","verb","B1"),
    ("formidable","грозный","adj","B1"),("fortify","укреплять","verb","B1"),("fragile","хрупкий","adj","B1"),
    ("friction","трение","noun","B1"),("fulfill","выполнять","verb","B1"),("furnish","обставлять","verb","B1"),
    ("garrison","гарнизон","noun","B1"),("generate","генерировать","verb","B1"),("genius","гений","noun","B1"),
    ("genuine","подлинный","adj","B1"),("glorify","прославлять","verb","B1"),("grandeur","величие","noun","B1"),
    ("gratitude","благодарность","noun","B1"),("grievance","жалоба","noun","B1"),("grim","мрачный","adj","B1"),
    ("gruesome","ужасный","adj","B1"),("guarantee","гарантия","noun","B1"),("guidelines","руководящие принципы","noun","B1"),
    ("habitable","пригодный для жилья","adj","B1"),("hardship","лишение","noun","B1"),("hasten","торопиться","verb","B1"),
    ("haunt","преследовать","verb","B1"),("hectic","беспокойный","adj","B1"),("heritage","наследие","noun","B1"),
    ("horrify","ужасать","verb","B1"),("humiliate","унижать","verb","B1"),("hypocrisy","лицемерие","noun","B1"),
    ("identical","идентичный","adj","B1"),("ideology","идеология","noun","B1"),("illuminate","освещать","verb","B1"),
    ("immense","огромный","adj","B1"),("immortal","бессмертный","adj","B1"),("impartial","беспристрастный","adj","B1"),
    ("imperative","повелительный","adj","B1"),("implement","осуществлять","verb","B1"),("implication","подтекст","noun","B1"),
    ("implicit","неявный","adj","B1"),("impose","налагать","verb","B1"),("impulse","импульс","noun","B1"),
    ("inadequate","неадекватный","adj","B1"),("incentive","стимул","noun","B1"),("incidence","частота","noun","B1"),
    ("incline","наклон","noun","B1"),("incorporate","включать","verb","B1"),("incredible","невероятный","adj","B1"),
    ("incur","навлекать","verb","B1"),("indefinite","неопределённый","adj","B1"),("indifference","безразличие","noun","B1"),
    ("indignant","возмущённый","adj","B1"),("induce","побуждать","verb","B1"),("indulge","предаваться","verb","B1"),
    ("inevitable","неизбежный","adj","B1"),("infectious","заразный","adj","B1"),("infer","выводить","verb","B1"),
    ("inferior","худший","adj","B1"),("inflict","наносить","verb","B1"),("inhabit","обитать","verb","B1"),
    ("inherent","присущий","adj","B1"),("inhibit","подавлять","verb","B1"),("initiate","начинать","verb","B1"),
    ("innate","врождённый","adj","B1"),("innovation","нововведение","noun","B1"),("innumerable","бесчисленный","adj","B1"),
    ("inquire","спрашивать","verb","B1"),("insane","безумный","adj","B1"),("insight","проницательность","noun","B1"),
    ("inspect","осматривать","verb","B1"),("instinct","инстинкт","noun","B1"),("intact","неповреждённый","adj","B1"),
    ("integral","неотъемлемый","adj","B1"),("integrate","интегрировать","verb","B1"),("integrity","целостность","noun","B1"),
    ("intensify","усиливать","verb","B1"),("intent","намерение","noun","B1"),("interfere","вмешиваться","verb","B1"),
    ("intermediate","средний","adj","B1"),("intermittent","прерывистый","adj","B1"),("intervene","вмешиваться","verb","B1"),
    ("intimate","близкий","adj","B1"),("intricate","сложный","adj","B1"),("intrinsic","внутренний","adj","B1"),
    ("invade","вторгаться","verb","B1"),("invalid","недействительный","adj","B1"),("inventive","изобретательный","adj","B1"),
    ("invert","переворачивать","verb","B1"),("investigate","расследовать","verb","B1"),("involve","вовлекать","verb","B1"),
    ("irony","ирония","noun","B1"),("irrelevant","неуместный","adj","B1"),("irreversible","необратимый","adj","B1"),
    ("isolate","изолировать","verb","B1"),("jeopardize","подвергать опасности","verb","B1"),("judicial","судебный","adj","B1"),
    ("jurisdiction","юрисдикция","noun","B1"),("justification","оправдание","noun","B1"),("juvenile","юный","adj","B1"),
    ("kindle","разжигать","verb","B1"),("knack","сноровка","noun","B1"),("lament","скорбеть","verb","B1"),
    ("latent","скрытый","adj","B1"),("lavish","роскошный","adj","B1"),("legacy","наследие","noun","B1"),
    ("legitimate","законный","adj","B1"),("lenient","снисходительный","adj","B1"),("lethal","смертельный","adj","B1"),
    ("linger","задерживаться","verb","B1"),("literacy","грамотность","noun","B1"),("luminous","светящийся","adj","B1"),
    ("magnify","увеличивать","verb","B1"),("magnitude","величина","noun","B1"),("majesty","величество","noun","B1"),
    ("malignant","злокачественный","adj","B1"),("manipulate","манипулировать","verb","B1"),("mansion","особняк","noun","B1"),
    ("maritime","морской","adj","B1"),("martial","военный","adj","B1"),("masculine","мужской","adj","B1"),
    ("massive","массивный","adj","B1"),("mature","зрелый","adj","B1"),("maximize","максимизировать","verb","B1"),
    ("meadow","луг","noun","B1"),("meditate","размышлять","verb","B1"),("melancholy","меланхолия","noun","B1"),
    ("memorable","запоминающийся","adj","B1"),("menace","угроза","noun","B1"),("merge","сливать","verb","B1"),
    ("metaphor","метафора","noun","B1"),("midst","середина","noun","B1"),("militant","воинственный","adj","B1"),
    ("minimize","минимизировать","verb","B1"),("minute","мелкий","adj","B1"),("misery","страдание","noun","B1"),
    ("mission","миссия","noun","B1"),("moan","стон","noun","B1"),("modify","модифицировать","verb","B1"),
    ("monarch","монарх","noun","B1"),("monetary","денежный","adj","B1"),("monopoly","монополия","noun","B1"),
    ("monument","памятник","noun","B1"),("morale","боевой дух","noun","B1"),("mortgage","ипотека","noun","B1"),
    ("motif","мотив","noun","B1"),("municipal","муниципальный","adj","B1"),("mutual","взаимный","adj","B1"),
    ("mystery","тайна","noun","B1"),("myth","миф","noun","B1"),("narrative","повествование","noun","B1"),
    ("nasty","мерзкий","adj","B1"),("navigate","навигировать","verb","B1"),("negotiate","вести переговоры","verb","B1"),
    ("neutral","нейтральный","adj","B1"),("nominate","выдвигать","verb","B1"),("notorious","печально известный","adj","B1"),
    ("novelty","новинка","noun","B1"),("nurture","воспитывать","verb","B1"),("obscure","неясный","adj","B1"),
    ("observatory","обсерватория","noun","B1"),("obsess","одержимость","verb","B1"),("obstruct","препятствовать","verb","B1"),
    ("offensive","оскорбительный","adj","B1"),("offset","компенсировать","verb","B1"),("ominous","зловещий","adj","B1"),
    ("omit","пропускать","verb","B1"),("onset","начало","noun","B1"),("opaque","непрозрачный","adj","B1"),
    ("oppress","угнетать","verb","B1"),("optimism","оптимизм","noun","B1"),("option","опция","noun","B1"),
    ("orient","ориентировать","verb","B1"),("originate","происходить","verb","B1"),("outbreak","вспышка","noun","B1"),
    ("outlook","перспектива","noun","B1"),("outrage","возмущение","noun","B1"),("outskirts","окраина","noun","B1"),
    ("overall","в целом","adj","B1"),("overcome","преодолевать","verb","B1"),("overlap","перекрывать","verb","B1"),
    ("overlook","не замечать","verb","B1"),("overwhelm","переполнять","verb","B1"),("pamphlet","памфлет","noun","B1"),
    ("paradise","рай","noun","B1"),("paradox","парадокс","noun","B1"),("parallel","параллель","noun","B1"),
    ("paralyze","парализовать","verb","B1"),("partial","частичный","adj","B1"),("participate","участвовать","verb","B1"),
    ("passion","страсть","noun","B1"),("passive","пассивный","adj","B1"),("patent","патент","noun","B1"),
    ("patriot","патриот","noun","B1"),("patrol","патруль","noun","B1"),("patron","покровитель","noun","B1"),
    ("pave","мостить","verb","B1"),("peasant","крестьянин","noun","B1"),("penalty","штраф","noun","B1"),
    ("pending","в ожидании","adj","B1"),("perceive","воспринимать","verb","B1"),("permanent","постоянный","adj","B1"),
    ("permeate","проникать","verb","B1"),("permit","разрешение","noun","B1"),("perpetual","вечный","adj","B1"),
    ("perplex","озадачивать","verb","B1"),("persist","упорствовать","verb","B1"),("personnel","персонал","noun","B1"),
    ("perspective","перспектива","noun","B1"),("pessimism","пессимизм","noun","B1"),("petition","петиция","noun","B1"),
    ("phenomenon","феномен","noun","B1"),("philosophy","философия","noun","B1"),("picturesque","живописный","adj","B1"),
    ("pioneer","пионер","noun","B1"),("plague","чума","noun","B1"),("plausible","правдоподобный","adj","B1"),
    ("pledge","залог","noun","B1"),("plunge","нырять","verb","B1"),("poignant","трогательный","adj","B1"),
    ("pollute","загрязнять","verb","B1"),("pomp","пышность","noun","B1"),("portray","изображать","verb","B1"),
    ("postpone","откладывать","verb","B1"),("potent","сильнодействующий","adj","B1"),("potential","потенциальный","adj","B1"),
    ("practitioner","практик","noun","B1"),("precaution","мера предосторожности","noun","B1"),("precede","предшествовать","verb","B1"),
    ("precious","драгоценный","adj","B1"),("precise","точный","adj","B1"),("predecessor","предшественник","noun","B1"),
    ("predominant","преобладающий","adj","B1"),("prejudice","предубеждение","noun","B1"),("preliminary","предварительный","adj","B1"),
    ("premature","преждевременный","adj","B1"),("premise","предпосылка","noun","B1"),("premium","премия","noun","B1"),
    ("prescribe","предписывать","verb","B1"),("preserve","сохранять","verb","B1"),("preside","председательствовать","verb","B1"),
    ("prestige","престиж","noun","B1"),("presume","предполагать","verb","B1"),("prevail","преобладать","verb","B1"),
    ("prevalent","распространённый","adj","B1"),("prevention","предотвращение","noun","B1"),("prey","добыча","noun","B1"),
    ("primary","первичный","adj","B1"),("prime","главный","adj","B1"),("primitive","примитивный","adj","B1"),
    ("principal","главный","adj","B1"),("prior","предшествующий","adj","B1"),("privilege","привилегия","noun","B1"),
    ("probe","зонд","noun","B1"),("procedure","процедура","noun","B1"),("proclaim","провозглашать","verb","B1"),
    ("productive","продуктивный","adj","B1"),("profound","глубокий","adj","B1"),("progressive","прогрессивный","adj","B1"),
    ("prohibit","запрещать","verb","B1"),("projector","проектор","noun","B1"),("prolong","продлевать","verb","B1"),
    ("prominent","выдающийся","adj","B1"),("promote","продвигать","verb","B1"),("prompt","быстрый","adj","B1"),
    ("prone","склонный","adj","B1"),("propaganda","пропаганда","noun","B1"),("propel","двигать","verb","B1"),
    ("proportion","пропорция","noun","B1"),("proposition","предложение","noun","B1"),("prose","проза","noun","B1"),
    ("prosecute","судить","verb","B1"),("prosper","процветать","verb","B1"),("prosperity","процветание","noun","B1"),
    ("protocol","протокол","noun","B1"),("provoke","провоцировать","verb","B1"),("puberty","половое созревание","noun","B1"),
    ("publicize","рекламировать","verb","B1"),("punctual","пунктуальный","adj","B1"),("purchase","покупка","noun","B1"),
    ("pursue","преследовать","verb","B1"),("puzzle","головоломка","noun","B1"),("quench","утолять","verb","B1"),
    ("quest","поиск","noun","B1"),("quiver","дрожать","verb","B1"),("quota","квота","noun","B1"),
    ("radical","радикальный","adj","B1"),("rage","ярость","noun","B1"),("raid","набег","noun","B1"),
    ("rational","рациональный","adj","B1"),("ravage","опустошать","verb","B1"),("realm","царство","noun","B1"),
    ("reap","жать","verb","B1"),("reassure","успокаивать","verb","B1"),("rebel","мятежник","noun","B1"),
    ("rebellion","мятеж","noun","B1"),("recession","спад","noun","B1"),("recipient","получатель","noun","B1"),
    ("recite","декламировать","verb","B1"),("reckon","считать","verb","B1"),("reclaim","возвращать","verb","B1"),
    ("recommend","рекомендовать","verb","B1"),("reconcile","примирять","verb","B1"),("recover","восстанавливать","verb","B1"),
    ("recreation","отдых","noun","B1"),("recruit","набирать","verb","B1"),("rectify","исправлять","verb","B1"),
    ("recur","повторяться","verb","B1"),("redeem","выкупать","verb","B1"),("redundant","избыточный","adj","B1"),
    ("refine","очищать","verb","B1"),("reflect","отражать","verb","B1"),("reform","реформа","noun","B1"),
    ("refuge","убежище","noun","B1"),("refund","возврат","noun","B1"),("regain","возвращать","verb","B1"),
    ("regime","режим","noun","B1"),("regulate","регулировать","verb","B1"),("rehabilitation","реабилитация","noun","B1"),
    ("reign","царствовать","verb","B1"),("reimburse","возмещать","verb","B1"),("reinforce","подкреплять","verb","B1"),
    ("relax","расслабляться","verb","B1"),("relay","передавать","verb","B1"),("release","выпуск","noun","B1"),
    ("relevant","уместный","adj","B1"),("reliable","надёжный","adj","B1"),("relic","реликвия","noun","B1"),
    ("reluctant","неохотный","adj","B1"),("remainder","остаток","noun","B1"),("remedy","средство","noun","B1"),
    ("remind","напоминать","verb","B1"),("remnant","остаток","noun","B1"),("renovate","обновлять","verb","B1"),
    ("repay","отплачивать","verb","B1"),("repeal","отменять","verb","B1"),("repeatedly","неоднократно","adv","B1"),
    ("repel","отталкивать","verb","B1"),("reproduce","размножаться","verb","B1"),("republic","республика","noun","B1"),
    ("reputation","репутация","noun","B1"),("resemble","походить","verb","B1"),("resent","обижаться","verb","B1"),
    ("reside","проживать","verb","B1"),("resign","подавать в отставку","verb","B1"),("resist","сопротивляться","verb","B1"),
    ("resolution","резолюция","noun","B1"),("resolve","решать","verb","B1"),("resort","курорт","noun","B1"),
    ("respective","соответствующий","adj","B1"),("restore","восстанавливать","verb","B1"),("restrain","сдерживать","verb","B1"),
    ("restrict","ограничивать","verb","B1"),("retain","удерживать","verb","B1"),("retreat","отступление","noun","B1"),
    ("retrieve","извлекать","verb","B1"),("reveal","раскрывать","verb","B1"),("revenge","месть","noun","B1"),
    ("revenue","доход","noun","B1"),("reverse","менять на противоположный","verb","B1"),("revise","пересматривать","verb","B1"),
    ("revolt","восстание","noun","B1"),("revolve","вращаться","verb","B1"),("ridiculous","смехотворный","adj","B1"),
    ("rigid","жёсткий","adj","B1"),("robust","крепкий","adj","B1"),("romance","роман","noun","B1"),
    ("sacred","священный","adj","B1"),("safeguard","защита","noun","B1"),("sailor","моряк","noun","B1"),
    ("sanction","санкция","noun","B1"),("satellite","спутник","noun","B1"),("satisfy","удовлетворять","verb","B1"),
    ("scarcely","едва","adv","B1"),("scatter","разбрасывать","verb","B1"),("scenic","живописный","adj","B1"),
    ("scheme","схема","noun","B1"),("scholar","учёный","noun","B1"),("scorn","презрение","noun","B1"),
    ("scramble","карабкаться","verb","B1"),("scrap","обрезок","noun","B1"),("scratch","царапать","verb","B1"),
    ("screw","винт","noun","B1"),("script","сценарий","noun","B1"),("scrutiny","придирчивый осмотр","noun","B1"),
    ("seam","шов","noun","B1"),("sector","сектор","noun","B1"),("secure","безопасный","adj","B1"),
    ("seemingly","по-видимому","adv","B1"),("segregate","разделять","verb","B1"),("sensation","ощущение","noun","B1"),
    ("sentiment","чувство","noun","B1"),("sequence","последовательность","noun","B1"),("serene","безмятежный","adj","B1"),
    ("severe","суровый","adj","B1"),("shatter","разбивать","verb","B1"),("sheer","чистый","adj","B1"),
    ("shelter","укрытие","noun","B1"),("shield","щит","noun","B1"),("shrewd","проницательный","adj","B1"),
    ("shrub","кустарник","noun","B1"),("siege","осада","noun","B1"),("simultaneous","одновременный","adj","B1"),
    ("sinister","зловещий","adj","B1"),("skeptic","скептик","noun","B1"),("slavery","рабство","noun","B1"),
    ("slim","тонкий","adj","B1"),("slogan","лозунг","noun","B1"),("slot","щель","noun","B1"),
    ("slump","спад","noun","B1"),("smuggle","контрабандировать","verb","B1"),("snatch","выхватывать","verb","B1"),
    ("soar","парить","verb","B1"),("sober","трезвый","adj","B1"),("solemn","торжественный","adj","B1"),
    ("solicit","просить","verb","B1"),("solidarity","солидарность","noun","B1"),("solitary","одинокий","adj","B1"),
    ("soluble","растворимый","adj","B1"),("sophisticated","сложный","adj","B1"),("sovereign","суверенный","adj","B1"),
    ("span","размах","noun","B1"),("spark","искра","noun","B1"),("spawn","порождать","verb","B1"),
    ("specify","указывать","verb","B1"),("specimen","образец","noun","B1"),("spectacle","зрелище","noun","B1"),
    ("spectator","зритель","noun","B1"),("spectrum","спектр","noun","B1"),("speculate","размышлять","verb","B1"),
    ("sphere","сфера","noun","B1"),("spill","проливать","verb","B1"),("spiral","спираль","noun","B1"),
    ("spontaneous","спонтанный","adj","B1"),("spouse","супруг","noun","B1"),("sprawl","расползаться","verb","B1"),
    ("sprint","спринт","noun","B1"),("stagnant","застойный","adj","B1"),("stamina","выносливость","noun","B1"),
    ("startling","поразительный","adj","B1"),("stationary","неподвижный","adj","B1"),("statistical","статистический","adj","B1"),
    ("status","статус","noun","B1"),("statute","статут","noun","B1"),("steadfast","твёрдый","adj","B1"),
    ("stereotype","стереотип","noun","B1"),("stimulus","стимул","noun","B1"),("stipulate","обусловливать","verb","B1"),
    ("stir","мешать","verb","B1"),("stray","заблудиться","verb","B1"),("strenuous","напряжённый","adj","B1"),
    ("stride","шаг","noun","B1"),("strife","борьба","noun","B1"),("striking","поразительный","adj","B1"),
    ("strive","стремиться","verb","B1"),("stumble","спотыкаться","verb","B1"),("stun","оглушать","verb","B1"),
    ("sturdy","крепкий","adj","B1"),("submit","подчиняться","verb","B1"),("subordinate","подчинённый","adj","B1"),
    ("subscribe","подписываться","verb","B1"),("subsequent","последующий","adj","B1"),("substance","вещество","noun","B1"),
    ("substantial","значительный","adj","B1"),("subtle","тонкий","adj","B1"),("succeed","преуспевать","verb","B1"),
    ("successor","преемник","noun","B1"),("sue","подавать в суд","verb","B1"),("sufficient","достаточный","adj","B1"),
    ("summit","вершина","noun","B1"),("summon","вызывать","verb","B1"),("superb","превосходный","adj","B1"),
    ("superficial","поверхностный","adj","B1"),("superintendent","надзиратель","noun","B1"),("supplement","дополнение","noun","B1"),
    ("suppress","подавлять","verb","B1"),("surge","волна","noun","B1"),("surplus","излишек","noun","B1"),
    ("surrender","капитуляция","noun","B1"),("surveillance","наблюдение","noun","B1"),("susceptible","восприимчивый","adj","B1"),
    ("suspend","приостанавливать","verb","B1"),("suspense","напряжение","noun","B1"),("sustain","поддерживать","verb","B1"),
    ("sustainable","устойчивый","adj","B1"),("swamp","болото","noun","B1"),("swap","менять","verb","B1"),
    ("sympathy","сочувствие","noun","B1"),("symphony","симфония","noun","B1"),("symposium","симпозиум","noun","B1"),
    ("syndrome","синдром","noun","B1"),("synthesis","синтез","noun","B1"),("tactic","тактика","noun","B1"),
    ("tan","загар","noun","B1"),("tangle","запутывать","verb","B1"),("tariff","тариф","noun","B1"),
    ("taunt","дразнить","verb","B1"),("tedious","утомительный","adj","B1"),("temperament","темперамент","noun","B1"),
    ("tempo","темп","noun","B1"),("tempt","соблазнять","verb","B1"),("tenant","арендатор","noun","B1"),
    ("tender","нежный","adj","B1"),("tenure","полномочие","noun","B1"),("terminal","терминал","noun","B1"),
    ("terrain","местность","noun","B1"),("testimony","показание","noun","B1"),("textile","текстиль","noun","B1"),
    ("thaw","таять","verb","B1"),("theft","кража","noun","B1"),("theoretical","теоретический","adj","B1"),
    ("therapy","терапия","noun","B1"),("thereafter","после этого","adv","B1"),("thereby","тем самым","adv","B1"),
    ("thigh","бедро","noun","B1"),("thorough","тщательный","adj","B1"),("threshold","порог","noun","B1"),
    ("thrive","процветать","verb","B1"),("thrust","толчок","noun","B1"),("tick","отмечать","verb","B1"),
    ("tidy","опрятный","adj","B1"),("tilt","наклон","noun","B1"),("timber","древесина","noun","B1"),
    ("timid","робкий","adj","B1"),("tissue","ткань","noun","B1"),("tolerant","терпимый","adj","B1"),
    ("toll","пошлина","noun","B1"),("topple","свергать","verb","B1"),("torment","мука","noun","B1"),
    ("torrent","поток","noun","B1"),("torture","пытка","noun","B1"),("toss","бросать","verb","B1"),
    ("toxic","токсичный","adj","B1"),("tract","участок","noun","B1"),("tradition","традиция","noun","B1"),
    ("tragic","трагический","adj","B1"),("trait","черта","noun","B1"),("tranquil","спокойный","adj","B1"),
    ("transit","транзит","noun","B1"),("transition","переход","noun","B1"),("transparent","прозрачный","adj","B1"),
    ("transplant","пересадка","noun","B1"),("trauma","травма","noun","B1"),("tremble","дрожать","verb","B1"),
    ("tremendous","огромный","adj","B1"),("trigger","спусковой крючок","noun","B1"),("trillion","триллион","num","B1"),
    ("triumph","триумф","noun","B1"),("trolley","тележка","noun","B1"),("troop","войско","noun","B1"),
    ("truce","перемирие","noun","B1"),("trumpet","труба","noun","B1"),("truncate","усекать","verb","B1"),
    ("turbine","турбина","noun","B1"),("turmoil","смятение","noun","B1"),("turnover","оборот","noun","B1"),
    ("twilight","сумерки","noun","B1"),("twist","скручивать","verb","B1"),("tyranny","тирания","noun","B1"),
    ("unanimous","единогласный","adj","B1"),("undergo","претерпевать","verb","B1"),("underline","подчёркивать","verb","B1"),
    ("underlying","лежащий в основе","adj","B1"),("undermine","подрывать","verb","B1"),("undertake","браться за","verb","B1"),
    ("unemployment","безработица","noun","B1"),("unfold","разворачивать","verb","B1"),("uniform","однородный","adj","B1"),
    ("unify","объединять","verb","B1"),("unique","уникальный","adj","B1"),("universe","вселенная","noun","B1"),
    ("unprecedented","беспрецедентный","adj","B1"),("upbringing","воспитание","noun","B1"),("upheaval","переворот","noun","B1"),
    ("uphold","поддерживать","verb","B1"),("upright","вертикальный","adj","B1"),("uproot","выкорчёвывать","verb","B1"),
    ("upsurge","подъём","noun","B1"),("upward","вверх","adv","B1"),("urge","настоять","verb","B1"),
    ("utilize","использовать","verb","B1"),("utmost","крайний","adj","B1"),("utter","полный","adj","B1"),
    ("vacancy","вакансия","noun","B1"),("vaccine","вакцина","noun","B1"),("valid","действительный","adj","B1"),
    ("valve","клапан","noun","B1"),("vanish","исчезать","verb","B1"),("variable","переменная","noun","B1"),
    ("vast","обширный","adj","B1"),("vehicle","транспортное средство","noun","B1"),("venture","предприятие","noun","B1"),
    ("verdict","вердикт","noun","B1"),("verify","проверять","verb","B1"),("versatile","разносторонний","adj","B1"),
    ("veteran","ветеран","noun","B1"),("veto","вето","noun","B1"),("viable","жизнеспособный","adj","B1"),
    ("vigorous","энергичный","adj","B1"),("vindicate","оправдывать","verb","B1"),("vintage","винтажный","adj","B1"),
    ("viral","вирусный","adj","B1"),("virtual","виртуальный","adj","B1"),("virtue","добродетель","noun","B1"),
    ("visionary","провидец","noun","B1"),("vital","жизненно важный","adj","B1"),("vivid","яркий","adj","B1"),
    ("volcano","вулкан","noun","B1"),("volume","объём","noun","B1"),("volunteer","волонтёр","noun","B1"),
    ("vow","обет","noun","B1"),("vulgar","вульгарный","adj","B1"),("vulnerable","уязвимый","adj","B1"),
    ("wander","бродить","verb","B1"),("warehouse","склад","noun","B1"),("warfare","война","noun","B1"),
    ("warrant","ордер","noun","B1"),("warranty","гарантия","noun","B1"),("warrior","воин","noun","B1"),
    ("wary","осторожный","adj","B1"),("watershed","водораздел","noun","B1"),("weave","ткать","verb","B1"),
    ("wedge","клин","noun","B1"),("weird","странный","adj","B1"),("wharf","причал","noun","B1"),
    ("whereby","посредством чего","adv","B1"),("whisker","вибрисс","noun","B1"),("wholesale","оптовый","adj","B1"),
    ("wicked","злой","adj","B1"),("widespread","широко распространённый","adj","B1"),("wield","властвовать","verb","B1"),
    ("wildlife","дикая природа","noun","B1"),("withdraw","отзывать","verb","B1"),("withhold","удерживать","verb","B1"),
    ("withstand","выдерживать","verb","B1"),("witness","свидетель","noun","B1"),("witty","остроумный","adj","B1"),
    ("wreck","обломки","noun","B1"),("wrestle","бороться","verb","B1"),("wring","выжимать","verb","B1"),
    ("yield","уступать","verb","B1"),("zeal","рвение","noun","B1"),("zenith","зенит","noun","B1"),
    ("zone","зона","noun","B1"),("aggregate","совокупность","noun","B1"),("agitate","волновать","verb","B1"),
    ("ailment","недуг","noun","B1"),("airway","воздушный путь","noun","B1"),("allude","намекать","verb","B1"),
    ("allure","привлекать","verb","B1"),("almighty","всемогущий","adj","B1"),("alloy","сплав","noun","B1"),
    ("amplify","усиливать","verb","B1"),("anecdote","анекдот","noun","B1"),("angular","угловой","adj","B1"),
    ("antique","антикварный","adj","B1"),("appealing","привлекательный","adj","B1"),("appendix","приложение","noun","B1"),
    ("appraise","оценивать","verb","B1"),("apprehend","арестовывать","verb","B1"),("arid","засушливый","adj","B1"),
    ("aristocracy","аристократия","noun","B1"),("arouse","пробуждать","verb","B1"),("articulate","чётко выражать","verb","B1"),
    ("artifact","артефакт","noun","B1"),("ascend","подниматься","verb","B1"),("assimilate","усваивать","verb","B1"),
    ("astronomer","астроном","noun","B1"),("asylum","убежище","noun","B1"),("augment","увеличивать","verb","B1"),
    ("automate","автоматизировать","verb","B1"),("avail","польза","noun","B1"),("avert","предотвращать","verb","B1"),
    ("awe","трепет","noun","B1"),("backdrop","фон","noun","B1"),("baffle","ставить в тупик","verb","B1"),
    ("bald","лысый","adj","B1"),("barter","бартер","noun","B1"),("battered","потрёпанный","adj","B1"),
    ("belongings","вещи","noun","B1"),("benchmark","эталон","noun","B1"),("beneficial","полезный","adj","B1"),
    ("bilateral","двусторонний","adj","B1"),("bitter","горький","adj","B1"),("bizarre","странный","adj","B1"),
    ("bleak","мрачный","adj","B1"),("bliss","блаженство","noun","B1"),("blockade","блокада","noun","B1"),
    ("bourbon","бурбон","noun","B1"),("bygone","прошлый","adj","B1"),("bylaw","устав","noun","B1"),
    ("callous","бесчувственный","adj","B1"),("caliber","калибр","noun","B1"),("canvas","холст","noun","B1"),
    ("capable","способный","adj","B1"),("caption","подпись","noun","B1"),("carnival","карнавал","noun","B1"),
    ("casual","небрежный","adj","B1"),("cater","обслуживать","verb","B1"),("census","перепись","noun","B1"),
    ("chancellor","канцлер","noun","B1"),("chaos","хаос","noun","B1"),("chill","озноб","noun","B1"),
    ("circuit","схема","noun","B1"),("cite","цитировать","verb","B1"),("cognitive","когнитивный","adj","B1"),
    ("coherent","связный","adj","B1"),("coincide","совпадать","verb","B1"),("collaborate","сотрудничать","verb","B1"),
    ("collective","коллективный","adj","B1"),("comet","комета","noun","B1"),("commemorate","увековечивать","verb","B1"),
    ("commence","начинать","verb","B1"),("commodity","товар","noun","B1"),("commonplace","обыденный","adj","B1"),
    ("commute","ездить","verb","B1"),("compact","компактный","adj","B1"),("comparison","сравнение","noun","B1"),
    ("competent","компетентный","adj","B1"),("competition","соревнование","noun","B1"),("compile","составлять","verb","B1"),
    ("complaint","жалоба","noun","B1"),("complement","дополнять","verb","B1"),("complexity","сложность","noun","B1"),
    ("compliance","соответствие","noun","B1"),("complicate","усложнять","verb","B1"),("compliment","комплимент","noun","B1"),
    ("composer","композитор","noun","B1"),("comprehensive","исчерпывающий","adj","B1"),("comprise","состоять из","verb","B1"),
    ("compromise","компромисс","noun","B1"),("compulsory","обязательный","adj","B1"),("compute","вычислять","verb","B1"),
    ("conceal","скрывать","verb","B1"),("concede","уступать","verb","B1"),("conceive","замышлять","verb","B1"),
    ("concentrate","концентрировать","verb","B1"),("conclusion","заключение","noun","B1"),("condemn","осуждать","verb","B1"),
    ("condition","условие","noun","B1"),("confer","совещаться","verb","B1"),("confess","признаваться","verb","B1"),
    ("confident","уверенный","adj","B1"),("confidential","конфиденциальный","adj","B1"),("configuration","конфигурация","noun","B1"),
    ("confine","ограничивать","verb","B1"),("conform","соответствовать","verb","B1"),("confuse","путать","verb","B1"),
    ("conjunction","союз","noun","B1"),("connection","связь","noun","B1"),("conquest","завоевание","noun","B1"),
    ("conscience","совесть","noun","B1"),("conscious","сознательный","adj","B1"),("consensus","консенсус","noun","B1"),
    ("consequently","следовательно","adv","B1"),("conservation","сохранение","noun","B1"),("considerable","значительный","adj","B1"),
    ("consideration","соображение","noun","B1"),("consistent","последовательный","adj","B1"),("constantly","постоянно","adv","B1"),
    ("constitution","конституция","noun","B1"),("construction","строительство","noun","B1"),("consumer","потребитель","noun","B1"),
    ("consumption","потребление","noun","B1"),("contemporary","современник","noun","B1"),("continual","непрерывный","adj","B1"),
    ("continuous","непрерывный","adj","B1"),("contribution","вклад","noun","B1"),("controversial","спорный","adj","B1"),
    ("controversy","полемика","noun","B1"),("convenient","удобный","adj","B1"),("conventional","обычный","adj","B1"),
    ("conversion","превращение","noun","B1"),("convert","превращать","verb","B1"),("convey","передавать","verb","B1"),
    ("conviction","убеждение","noun","B1"),("cooperation","сотрудничество","noun","B1"),("coordinate","координировать","verb","B1"),
    ("core","сердцевина","noun","B1"),("correspond","соответствовать","verb","B1"),("corrupt","коррумпированный","adj","B1"),
    ("counterpart","коллега","noun","B1"),("courtesy","вежливость","noun","B1"),("crucial","решающий","adj","B1"),
    ("cruise","круиз","noun","B1"),("crush","давить","verb","B1"),("curiosity","любопытство","noun","B1"),
    ("curriculum","учебный план","noun","B1"),("cutting","черенок","noun","B1"),
]


def _gen_example(word: str, pos: str) -> str:
    w = word.lower()
    if pos == "verb":
        return f"They {w} regularly."
    elif pos == "noun":
        return f"The {w} was discussed."
    elif pos == "adj":
        return f"The result is {w}."
    elif pos == "adv":
        return f"He acted {w}."
    elif pos == "prep":
        return f"Sit {w} the table."
    elif pos == "pron":
        return f"{word.capitalize()} knows the answer."
    elif pos == "conj":
        return f"She stayed {w} he left."
    elif pos == "num":
        return f"There are {w} options."
    elif pos == "intj":
        return f"{word.capitalize()}! That's too bad."
    else:
        return f"This is {w}."


def get_frequency_words3() -> list[tuple]:
    result = []
    for word, trans, pos, cefr in _W3:
        example = _gen_example(word, pos)
        result.append((word, trans, pos, example, cefr))
    return result
