"""Generate 3000+ frequency words programmatically for the word database.

Instead of storing 3000 words as text, we generate them from compact tuples.
This covers NGSL 1.2 + Oxford 3000/5000 core vocabulary.
"""

from __future__ import annotations

# Compact format: (word, translation, pos, cefr)
# Example will be auto-generated.

_W = [
    # A1 — 500 core words (most frequent English words)
    ("able","способный","adj","A1"),("about","о, около","prep","A1"),("above","выше","prep","A1"),
    ("accept","принимать","verb","A1"),("account","счёт","noun","A1"),("across","через","prep","A1"),
    ("act","действовать","verb","A1"),("action","действие","noun","A1"),("active","активный","adj","A1"),
    ("actor","актёр","noun","A1"),("add","добавлять","verb","A1"),("address","адрес","noun","A1"),
    ("adult","взрослый","noun","A1"),("advice","совет","noun","A1"),("afraid","боящийся","adj","A1"),
    ("after","после","prep","A1"),("afternoon","день","noun","A1"),("again","снова","adv","A1"),
    ("against","против","prep","A1"),("age","возраст","noun","A1"),("agree","соглашаться","verb","A1"),
    ("air","воздух","noun","A1"),("airport","аэропорт","noun","A1"),("all","все","det","A1"),
    ("almost","почти","adv","A1"),("alone","один","adv","A1"),("along","вдоль","prep","A1"),
    ("already","уже","adv","A1"),("also","также","adv","A1"),("always","всегда","adv","A1"),
    ("among","среди","prep","A1"),("amount","количество","noun","A1"),("and","и","conj","A1"),
    ("animal","животное","noun","A1"),("another","другой","det","A1"),("answer","ответ","noun","A1"),
    ("any","любой","det","A1"),("anyone","кто-нибудь","pron","A1"),("anything","что-нибудь","pron","A1"),
    ("area","район","noun","A1"),("arm","рука","noun","A1"),("army","армия","noun","A1"),
    ("around","вокруг","prep","A1"),("arrive","прибывать","verb","A1"),("art","искусство","noun","A1"),
    ("as","как","conj","A1"),("ask","спрашивать","verb","A1"),("asleep","спящий","adj","A1"),
    ("at","у, в","prep","A1"),("attack","нападать","verb","A1"),("attempt","попытка","noun","A1"),
    ("attention","внимание","noun","A1"),("aunt","тётя","noun","A1"),("autumn","осень","noun","A1"),
    ("available","доступный","adj","A1"),("awake","проснувшийся","adj","A1"),("away","прочь","adv","A1"),
    ("baby","малыш","noun","A1"),("back","спина","noun","A1"),("bad","плохой","adj","A1"),
    ("bag","сумка","noun","A1"),("bake","печь","verb","A1"),("ball","мяч","noun","A1"),
    ("band","группа","noun","A1"),("bank","банк","noun","A1"),("bar","бар","noun","A1"),
    ("base","основа","noun","A1"),("basic","базовый","adj","A1"),("bath","ванна","noun","A1"),
    ("be","быть","verb","A1"),("beach","пляж","noun","A1"),("bear","медведь","noun","A1"),
    ("beat","бить","verb","A1"),("beautiful","красивый","adj","A1"),("because","потому что","conj","A1"),
    ("become","становиться","verb","A1"),("bed","кровать","noun","A1"),("before","до","prep","A1"),
    ("begin","начинать","verb","A1"),("behind","за","prep","A1"),("believe","верить","verb","A1"),
    ("bell","звонок","noun","A1"),("below","ниже","prep","A1"),("beside","рядом","prep","A1"),
    ("best","лучший","adj","A1"),("better","лучше","adj","A1"),("between","между","prep","A1"),
    ("bicycle","велосипед","noun","A1"),("big","большой","adj","A1"),("bike","велосипед","noun","A1"),
    ("bird","птица","noun","A1"),("birth","рождение","noun","A1"),("birthday","день рождения","noun","A1"),
    ("bit","кусочек","noun","A1"),("black","чёрный","adj","A1"),("blanket","одеяло","noun","A1"),
    ("blood","кровь","noun","A1"),("blow","дуть","verb","A1"),("blue","синий","adj","A1"),
    ("board","доска","noun","A1"),("boat","лодка","noun","A1"),("body","тело","noun","A1"),
    ("boil","кипятить","verb","A1"),("book","книга","noun","A1"),("border","граница","noun","A1"),
    ("born","рождённый","verb","A1"),("borrow","одалживать","verb","A1"),("boss","начальник","noun","A1"),
    ("both","оба","det","A1"),("bottle","бутылка","noun","A1"),("bottom","дно","noun","A1"),
    ("bowl","миска","noun","A1"),("box","коробка","noun","A1"),("boy","мальчик","noun","A1"),
    ("brain","мозг","noun","A1"),("branch","ветка","noun","A1"),("brave","смелый","adj","A1"),
    ("bread","хлеб","noun","A1"),("break","ломать","verb","A1"),("breakfast","завтрак","noun","A1"),
    ("breathe","дышать","verb","A1"),("brick","кирпич","noun","A1"),("bridge","мост","noun","A1"),
    ("brief","краткий","adj","A1"),("bright","яркий","adj","A1"),("bring","приносить","verb","A1"),
    ("broad","широкий","adj","A1"),("broken","сломанный","adj","A1"),("brother","брат","noun","A1"),
    ("brown","коричневый","adj","A1"),("brush","щётка","noun","A1"),("build","строить","verb","A1"),
    ("building","здание","noun","A1"),("burn","гореть","verb","A1"),("bus","автобус","noun","A1"),
    ("business","бизнес","noun","A1"),("busy","занятый","adj","A1"),("but","но","conj","A1"),
    ("butter","масло","noun","A1"),("button","кнопка","noun","A1"),("buy","покупать","verb","A1"),
    ("cake","торт","noun","A1"),("call","звонить","verb","A1"),("calm","спокойный","adj","A1"),
    ("camera","камера","noun","A1"),("camp","лагерь","noun","A1"),("can","мочь","verb","A1"),
    ("cap","кепка","noun","A1"),("car","машина","noun","A1"),("card","карта","noun","A1"),
    ("care","забота","noun","A1"),("careful","осторожный","adj","A1"),("carry","носить","verb","A1"),
    ("case","случай","noun","A1"),("cash","наличные","noun","A1"),("cat","кошка","noun","A1"),
    ("catch","ловить","verb","A1"),("cause","причина","noun","A1"),("ceiling","потолок","noun","A1"),
    ("celebrate","праздновать","verb","A1"),("cell","клетка","noun","A1"),("center","центр","noun","A1"),
    ("certain","определённый","adj","A1"),("chair","стул","noun","A1"),("chance","шанс","noun","A1"),
    ("change","менять","verb","A1"),("channel","канал","noun","A1"),("character","характер","noun","A1"),
    ("charge","заряжать","verb","A1"),("cheap","дешёвый","adj","A1"),("check","проверять","verb","A1"),
    ("cheese","сыр","noun","A1"),("chicken","курица","noun","A1"),("child","ребёнок","noun","A1"),
    ("choose","выбирать","verb","A1"),("church","церковь","noun","A1"),("circle","круг","noun","A1"),
    ("city","город","noun","A1"),("class","класс","noun","A1"),("clean","чистый","adj","A1"),
    ("clear","ясный","adj","A1"),("climb","лезть","verb","A1"),("clock","часы","noun","A1"),
    ("close","закрывать","verb","A1"),("cloth","ткань","noun","A1"),("clothes","одежда","noun","A1"),
    ("cloud","облако","noun","A1"),("club","клуб","noun","A1"),("coast","побережье","noun","A1"),
    ("coat","пальто","noun","A1"),("coffee","кофе","noun","A1"),("coin","монета","noun","A1"),
    ("cold","холодный","adj","A1"),("collect","собирать","verb","A1"),("college","колледж","noun","A1"),
    ("color","цвет","noun","A1"),("come","приходить","verb","A1"),("comfortable","удобный","adj","A1"),
    ("common","обычный","adj","A1"),("company","компания","noun","A1"),("complete","полный","adj","A1"),
    ("computer","компьютер","noun","A1"),("condition","условие","noun","A1"),("connect","соединять","verb","A1"),
    ("consider","рассматривать","verb","A1"),("contact","контакт","noun","A1"),("contain","содержать","verb","A1"),
    ("continue","продолжать","verb","A1"),("control","контроль","noun","A1"),("cook","готовить","verb","A1"),
    ("cool","прохладный","adj","A1"),("copy","копия","noun","A1"),("corner","угол","noun","A1"),
    ("correct","правильный","adj","A1"),("cost","стоить","verb","A1"),("cotton","хлопок","noun","A1"),
    ("couch","диван","noun","A1"),("country","страна","noun","A1"),("couple","пара","noun","A1"),
    ("course","курс","noun","A1"),("court","суд","noun","A1"),("cover","покрывать","verb","A1"),
    ("cow","корова","noun","A1"),("crash","авария","noun","A1"),("crazy","сумасшедший","adj","A1"),
    ("cream","крем","noun","A1"),("create","создавать","verb","A1"),("credit","кредит","noun","A1"),
    ("crew","команда","noun","A1"),("crime","преступление","noun","A1"),("cross","пересекать","verb","A1"),
    ("crowd","толпа","noun","A1"),("cry","плакать","verb","A1"),("cup","чашка","noun","A1"),
    ("current","текущий","adj","A1"),("cut","резать","verb","A1"),("daily","ежедневный","adj","A1"),
    ("damage","ущерб","noun","A1"),("dance","танцевать","verb","A1"),("danger","опасность","noun","A1"),
    ("dark","тёмный","adj","A1"),("data","данные","noun","A1"),("date","дата","noun","A1"),
    ("daughter","дочь","noun","A1"),("day","день","noun","A1"),("dead","мёртвый","adj","A1"),
    ("deal","сделка","noun","A1"),("dear","дорогой","adj","A1"),("death","смерть","noun","A1"),
    ("decide","решать","verb","A1"),("deep","глубокий","adj","A1"),("defend","защищать","verb","A1"),
    ("degree","градус","noun","A1"),("delay","задержка","noun","A1"),("deliver","доставлять","verb","A1"),
    ("demand","требование","noun","A1"),("depend","зависеть","verb","A1"),("describe","описывать","verb","A1"),
    ("desert","пустыня","noun","A1"),("design","дизайн","noun","A1"),("desk","стол","noun","A1"),
    ("detail","деталь","noun","A1"),("develop","развивать","verb","A1"),("device","устройство","noun","A1"),
    ("dial","набирать","verb","A1"),("die","умирать","verb","A1"),("different","разный","adj","A1"),
    ("difficult","трудный","adj","A1"),("dig","копать","verb","A1"),("dinner","ужин","noun","A1"),
    ("direct","прямой","adj","A1"),("direction","направление","noun","A1"),("dirt","грязь","noun","A1"),
    ("dirty","грязный","adj","A1"),("disappear","исчезать","verb","A1"),("discover","обнаруживать","verb","A1"),
    ("distance","расстояние","noun","A1"),("divide","делить","verb","A1"),("do","делать","verb","A1"),
    ("doctor","доктор","noun","A1"),("dog","собака","noun","A1"),("dollar","доллар","noun","A1"),
    ("door","дверь","noun","A1"),("down","вниз","adv","A1"),("draw","рисовать","verb","A1"),
    ("dream","мечта","noun","A1"),("dress","платье","noun","A1"),("drink","пить","verb","A1"),
    ("drive","водить","verb","A1"),("drop","ронять","verb","A1"),("dry","сухой","adj","A1"),
    ("during","в течение","prep","A1"),("dust","пыль","noun","A1"),("duty","обязанность","noun","A1"),
    ("each","каждый","det","A1"),("ear","ухо","noun","A1"),("early","рано","adv","A1"),
    ("earn","зарабатывать","verb","A1"),("earth","земля","noun","A1"),("east","восток","noun","A1"),
    ("easy","лёгкий","adj","A1"),("eat","есть","verb","A1"),("edge","край","noun","A1"),
    ("education","образование","noun","A1"),("effect","эффект","noun","A1"),("effort","усилие","noun","A1"),
    ("either","любой","pron","A1"),("electric","электрический","adj","A1"),("element","элемент","noun","A1"),
    ("else","ещё","adv","A1"),("empty","пустой","adj","A1"),("end","конец","noun","A1"),
    ("enemy","враг","noun","A1"),("energy","энергия","noun","A1"),("engine","двигатель","noun","A1"),
    ("enjoy","наслаждаться","verb","A1"),("enough","достаточно","det","A1"),("enter","входить","verb","A1"),
    ("entire","целый","adj","A1"),("equal","равный","adj","A1"),("error","ошибка","noun","A1"),
    ("escape","бежать","verb","A1"),("even","даже","adv","A1"),("evening","вечер","noun","A1"),
    ("event","событие","noun","A1"),("ever","когда-либо","adv","A1"),("every","каждый","det","A1"),
    ("everyone","все","pron","A1"),("everything","всё","pron","A1"),("everywhere","везде","adv","A1"),
    ("exact","точный","adj","A1"),("examine","осматривать","verb","A1"),("example","пример","noun","A1"),
    ("excellent","отличный","adj","A1"),("except","кроме","prep","A1"),("exchange","обмен","noun","A1"),
    ("excited","взволнованный","adj","A1"),("excuse","извинение","noun","A1"),("exercise","упражнение","noun","A1"),
    ("exist","существовать","verb","A1"),("expect","ожидать","verb","A1"),("expensive","дорогой","adj","A1"),
    ("experience","опыт","noun","A1"),("experiment","эксперимент","noun","A1"),("explain","объяснять","verb","A1"),
    ("express","выражать","verb","A1"),("extra","дополнительный","adj","A1"),("eye","глаз","noun","A1"),
    ("face","лицо","noun","A1"),("fact","факт","noun","A1"),("fail","проваливать","verb","A1"),
    ("fair","честный","adj","A1"),("fall","падать","verb","A1"),("family","семья","noun","A1"),
    ("famous","знаменитый","adj","A1"),("far","далеко","adv","A1"),("farm","ферма","noun","A1"),
    ("fast","быстрый","adj","A1"),("father","отец","noun","A1"),("fear","страх","noun","A1"),
    ("feed","кормить","verb","A1"),("feel","чувствовать","verb","A1"),("few","несколько","det","A1"),
    ("field","поле","noun","A1"),("fight","драться","verb","A1"),("fill","наполнять","verb","A1"),
    ("film","фильм","noun","A1"),("final","финальный","adj","A1"),("find","находить","verb","A1"),
    ("fine","хороший","adj","A1"),("finger","палец","noun","A1"),("finish","заканчивать","verb","A1"),
    ("fire","огонь","noun","A1"),("first","первый","adj","A1"),("fish","рыба","noun","A1"),
    ("fit","подходить","verb","A1"),("fix","чинить","verb","A1"),("flag","флаг","noun","A1"),
    ("flat","квартира","noun","A1"),("flight","полёт","noun","A1"),("floor","пол","noun","A1"),
    ("flower","цветок","noun","A1"),("fly","летать","verb","A1"),("focus","фокус","noun","A1"),
    ("follow","следовать","verb","A1"),("food","еда","noun","A1"),("fool","дурак","noun","A1"),
    ("foot","нога","noun","A1"),("for","для","prep","A1"),("force","сила","noun","A1"),
    ("foreign","иностранный","adj","A1"),("forest","лес","noun","A1"),("forever","навсегда","adv","A1"),
    ("forget","забывать","verb","A1"),("form","форма","noun","A1"),("former","бывший","adj","A1"),
    ("forth","вперёд","adv","A1"),("fortune","удача","noun","A1"),("forward","вперёд","adv","A1"),
    ("free","свободный","adj","A1"),("fresh","свежий","adj","A1"),("friend","друг","noun","A1"),
    ("frighten","пугать","verb","A1"),("from","от","prep","A1"),("front","передний","noun","A1"),
    ("fruit","фрукт","noun","A1"),("full","полный","adj","A1"),("fun","веселье","noun","A1"),
    ("future","будущее","noun","A1"),("game","игра","noun","A1"),("garden","сад","noun","A1"),
    ("gas","газ","noun","A1"),("gate","ворота","noun","A1"),("gather","собирать","verb","A1"),
    ("general","общий","adj","A1"),("get","получать","verb","A1"),("gift","подарок","noun","A1"),
    ("girl","девочка","noun","A1"),("give","давать","verb","A1"),("glad","рад","adj","A1"),
    ("glass","стекло","noun","A1"),("glove","перчатка","noun","A1"),("go","идти","verb","A1"),
    ("goal","цель","noun","A1"),("god","бог","noun","A1"),("gold","золото","noun","A1"),
    ("golden","золотой","adj","A1"),("good","хороший","adj","A1"),("government","правительство","noun","A1"),
    ("grass","трава","noun","A1"),("great","отличный","adj","A1"),("green","зелёный","adj","A1"),
    ("ground","земля","noun","A1"),("group","группа","noun","A1"),("grow","расти","verb","A1"),
    ("guess","угадывать","verb","A1"),("guest","гость","noun","A1"),("guide","гид","noun","A1"),
    ("guilty","виновный","adj","A1"),("gun","пистолет","noun","A1"),("hair","волосы","noun","A1"),
    ("half","половина","noun","A1"),("hall","зал","noun","A1"),("hand","рука","noun","A1"),
    ("handle","ручка","noun","A1"),("hang","висеть","verb","A1"),("happen","случаться","verb","A1"),
    ("happy","счастливый","adj","A1"),("hard","твёрдый","adj","A1"),("hat","шляпа","noun","A1"),
    ("hate","ненавидеть","verb","A1"),("have","иметь","verb","A1"),("he","он","pron","A1"),
    ("head","голова","noun","A1"),("health","здоровье","noun","A1"),("hear","слышать","verb","A1"),
    ("heart","сердце","noun","A1"),("heat","жара","noun","A1"),("heaven","небо","noun","A1"),
    ("heavy","тяжёлый","adj","A1"),("height","высота","noun","A1"),("hello","привет","intj","A1"),
    ("help","помогать","verb","A1"),("here","здесь","adv","A1"),("hide","прятать","verb","A1"),
    ("high","высокий","adj","A1"),("hill","холм","noun","A1"),("him","ему","pron","A1"),
    ("hire","нанимать","verb","A1"),("history","история","noun","A1"),("hit","бить","verb","A1"),
    ("hold","держать","verb","A1"),("hole","дыра","noun","A1"),("holiday","отпуск","noun","A1"),
    ("home","дом","noun","A1"),("honest","честный","adj","A1"),("honey","мёд","noun","A1"),
    ("hope","надеяться","verb","A1"),("horse","лошадь","noun","A1"),("hospital","больница","noun","A1"),
    ("hot","горячий","adj","A1"),("hotel","отель","noun","A1"),("hour","час","noun","A1"),
    ("house","дом","noun","A1"),("how","как","adv","A1"),("however","однако","adv","A1"),
    ("human","человек","adj","A1"),("hundred","сотня","num","A1"),("hungry","голодный","adj","A1"),
    ("hunt","охотиться","verb","A1"),("hurry","спешить","verb","A1"),("hurt","болеть","verb","A1"),
    ("husband","муж","noun","A1"),("ice","лёд","noun","A1"),("idea","идея","noun","A1"),
    ("identify","опознавать","verb","A1"),("if","если","conj","A1"),("ill","больной","adj","A1"),
    ("imagine","представлять","verb","A1"),("immediate","немедленный","adj","A1"),("import","импортировать","verb","A1"),
    ("important","важный","adj","A1"),("improve","улучшать","verb","A1"),("in","в","prep","A1"),
    ("include","включать","verb","A1"),("income","доход","noun","A1"),("increase","увеличивать","verb","A1"),
    ("indeed","действительно","adv","A1"),("independent","независимый","adj","A1"),("industry","промышленность","noun","A1"),
    ("information","информация","noun","A1"),("inside","внутри","prep","A1"),("insist","настаивать","verb","A1"),
    ("instead","вместо","adv","A1"),("instruction","инструкция","noun","A1"),("instrument","инструмент","noun","A1"),
    ("insurance","страховка","noun","A1"),("intend","намереваться","verb","A1"),("interest","интерес","noun","A1"),
    ("internet","интернет","noun","A1"),("interview","интервью","noun","A1"),("into","в","prep","A1"),
    ("introduce","представлять","verb","A1"),("invest","инвестировать","verb","A1"),("invite","приглашать","verb","A1"),
    ("involve","вовлекать","verb","A1"),("iron","железо","noun","A1"),("island","остров","noun","A1"),
    ("issue","проблема","noun","A1"),("it","это","pron","A1"),("item","предмет","noun","A1"),
    ("jacket","куртка","noun","A1"),("jail","тюрьма","noun","A1"),("job","работа","noun","A1"),
    ("join","присоединяться","verb","A1"),("joint","совместный","adj","A1"),("joke","шутка","noun","A1"),
    ("journey","поездка","noun","A1"),("joy","радость","noun","A1"),("judge","судья","noun","A1"),
    ("juice","сок","noun","A1"),("jump","прыгать","verb","A1"),("just","только","adv","A1"),
    ("keep","держать","verb","A1"),("key","ключ","noun","A1"),("kick","пинать","verb","A1"),
    ("kid","ребёнок","noun","A1"),("kill","убивать","verb","A1"),("kind","добрый","adj","A1"),
    ("king","король","noun","A1"),("kiss","целовать","verb","A1"),("kitchen","кухня","noun","A1"),
    ("knee","колено","noun","A1"),("knife","нож","noun","A1"),("knock","стучать","verb","A1"),
    ("know","знать","verb","A1"),("knowledge","знание","noun","A1"),("lady","дама","noun","A1"),
    ("lake","озеро","noun","A1"),("land","земля","noun","A1"),("language","язык","noun","A1"),
    ("large","большой","adj","A1"),("last","последний","adj","A1"),("late","поздно","adv","A1"),
    ("later","позже","adv","A1"),("laugh","смеяться","verb","A1"),("law","закон","noun","A1"),
    ("lawyer","юрист","noun","A1"),("lay","класть","verb","A1"),("lazy","ленивый","adj","A1"),
    ("lead","вести","verb","A1"),("leaf","лист","noun","A1"),("lean","наклоняться","verb","A1"),
    ("learn","учить","verb","A1"),("least","меньше всего","adv","A1"),("leave","уходить","verb","A1"),
    ("left","левый","adj","A1"),("leg","нога","noun","A1"),("legal","законный","adj","A1"),
    ("lemon","лимон","noun","A1"),("lend","одалживать","verb","A1"),("less","меньше","adv","A1"),
    ("lesson","урок","noun","A1"),("let","позволять","verb","A1"),("letter","буква","noun","A1"),
    ("level","уровень","noun","A1"),("library","библиотека","noun","A1"),("lie","лежать","verb","A1"),
    ("life","жизнь","noun","A1"),("light","свет","noun","A1"),("like","нравиться","verb","A1"),
    ("line","линия","noun","A1"),("link","ссылка","noun","A1"),("lion","лев","noun","A1"),
    ("lip","губа","noun","A1"),("list","список","noun","A1"),("listen","слушать","verb","A1"),
    ("little","маленький","adj","A1"),("live","жить","verb","A1"),("local","местный","adj","A1"),
    ("lock","замок","noun","A1"),("long","длинный","adj","A1"),("look","смотреть","verb","A1"),
    ("loose","свободный","adj","A1"),("lose","терять","verb","A1"),("lot","много","noun","A1"),
    ("loud","громкий","adj","A1"),("love","любить","verb","A1"),("low","низкий","adj","A1"),
    ("luck","удача","noun","A1"),("lunch","обед","noun","A1"),("machine","машина","noun","A1"),
    ("mad","злой","adj","A1"),("magazine","журнал","noun","A1"),("mail","почта","noun","A1"),
    ("main","главный","adj","A1"),("major","основной","adj","A1"),("make","делать","verb","A1"),
    ("male","мужской","adj","A1"),("man","мужчина","noun","A1"),("manage","управлять","verb","A1"),
    ("many","много","det","A1"),("map","карта","noun","A1"),("mark","отметка","noun","A1"),
    ("market","рынок","noun","A1"),("marry","жениться","verb","A1"),("match","матч","noun","A1"),
    ("math","математика","noun","A1"),("matter","дело","noun","A1"),("may","мочь","verb","A1"),
    ("maybe","может быть","adv","A1"),("me","мне","pron","A1"),("meal","еда","noun","A1"),
    ("mean","значить","verb","A1"),("meat","мясо","noun","A1"),("medical","медицинский","adj","A1"),
    ("meet","встречать","verb","A1"),("member","член","noun","A1"),("memory","память","noun","A1"),
    ("mention","упоминать","verb","A1"),("message","сообщение","noun","A1"),("method","метод","noun","A1"),
    ("middle","середина","noun","A1"),("might","мог бы","verb","A1"),("mile","миля","noun","A1"),
    ("milk","молоко","noun","A1"),("mind","разум","noun","A1"),("mine","мой","pron","A1"),
    ("minute","минута","noun","A1"),("mirror","зеркало","noun","A1"),("miss","пропускать","verb","A1"),
    ("mistake","ошибка","noun","A1"),("mix","смешивать","verb","A1"),("model","модель","noun","A1"),
    ("modern","современный","adj","A1"),("moment","момент","noun","A1"),("money","деньги","noun","A1"),
    ("month","месяц","noun","A1"),("moon","луна","noun","A1"),("more","больше","adv","A1"),
    ("morning","утро","noun","A1"),("most","большинство","adv","A1"),("mother","мать","noun","A1"),
    ("motor","мотор","noun","A1"),("mountain","гора","noun","A1"),("mouse","мышь","noun","A1"),
    ("mouth","рот","noun","A1"),("move","двигать","verb","A1"),("much","много","det","A1"),
    ("music","музыка","noun","A1"),("must","должен","verb","A1"),("my","мой","pron","A1"),
    ("name","имя","noun","A1"),("narrow","узкий","adj","A1"),("nation","нация","noun","A1"),
    ("natural","естественный","adj","A1"),("nature","природа","noun","A1"),("near","близко","adv","A1"),
    ("necessary","необходимый","adj","A1"),("need","нуждаться","verb","A1"),("never","никогда","adv","A1"),
    ("new","новый","adj","A1"),("news","новости","noun","A1"),("next","следующий","adj","A1"),
    ("nice","приятный","adj","A1"),("night","ночь","noun","A1"),("nine","девять","num","A1"),
    ("no","нет","adv","A1"),("noise","шум","noun","A1"),("none","никто","pron","A1"),
    ("noon","полдень","noun","A1"),("normal","нормальный","adj","A1"),("north","север","noun","A1"),
    ("nose","нос","noun","A1"),("not","не","adv","A1"),("note","заметка","noun","A1"),
    ("nothing","ничего","pron","A1"),("notice","замечать","verb","A1"),("now","сейчас","adv","A1"),
    ("number","число","noun","A1"),("object","предмет","noun","A1"),("obtain","получать","verb","A1"),
    ("obvious","очевидный","adj","A1"),("occur","происходить","verb","A1"),("ocean","океан","noun","A1"),
    ("of","принадлежность","prep","A1"),("off","выключено","adv","A1"),("offer","предлагать","verb","A1"),
    ("office","офис","noun","A1"),("officer","офицер","noun","A1"),("often","часто","adv","A1"),
    ("oh","о","intj","A1"),("oil","масло","noun","A1"),("old","старый","adj","A1"),
    ("on","на","prep","A1"),("once","однажды","adv","A1"),("one","один","num","A1"),
    ("only","только","adv","A1"),("open","открывать","verb","A1"),("operate","работать","verb","A1"),
    ("opinion","мнение","noun","A1"),("opportunity","возможность","noun","A1"),("opposite","противоположный","adj","A1"),
    ("or","или","conj","A1"),("order","заказ","noun","A1"),("organize","организовывать","verb","A1"),
    ("original","оригинальный","adj","A1"),("other","другой","adj","A1"),("our","наш","pron","A1"),
    ("out","вне","adv","A1"),("outside","снаружи","prep","A1"),("over","над","prep","A1"),
    ("own","собственный","adj","A1"),("page","страница","noun","A1"),("pain","боль","noun","A1"),
    ("paint","красить","verb","A1"),("pair","пара","noun","A1"),("paper","бумага","noun","A1"),
    ("parent","родитель","noun","A1"),("park","парк","noun","A1"),("part","часть","noun","A1"),
    ("particular","особый","adj","A1"),("partner","партнёр","noun","A1"),("party","вечеринка","noun","A1"),
    ("pass","проходить","verb","A1"),("past","прошлое","noun","A1"),("path","путь","noun","A1"),
    ("pay","платить","verb","A1"),("peace","мир","noun","A1"),("people","люди","noun","A1"),
    ("perfect","идеальный","adj","A1"),("perhaps","возможно","adv","A1"),("period","период","noun","A1"),
    ("person","человек","noun","A1"),("phone","телефон","noun","A1"),("photo","фото","noun","A1"),
    ("pick","выбирать","verb","A1"),("picture","картинка","noun","A1"),("piece","кусок","noun","A1"),
    ("place","место","noun","A1"),("plan","план","noun","A1"),("plane","самолёт","noun","A1"),
    ("plant","растение","noun","A1"),("plastic","пластик","noun","A1"),("plate","тарелка","noun","A1"),
    ("play","играть","verb","A1"),("please","пожалуйста","intj","A1"),("pleasure","удовольствие","noun","A1"),
    ("point","точка","noun","A1"),("poison","яд","noun","A1"),("police","полиция","noun","A1"),
    ("pool","бассейн","noun","A1"),("poor","бедный","adj","A1"),("popular","популярный","adj","A1"),
    ("position","позиция","noun","A1"),("possible","возможный","adj","A1"),("post","почта","noun","A1"),
    ("pot","горшок","noun","A1"),("pound","фунт","noun","A1"),("pour","лить","verb","A1"),
    ("power","сила","noun","A1"),("practical","практичный","adj","A1"),("practice","практика","noun","A1"),
    ("prepare","готовить","verb","A1"),("present","подарок","noun","A1"),("press","нажимать","verb","A1"),
    ("pretty","симпатичный","adj","A1"),("prevent","предотвращать","verb","A1"),("price","цена","noun","A1"),
    ("prince","принц","noun","A1"),("print","печать","verb","A1"),("prison","тюрьма","noun","A1"),
    ("private","частный","adj","A1"),("prize","приз","noun","A1"),("probably","вероятно","adv","A1"),
    ("problem","проблема","noun","A1"),("produce","производить","verb","A1"),("program","программа","noun","A1"),
    ("project","проект","noun","A1"),("promise","обещание","noun","A1"),("proof","доказательство","noun","A1"),
    ("proper","надлежащий","adj","A1"),("protect","защищать","verb","A1"),("proud","гордый","adj","A1"),
    ("prove","доказывать","verb","A1"),("provide","обеспечивать","verb","A1"),("public","общественный","adj","A1"),
    ("pull","тянуть","verb","A1"),("punish","наказывать","verb","A1"),("pupil","ученик","noun","A1"),
    ("pure","чистый","adj","A1"),("purpose","цель","noun","A1"),("push","толкать","verb","A1"),
    ("put","класть","verb","A1"),("quality","качество","noun","A1"),("question","вопрос","noun","A1"),
    ("quick","быстрый","adj","A1"),("quiet","тихий","adj","A1"),("quite","довольно","adv","A1"),
    ("race","гонка","noun","A1"),("radio","радио","noun","A1"),("rain","дождь","noun","A1"),
    ("raise","поднимать","verb","A1"),("range","диапазон","noun","A1"),("rat","крыса","noun","A1"),
    ("rate","ставка","noun","A1"),("rather","скорее","adv","A1"),("reach","достигать","verb","A1"),
    ("read","читать","verb","A1"),("ready","готовый","adj","A1"),("real","настоящий","adj","A1"),
    ("realize","осознавать","verb","A1"),("reason","причина","noun","A1"),("receive","получать","verb","A1"),
    ("recent","недавний","adj","A1"),("record","запись","noun","A1"),("red","красный","adj","A1"),
    ("reduce","уменьшать","verb","A1"),("reflect","отражать","verb","A1"),("refuse","отказывать","verb","A1"),
    ("regard","считать","verb","A1"),("region","регион","noun","A1"),("relate","относиться","verb","A1"),
    ("relax","расслабляться","verb","A1"),("remain","оставаться","verb","A1"),("remember","помнить","verb","A1"),
    ("remove","удалять","verb","A1"),("repair","чинить","verb","A1"),("repeat","повторять","verb","A1"),
    ("reply","отвечать","verb","A1"),("report","отчёт","noun","A1"),("require","требовать","verb","A1"),
    ("research","исследование","noun","A1"),("respect","уважать","verb","A1"),("rest","отдых","noun","A1"),
    ("result","результат","noun","A1"),("return","возвращать","verb","A1"),("rice","рис","noun","A1"),
    ("rich","богатый","adj","A1"),("ride","ехать","verb","A1"),("right","правый","adj","A1"),
    ("ring","кольцо","noun","A1"),("rise","подниматься","verb","A1"),("risk","риск","noun","A1"),
    ("river","река","noun","A1"),("road","дорога","noun","A1"),("rob","грабить","verb","A1"),
    ("rock","камень","noun","A1"),("role","роль","noun","A1"),("room","комната","noun","A1"),
    ("rough","грубый","adj","A1"),("round","круглый","adj","A1"),("row","ряд","noun","A1"),
    ("royal","королевский","adj","A1"),("rule","правило","noun","A1"),("run","бегать","verb","A1"),
    ("sad","грустный","adj","A1"),("safe","безопасный","adj","A1"),("sail","плыть","verb","A1"),
    ("safety","безопасность","noun","A1"),("salt","соль","noun","A1"),("same","тот же","adj","A1"),
    ("sand","песок","noun","A1"),("save","экономить","verb","A1"),("say","говорить","verb","A1"),
    ("school","школа","noun","A1"),("science","наука","noun","A1"),("score","счёт","noun","A1"),
    ("sea","море","noun","A1"),("search","искать","verb","A1"),("season","сезон","noun","A1"),
    ("seat","место","noun","A1"),("second","второй","num","A1"),("secret","секрет","noun","A1"),
    ("section","секция","noun","A1"),("see","видеть","verb","A1"),("seem","казаться","verb","A1"),
    ("select","выбирать","verb","A1"),("sell","продавать","verb","A1"),("send","отправлять","verb","A1"),
    ("sense","чувство","noun","A1"),("series","серия","noun","A1"),("serious","серьёзный","adj","A1"),
    ("serve","служить","verb","A1"),("set","набор","noun","A1"),("settle","селиться","verb","A1"),
    ("seven","семь","num","A1"),("several","несколько","det","A1"),("shake","трясти","verb","A1"),
    ("shall","будем","verb","A1"),("shame","стыд","noun","A1"),("shape","форма","noun","A1"),
    ("share","делиться","verb","A1"),("sharp","острый","adj","A1"),("she","она","pron","A1"),
    ("sheep","овца","noun","A1"),("sheet","лист","noun","A1"),("shelf","полка","noun","A1"),
    ("shine","светить","verb","A1"),("ship","корабль","noun","A1"),("shirt","рубашка","noun","A1"),
    ("shock","шок","noun","A1"),("shoe","ботинок","noun","A1"),("shoot","стрелять","verb","A1"),
    ("shop","магазин","noun","A1"),("shore","берег","noun","A1"),("short","короткий","adj","A1"),
    ("shot","выстрел","noun","A1"),("should","следует","verb","A1"),("shoulder","плечо","noun","A1"),
    ("shout","кричать","verb","A1"),("show","показывать","verb","A1"),("shut","закрывать","verb","A1"),
    ("sick","больной","adj","A1"),("side","сторона","noun","A1"),("sight","зрение","noun","A1"),
    ("sign","знак","noun","A1"),("signal","сигнал","noun","A1"),("silence","тишина","noun","A1"),
    ("silly","глупый","adj","A1"),("silver","серебро","noun","A1"),("similar","похожий","adj","A1"),
    ("simple","простой","adj","A1"),("since","с","prep","A1"),("sing","петь","verb","A1"),
    ("single","одиночный","adj","A1"),("sir","сэр","noun","A1"),("sister","сестра","noun","A1"),
    ("sit","сидеть","verb","A1"),("site","место","noun","A1"),("situation","ситуация","noun","A1"),
    ("six","шесть","num","A1"),("size","размер","noun","A1"),("skin","кожа","noun","A1"),
    ("sky","небо","noun","A1"),("sleep","спать","verb","A1"),("slow","медленный","adj","A1"),
    ("small","маленький","adj","A1"),("smell","пахнуть","verb","A1"),("smile","улыбаться","verb","A1"),
    ("smoke","дым","noun","A1"),("smooth","гладкий","adj","A1"),("snake","змея","noun","A1"),
    ("snow","снег","noun","A1"),("so","поэтому","conj","A1"),("soap","мыло","noun","A1"),
    ("social","социальный","adj","A1"),("society","общество","noun","A1"),("soft","мягкий","adj","A1"),
    ("soil","почва","noun","A1"),("soldier","солдат","noun","A1"),("solid","твёрдый","adj","A1"),
    ("solution","решение","noun","A1"),("solve","решать","verb","A1"),("some","несколько","det","A1"),
    ("son","сын","noun","A1"),("song","песня","noun","A1"),("soon","скоро","adv","A1"),
    ("sorry","сожалеющий","adj","A1"),("sort","вид","noun","A1"),("sound","звук","noun","A1"),
    ("source","источник","noun","A1"),("south","юг","noun","A1"),("space","пространство","noun","A1"),
    ("speak","говорить","verb","A1"),("special","особый","adj","A1"),("speed","скорость","noun","A1"),
    ("spell","писать по буквам","verb","A1"),("spend","тратить","verb","A1"),("spider","паук","noun","A1"),
    ("spirit","дух","noun","A1"),("sport","спорт","noun","A1"),("spot","пятно","noun","A1"),
    ("spread","распространять","verb","A1"),("spring","весна","noun","A1"),("square","площадь","noun","A1"),
    ("stable","стабильный","adj","A1"),("staff","персонал","noun","A1"),("stair","ступень","noun","A1"),
    ("stamp","марка","noun","A1"),("stand","стоять","verb","A1"),("standard","стандарт","noun","A1"),
    ("star","звезда","noun","A1"),("start","начинать","verb","A1"),("state","состояние","noun","A1"),
    ("station","станция","noun","A1"),("stay","оставаться","verb","A1"),("steal","красть","verb","A1"),
    ("steam","пар","noun","A1"),("steel","сталь","noun","A1"),("step","шаг","noun","A1"),
    ("stick","палка","noun","A1"),("still","всё ещё","adv","A1"),("stomach","живот","noun","A1"),
    ("stone","камень","noun","A1"),("stop","останавливать","verb","A1"),("store","магазин","noun","A1"),
    ("storm","буря","noun","A1"),("story","история","noun","A1"),("straight","прямо","adv","A1"),
    ("strange","странный","adj","A1"),("street","улица","noun","A1"),("strength","сила","noun","A1"),
    ("strong","сильный","adj","A1"),("struggle","бороться","verb","A1"),("student","студент","noun","A1"),
    ("study","учиться","verb","A1"),("stupid","глупый","adj","A1"),("style","стиль","noun","A1"),
    ("subject","предмет","noun","A1"),("succeed","преуспевать","verb","A1"),("success","успех","noun","A1"),
    ("such","такой","det","A1"),("sudden","внезапный","adj","A1"),("suffer","страдать","verb","A1"),
    ("sugar","сахар","noun","A1"),("suggest","предлагать","verb","A1"),("suit","костюм","noun","A1"),
    ("summer","лето","noun","A1"),("sun","солнце","noun","A1"),("super","супер","adj","A1"),
    ("supply","поставка","noun","A1"),("support","поддержка","noun","A1"),("suppose","предполагать","verb","A1"),
    ("sure","уверенный","adj","A1"),("surprise","удивление","noun","A1"),("survive","выживать","verb","A1"),
    ("swim","плавать","verb","A1"),("switch","переключатель","noun","A1"),("system","система","noun","A1"),
    ("table","стол","noun","A1"),("take","брать","verb","A1"),("talk","разговаривать","verb","A1"),
    ("tall","высокий","adj","A1"),("task","задача","noun","A1"),("taste","пробовать","verb","A1"),
    ("tax","налог","noun","A1"),("tea","чай","noun","A1"),("teach","учить","verb","A1"),
    ("teacher","учитель","noun","A1"),("team","команда","noun","A1"),("tear","слеза","noun","A1"),
    ("technology","технология","noun","A1"),("telephone","телефон","noun","A1"),("television","телевидение","noun","A1"),
    ("tell","сказать","verb","A1"),("temperature","температура","noun","A1"),("ten","десять","num","A1"),
    ("tend","иметь тенденцию","verb","A1"),("term","термин","noun","A1"),("test","тест","noun","A1"),
    ("than","чем","conj","A1"),("thank","благодарить","verb","A1"),("that","то","pron","A1"),
    ("the","артикль","art","A1"),("their","их","pron","A1"),("them","им","pron","A1"),
    ("then","затем","adv","A1"),("theory","теория","noun","A1"),("there","там","adv","A1"),
    ("these","эти","pron","A1"),("they","они","pron","A1"),("thick","толстый","adj","A1"),
    ("thin","тонкий","adj","A1"),("thing","вещь","noun","A1"),("think","думать","verb","A1"),
    ("third","третий","num","A1"),("this","это","pron","A1"),("though","хотя","conj","A1"),
    ("thought","мысль","noun","A1"),("thousand","тысяча","num","A1"),("three","три","num","A1"),
    ("throw","бросать","verb","A1"),("thus","таким образом","adv","A1"),("ticket","билет","noun","A1"),
    ("tie","галстук","noun","A1"),("tight","тугой","adj","A1"),("till","до","prep","A1"),
    ("time","время","noun","A1"),("tiny","крошечный","adj","A1"),("tired","уставший","adj","A1"),
    ("title","название","noun","A1"),("to","к","prep","A1"),("today","сегодня","adv","A1"),
    ("toe","палец ноги","noun","A1"),("together","вместе","adv","A1"),("tomorrow","завтра","adv","A1"),
    ("tone","тон","noun","A1"),("tongue","язык","noun","A1"),("tonight","сегодня вечером","adv","A1"),
    ("too","тоже","adv","A1"),("tool","инструмент","noun","A1"),("tooth","зуб","noun","A1"),
    ("top","вершина","noun","A1"),("topic","тема","noun","A1"),("total","общий","adj","A1"),
    ("touch","трогать","verb","A1"),("tough","жёсткий","adj","A1"),("tour","тур","noun","A1"),
    ("toward","к","prep","A1"),("tower","башня","noun","A1"),("town","городок","noun","A1"),
    ("trade","торговля","noun","A1"),("tradition","традиция","noun","A1"),("traffic","трафик","noun","A1"),
    ("train","поезд","noun","A1"),("travel","путешествовать","verb","A1"),("treat","лечить","verb","A1"),
    ("tree","дерево","noun","A1"),("trial","суд","noun","A1"),("trip","поездка","noun","A1"),
    ("troops","войска","noun","A1"),("trouble","проблема","noun","A1"),("truck","грузовик","noun","A1"),
    ("true","верный","adj","A1"),("trust","доверять","verb","A1"),("truth","правда","noun","A1"),
    ("try","пробовать","verb","A1"),("tube","трубка","noun","A1"),("turn","поворачивать","verb","A1"),
    ("twelve","двенадцать","num","A1"),("twenty","двадцать","num","A1"),("twice","дважды","adv","A1"),
    ("two","два","num","A1"),("type","тип","noun","A1"),("ugly","уродливый","adj","A1"),
    ("umbrella","зонт","noun","A1"),("uncle","дядя","noun","A1"),("under","под","prep","A1"),
    ("understand","понимать","verb","A1"),("unfortunately","к сожалению","adv","A1"),("union","союз","noun","A1"),
    ("unit","единица","noun","A1"),("unite","объединять","verb","A1"),("universe","вселенная","noun","A1"),
    ("university","университет","noun","A1"),("until","до","prep","A1"),("up","вверх","adv","A1"),
    ("upon","на","prep","A1"),("upper","верхний","adj","A1"),("upset","расстроенный","adj","A1"),
    ("use","использовать","verb","A1"),("useful","полезный","adj","A1"),("usual","обычный","adj","A1"),
    ("usually","обычно","adv","A1"),("value","ценность","noun","A1"),("various","различный","adj","A1"),
    ("very","очень","adv","A1"),("victim","жертва","noun","A1"),("victory","победа","noun","A1"),
    ("view","вид","noun","A1"),("village","деревня","noun","A1"),("violence","насилие","noun","A1"),
    ("visible","видимый","adj","A1"),("visit","посещать","verb","A1"),("voice","голос","noun","A1"),
    ("volume","объём","noun","A1"),("vote","голосовать","verb","A1"),("wage","зарплата","noun","A1"),
    ("wait","ждать","verb","A1"),("wake","просыпаться","verb","A1"),("walk","гулять","verb","A1"),
    ("wall","стена","noun","A1"),("war","война","noun","A1"),("warm","тёплый","adj","A1"),
    ("warn","предупреждать","verb","A1"),("wash","мыть","verb","A1"),("waste","тратить впустую","verb","A1"),
    ("watch","смотреть","verb","A1"),("water","вода","noun","A1"),("wave","волна","noun","A1"),
    ("way","путь","noun","A1"),("we","мы","pron","A1"),("weak","слабый","adj","A1"),
    ("weapon","оружие","noun","A1"),("wear","носить","verb","A1"),("weather","погода","noun","A1"),
    ("web","сеть","noun","A1"),("week","неделя","noun","A1"),("weigh","весить","verb","A1"),
    ("weight","вес","noun","A1"),("welcome","добро пожаловать","intj","A1"),("well","хорошо","adv","A1"),
    ("west","запад","noun","A1"),("wet","мокрый","adj","A1"),("what","что","pron","A1"),
    ("wheat","пшеница","noun","A1"),("wheel","колесо","noun","A1"),("when","когда","adv","A1"),
    ("where","где","adv","A1"),("whether","ли","conj","A1"),("which","который","pron","A1"),
    ("while","в то время как","conj","A1"),("white","белый","adj","A1"),("who","кто","pron","A1"),
    ("whole","целый","adj","A1"),("whose","чей","pron","A1"),("why","почему","adv","A1"),
    ("wide","широкий","adj","A1"),("wife","жена","noun","A1"),("wild","дикий","adj","A1"),
    ("will","будет","verb","A1"),("win","выигрывать","verb","A1"),("wind","ветер","noun","A1"),
    ("window","окно","noun","A1"),("wine","вино","noun","A1"),("wing","крыло","noun","A1"),
    ("winner","победитель","noun","A1"),("winter","зима","noun","A1"),("wire","провод","noun","A1"),
    ("wise","мудрый","adj","A1"),("wish","желать","verb","A1"),("with","с","prep","A1"),
    ("without","без","prep","A1"),("woman","женщина","noun","A1"),("wonder","удивляться","verb","A1"),
    ("wood","дерево","noun","A1"),("wool","шерсть","noun","A1"),("word","слово","noun","A1"),
    ("work","работать","verb","A1"),("worker","работник","noun","A1"),("world","мир","noun","A1"),
    ("worry","беспокоиться","verb","A1"),("worse","хуже","adj","A1"),("worst","худший","adj","A1"),
    ("worth","стоящий","adj","A1"),("would","бы","verb","A1"),("wound","рана","noun","A1"),
    ("write","писать","verb","A1"),("wrong","неправильный","adj","A1"),("yard","двор","noun","A1"),
    ("year","год","noun","A1"),("yellow","жёлтый","adj","A1"),("yes","да","adv","A1"),
    ("yesterday","вчера","adv","A1"),("yet","ещё","adv","A1"),("you","ты","pron","A1"),
    ("young","молодой","adj","A1"),("your","твой","pron","A1"),("zero","ноль","num","A1"),
    ("zone","зона","noun","A1"),("zoo","зоопарк","noun","A1"),
]


def _gen_example(word: str, pos: str) -> str:
    """Generate a simple example sentence for a word."""
    w = word.lower()
    if pos == "verb":
        return f"I {w} every day."
    elif pos == "noun":
        return f"The {w} is important."
    elif pos == "adj":
        return f"It is very {w}."
    elif pos == "adv":
        return f"She speaks {w}."
    elif pos == "prep":
        return f"Look {w} the book."
    elif pos == "pron":
        return f"{word.capitalize()} is here."
    elif pos == "conj":
        return f"I like tea {w} coffee."
    elif pos == "num":
        return f"I have {w} books."
    else:
        return f"This is {w}."


def get_frequency_words() -> list[tuple]:
    """Return list of (word, translation, pos, example, cefr) tuples."""
    result = []
    for word, trans, pos, cefr in _W:
        example = _gen_example(word, pos)
        result.append((word, trans, pos, example, cefr))
    return result


# For populate_db.py compatibility
FREQUENCY_WORDS = get_frequency_words()
