"""Frequency words part 2 — A2 words (~500).

Compact format: (word, translation, pos, cefr)
"""

_W2 = [
    ("achieve","достигать","verb","A2"),("actual","фактический","adj","A2"),("adapt","адаптироваться","verb","A2"),
    ("admire","восхищаться","verb","A2"),("admit","признавать","verb","A2"),("adopt","принимать","verb","A2"),
    ("advantage","преимущество","noun","A2"),("adventure","приключение","noun","A2"),("advertise","рекламировать","verb","A2"),
    ("affect","влиять","verb","A2"),("afford","позволить себе","verb","A2"),("agent","агент","noun","A2"),
    ("agriculture","сельское хозяйство","noun","A2"),("ahead","вперёд","adv","A2"),("aid","помощь","noun","A2"),
    ("aim","цель","noun","A2"),("airline","авиалиния","noun","A2"),("alarm","будильник","noun","A2"),
    ("album","альбом","noun","A2"),("alcohol","алкоголь","noun","A2"),("alike","похожий","adj","A2"),
    ("alley","переулок","noun","A2"),("allow","разрешать","verb","A2"),("ally","союзник","noun","A2"),
    ("alphabet","алфавит","noun","A2"),("amazing","удивительный","adj","A2"),("ambition","амбициозность","noun","A2"),
    ("amuse","развлекать","verb","A2"),("ancient","древний","adj","A2"),("angel","ангел","noun","A2"),
    ("anger","гнев","noun","A2"),("angle","угол","noun","A2"),("announce","объявлять","verb","A2"),
    ("annoy","раздражать","verb","A2"),("annual","ежегодный","adj","A2"),("anxious","тревожный","adj","A2"),
    ("anybody","кто-нибудь","pron","A2"),("apart","отдельно","adv","A2"),("apartment","квартира","noun","A2"),
    ("appeal","обращение","noun","A2"),("appear","появляться","verb","A2"),("appetite","аппетит","noun","A2"),
    ("appliance","прибор","noun","A2"),("apply","подавать заявку","verb","A2"),("appoint","назначать","verb","A2"),
    ("approach","подход","noun","A2"),("appropriate","уместный","adj","A2"),("approve","одобрять","verb","A2"),
    ("approximate","приблизительный","adj","A2"),("arch","арка","noun","A2"),("argue","спорить","verb","A2"),
    ("arise","возникать","verb","A2"),("arrange","организовывать","verb","A2"),("arrest","арестовывать","verb","A2"),
    ("arrival","прибытие","noun","A2"),("arrow","стрела","noun","A2"),("article","статья","noun","A2"),
    ("artificial","искусственный","adj","A2"),("ash","пепел","noun","A2"),("aspect","аспект","noun","A2"),
    ("assess","оценивать","verb","A2"),("assign","назначать","verb","A2"),("assist","помогать","verb","A2"),
    ("assume","предполагать","verb","A2"),("assure","заверять","verb","A2"),("athlete","атлет","noun","A2"),
    ("atmosphere","атмосфера","noun","A2"),("attach","прикреплять","verb","A2"),("attain","достигать","verb","A2"),
    ("attend","посещать","verb","A2"),("attic","чердак","noun","A2"),("attitude","отношение","noun","A2"),
    ("attract","привлекать","verb","A2"),("auction","аукцион","noun","A2"),("audience","аудитория","noun","A2"),
    ("author","автор","noun","A2"),("authority","власть","noun","A2"),("automatic","автоматический","adj","A2"),
    ("avenue","проспект","noun","A2"),("average","средний","adj","A2"),("avoid","избегать","verb","A2"),
    ("award","награда","noun","A2"),("aware","осведомлённый","adj","A2"),("awful","ужасный","adj","A2"),
    ("awkward","неловкий","adj","A2"),("background","фон","noun","A2"),("bacon","бекон","noun","A2"),
    ("baggage","багаж","noun","A2"),("balance","баланс","noun","A2"),("balcony","балкон","noun","A2"),
    ("ballot","бюллетень","noun","A2"),("ban","запрещать","verb","A2"),("bandage","повязка","noun","A2"),
    ("bang","удар","noun","A2"),("banner","баннер","noun","A2"),("barber","парикмахер","noun","A2"),
    ("bare","голый","adj","A2"),("bargain","сделка","noun","A2"),("barn","сарай","noun","A2"),
    ("barrier","барьер","noun","A2"),("baseball","бейсбол","noun","A2"),("basement","подвал","noun","A2"),
    ("basis","основа","noun","A2"),("batch","партия","noun","A2"),("battery","батарея","noun","A2"),
    ("battle","битва","noun","A2"),("bay","бухта","noun","A2"),("bead","бусина","noun","A2"),
    ("beak","клюв","noun","A2"),("beam","балка","noun","A2"),("bean","боб","noun","A2"),
    ("beard","борода","noun","A2"),("beast","зверь","noun","A2"),("bedroom","спальня","noun","A2"),
    ("beef","говядина","noun","A2"),("beer","пиво","noun","A2"),("behave","вести себя","verb","A2"),
    ("behavior","поведение","noun","A2"),("belief","вера","noun","A2"),("belong","принадлежать","verb","A2"),
    ("belt","ремень","noun","A2"),("bench","скамейка","noun","A2"),("bend","гнуть","verb","A2"),
    ("beneath","под","prep","A2"),("benefit","польза","noun","A2"),("berry","ягода","noun","A2"),
    ("bet","ставка","noun","A2"),("beyond","за пределами","prep","A2"),("bible","библия","noun","A2"),
    ("biology","биология","noun","A2"),("bishop","епископ","noun","A2"),("bite","кусать","verb","A2"),
    ("blame","винить","verb","A2"),("blank","пустой","adj","A2"),("blast","взрыв","noun","A2"),
    ("blend","смешивать","verb","A2"),("bless","благословлять","verb","A2"),("blind","слепой","adj","A2"),
    ("block","блок","noun","A2"),("blonde","блондинка","adj","A2"),("bloom","цвести","verb","A2"),
    ("boast","хвастаться","verb","A2"),("bold","смелый","adj","A2"),("bolt","болт","noun","A2"),
    ("bomb","бомба","noun","A2"),("bond","связь","noun","A2"),("bonus","бонус","noun","A2"),
    ("bookcase","книжный шкаф","noun","A2"),("bookmark","закладка","noun","A2"),("boot","ботинок","noun","A2"),
    ("bother","беспокоить","verb","A2"),("bounce","отскакивать","verb","A2"),("boundary","граница","noun","A2"),
    ("bow","лук","noun","A2"),("boycott","бойкот","verb","A2"),("brake","тормоз","noun","A2"),
    ("brand","бренд","noun","A2"),("brass","латунь","noun","A2"),("breakdown","поломка","noun","A2"),
    ("breath","дыхание","noun","A2"),("breed","порода","noun","A2"),("bride","невеста","noun","A2"),
    ("brilliant","блестящий","adj","A2"),("broadcast","трансляция","noun","A2"),("broker","брокер","noun","A2"),
    ("broom","метла","noun","A2"),("bubble","пузырь","noun","A2"),("bucket","ведро","noun","A2"),
    ("budget","бюджет","noun","A2"),("buffet","буфет","noun","A2"),("bug","жук","noun","A2"),
    ("bulb","лампочка","noun","A2"),("bulk","масса","noun","A2"),("bullet","пуля","noun","A2"),
    ("bunch","пучок","noun","A2"),("bundle","связка","noun","A2"),("burden","бремя","noun","A2"),
    ("bureau","бюро","noun","A2"),("burger","бургер","noun","A2"),("burst","лопаться","verb","A2"),
    ("bury","хоронить","verb","A2"),("bush","куст","noun","A2"),("cabin","каюта","noun","A2"),
    ("cabinet","шкаф","noun","A2"),("cable","кабель","noun","A2"),("cafe","кафе","noun","A2"),
    ("cafeteria","столовая","noun","A2"),("cage","клетка","noun","A2"),("calculate","вычислять","verb","A2"),
    ("calendar","календарь","noun","A2"),("campaign","кампания","noun","A2"),("campus","кампус","noun","A2"),
    ("canal","канал","noun","A2"),("cancel","отменять","verb","A2"),("candidate","кандидат","noun","A2"),
    ("candy","конфета","noun","A2"),("canvas","холст","noun","A2"),("capable","способный","adj","A2"),
    ("capacity","вместимость","noun","A2"),("capital","столица","noun","A2"),("captain","капитан","noun","A2"),
    ("capture","захватывать","verb","A2"),("carbon","углерод","noun","A2"),("career","карьера","noun","A2"),
    ("careless","небрежный","adj","A2"),("cargo","груз","noun","A2"),("carpenter","плотник","noun","A2"),
    ("carpet","ковёр","noun","A2"),("carriage","карета","noun","A2"),("carrier","перевозчик","noun","A2"),
    ("cart","тележка","noun","A2"),("cartoon","мультфильм","noun","A2"),("cashier","кассир","noun","A2"),
    ("cassette","кассета","noun","A2"),("cast","бросать","verb","A2"),("catalog","каталог","noun","A2"),
    ("category","категория","noun","A2"),("cattle","скот","noun","A2"),("cautious","осторожный","adj","A2"),
    ("cave","пещера","noun","A2"),("cease","прекращать","verb","A2"),("cement","цемент","noun","A2"),
    ("ceremony","церемония","noun","A2"),("certificate","сертификат","noun","A2"),("chain","цепь","noun","A2"),
    ("chairman","председатель","noun","A2"),("challenge","вызов","noun","A2"),("chamber","комната","noun","A2"),
    ("champion","чемпион","noun","A2"),("chancellor","канцлер","noun","A2"),("chaos","хаос","noun","A2"),
    ("chapter","глава","noun","A2"),("charity","благотворительность","noun","A2"),("charm","очарование","noun","A2"),
    ("chart","график","noun","A2"),("chase","преследовать","verb","A2"),("cheat","обманывать","verb","A2"),
    ("chef","шеф-повар","noun","A2"),("chess","шахматы","noun","A2"),("chest","грудь","noun","A2"),
    ("chew","жевать","verb","A2"),("childhood","детство","noun","A2"),("chimney","труба","noun","A2"),
    ("chip","чип","noun","A2"),("chocolate","шоколад","noun","A2"),("choice","выбор","noun","A2"),
    ("circuit","цепь","noun","A2"),("circumstance","обстоятельство","noun","A2"),("citizen","гражданин","noun","A2"),
    ("citizenship","гражданство","noun","A2"),("civil","гражданский","adj","A2"),("civilian","гражданский","noun","A2"),
    ("claim","утверждать","verb","A2"),("clarify","уточнять","verb","A2"),("classic","классический","adj","A2"),
    ("clay","глина","noun","A2"),("client","клиент","noun","A2"),("cliff","утёс","noun","A2"),
    ("climate","климат","noun","A2"),("clinic","клиника","noun","A2"),("clip","скрепка","noun","A2"),
    ("cloak","плащ","noun","A2"),("clockwise","по часовой","adv","A2"),("closet","шкаф","noun","A2"),
    ("clue","подсказка","noun","A2"),("cluster","группа","noun","A2"),("coach","тренер","noun","A2"),
    ("code","код","noun","A2"),("coil","катушка","noun","A2"),("collapse","обрушиваться","verb","A2"),
    ("collar","воротник","noun","A2"),("colleague","коллега","noun","A2"),("collect","собирать","verb","A2"),
    ("collision","столкновение","noun","A2"),("colony","колония","noun","A2"),("column","колонна","noun","A2"),
    ("combat","бой","noun","A2"),("combination","сочетание","noun","A2"),("comedy","комедия","noun","A2"),
    ("comfort","комфорт","noun","A2"),("command","команда","noun","A2"),("comment","комментарий","noun","A2"),
    ("commission","комиссия","noun","A2"),("committee","комитет","noun","A2"),("communicate","общаться","verb","A2"),
    ("community","сообщество","noun","A2"),("companion","спутник","noun","A2"),("compare","сравнивать","verb","A2"),
    ("compete","соревноваться","verb","A2"),("complain","жаловаться","verb","A2"),("complete","завершать","verb","A2"),
    ("complex","сложный","adj","A2"),("component","компонент","noun","A2"),("compose","составлять","verb","A2"),
    ("composition","сочинение","noun","A2"),("compound","соединение","noun","A2"),("concept","концепция","noun","A2"),
    ("concern","беспокойство","noun","A2"),("conclude","заключать","verb","A2"),("concrete","бетон","noun","A2"),
    ("conduct","проводить","verb","A2"),("conference","конференция","noun","A2"),("confidence","уверенность","noun","A2"),
    ("confirm","подтверждать","verb","A2"),("conflict","конфликт","noun","A2"),("confront","противостоять","verb","A2"),
    ("congress","конгресс","noun","A2"),("connect","соединять","verb","A2"),("conquer","завоёвывать","verb","A2"),
    ("consent","согласие","noun","A2"),("consequence","последствие","noun","A2"),("conservative","консервативный","adj","A2"),
    ("consider","рассматривать","verb","A2"),("consist","состоять из","verb","A2"),("constant","постоянный","adj","A2"),
    ("constitute","составлять","verb","A2"),("construct","строить","verb","A2"),("consult","консультироваться","verb","A2"),
    ("consume","потреблять","verb","A2"),("contact","контакт","noun","A2"),("container","контейнер","noun","A2"),
    ("contemporary","современный","adj","A2"),("content","содержание","noun","A2"),("contest","конкурс","noun","A2"),
    ("context","контекст","noun","A2"),("continent","континент","noun","A2"),("continue","продолжать","verb","A2"),
    ("contract","контракт","noun","A2"),("contradict","противоречить","verb","A2"),("contrast","контраст","noun","A2"),
    ("contribute","вносить вклад","verb","A2"),("convenience","удобство","noun","A2"),("convention","конвенция","noun","A2"),
    ("conversation","разговор","noun","A2"),("convince","убеждать","verb","A2"),("cooker","плита","noun","A2"),
    ("cookie","печенье","noun","A2"),("cooperate","сотрудничать","verb","A2"),("copper","медь","noun","A2"),
    ("copyright","авторское право","noun","A2"),("cord","шнур","noun","A2"),("corporation","корпорация","noun","A2"),
    ("correct","исправлять","verb","A2"),("corridor","коридор","noun","A2"),("costume","костюм","noun","A2"),
    ("cottage","коттедж","noun","A2"),("council","совет","noun","A2"),("counselor","консультант","noun","A2"),
    ("counter","счётчик","noun","A2"),("county","графство","noun","A2"),("couple","пара","noun","A2"),
    ("courage","смелость","noun","A2"),("course","курс","noun","A2"),("court","суд","noun","A2"),
    ("cousin","кузен","noun","A2"),("craft","ремесло","noun","A2"),("crash","авария","noun","A2"),
    ("creature","существо","noun","A2"),("credit","кредит","noun","A2"),("crew","команда","noun","A2"),
    ("cricket","крикет","noun","A2"),("crime","преступление","noun","A2"),("crisis","кризис","noun","A2"),
    ("critic","критик","noun","A2"),("crop","урожай","noun","A2"),("crossing","переход","noun","A2"),
    ("crowd","толпа","noun","A2"),("crown","корона","noun","A2"),("cruel","жестокий","adj","A2"),
    ("crystal","кристалл","noun","A2"),("cube","куб","noun","A2"),("cuisine","кухня","noun","A2"),
    ("culture","культура","noun","A2"),("cupboard","шкаф","noun","A2"),("curious","любопытный","adj","A2"),
    ("currency","валюта","noun","A2"),("current","течение","noun","A2"),("curse","проклятие","noun","A2"),
    ("curtain","занавеска","noun","A2"),("curve","кривая","noun","A2"),("cushion","подушка","noun","A2"),
    ("custom","обычай","noun","A2"),("customer","клиент","noun","A2"),("cycle","цикл","noun","A2"),
    ("daily","ежедневный","adj","A2"),("dairy","молочный","adj","A2"),("damage","ущерб","noun","A2"),
    ("damp","влажный","adj","A2"),("danger","опасность","noun","A2"),("deadline","крайний срок","noun","A2"),
    ("debate","дебаты","noun","A2"),("debt","долг","noun","A2"),("decade","десятилетие","noun","A2"),
    ("decay","гнить","verb","A2"),("decent","приличный","adj","A2"),("decision","решение","noun","A2"),
    ("declare","объявлять","verb","A2"),("decline","снижаться","verb","A2"),("decorate","украшать","verb","A2"),
    ("decrease","уменьшать","verb","A2"),("defeat","поражение","noun","A2"),("defend","защищать","verb","A2"),
    ("define","определять","verb","A2"),("definite","определённый","adj","A2"),("delay","задержка","noun","A2"),
    ("delegate","делегат","noun","A2"),("deliberately","умышленно","adv","A2"),("delicate","хрупкий","adj","A2"),
    ("delicious","вкусный","adj","A2"),("deliver","доставлять","verb","A2"),("demand","требовать","verb","A2"),
    ("democracy","демократия","noun","A2"),("demonstrate","демонстрировать","verb","A2"),("dense","плотный","adj","A2"),
    ("department","отдел","noun","A2"),("departure","отправление","noun","A2"),("depend","зависеть","verb","A2"),
    ("deposit","депозит","noun","A2"),("depress","угнетать","verb","A2"),("depth","глубина","noun","A2"),
    ("derive","получать из","verb","A2"),("descend","спускаться","verb","A2"),("describe","описывать","verb","A2"),
    ("desert","пустыня","noun","A2"),("deserve","заслуживать","verb","A2"),("design","дизайн","noun","A2"),
    ("desire","желание","noun","A2"),("desk","стол","noun","A2"),("desperate","отчаянный","adj","A2"),
    ("despite","несмотря на","prep","A2"),("dessert","десерт","noun","A2"),("destination","место назначения","noun","A2"),
    ("destroy","уничтожать","verb","A2"),("detail","деталь","noun","A2"),("detect","обнаруживать","verb","A2"),
    ("determine","определять","verb","A2"),("develop","развивать","verb","A2"),("device","устройство","noun","A2"),
    ("devote","посвящать","verb","A2"),("diagram","диаграмма","noun","A2"),("dial","набирать","verb","A2"),
    ("dialect","диалект","noun","A2"),("dialogue","диалог","noun","A2"),("diamond","алмаз","noun","A2"),
    ("diary","дневник","noun","A2"),("dictate","диктовать","verb","A2"),("diet","диета","noun","A2"),
    ("differ","различаться","verb","A2"),("digest","переваривать","verb","A2"),("dignity","достоинство","noun","A2"),
    ("dimension","измерение","noun","A2"),("dine","обедать","verb","A2"),("dip","окунать","verb","A2"),
    ("diploma","диплом","noun","A2"),("direct","направлять","verb","A2"),("director","директор","noun","A2"),
    ("dirt","грязь","noun","A2"),("disabled","инвалид","adj","A2"),("disagree","не соглашаться","verb","A2"),
    ("disappear","исчезать","verb","A2"),("disappoint","разочаровывать","verb","A2"),("disaster","катастрофа","noun","A2"),
    ("discard","выбрасывать","verb","A2"),("discipline","дисциплина","noun","A2"),("disclose","раскрывать","verb","A2"),
    ("discount","скидка","noun","A2"),("discover","обнаруживать","verb","A2"),("discuss","обсуждать","verb","A2"),
    ("disease","болезнь","noun","A2"),("dish","блюдо","noun","A2"),("disk","диск","noun","A2"),
    ("dismiss","увольнять","verb","A2"),("display","отображать","verb","A2"),("dissolve","растворять","verb","A2"),
    ("distance","расстояние","noun","A2"),("distant","далёкий","adj","A2"),("distinct","отчётливый","adj","A2"),
    ("distinguish","различать","verb","A2"),("distribute","распределять","verb","A2"),("district","район","noun","A2"),
    ("disturb","беспокоить","verb","A2"),("dive","нырять","verb","A2"),("diverse","разнообразный","adj","A2"),
    ("divide","делить","verb","A2"),("divorce","развод","noun","A2"),("document","документ","noun","A2"),
    ("domestic","домашний","adj","A2"),("dominate","господствовать","verb","A2"),("donate","жертвовать","verb","A2"),
    ("dough","тесто","noun","A2"),("dozen","дюжина","noun","A2"),("draft","черновик","noun","A2"),
    ("drain","сливать","verb","A2"),("drama","драма","noun","A2"),("drawer","ящик","noun","A2"),
    ("drift","дрейфовать","verb","A2"),("drill","сверло","noun","A2"),("drought","засуха","noun","A2"),
    ("drum","барабан","noun","A2"),("drunk","пьяный","adj","A2"),("due","надлежащий","adj","A2"),
    ("dull","скучный","adj","A2"),("dumb","глупый","adj","A2"),("duration","длительность","noun","A2"),
    ("dusk","сумерки","noun","A2"),("dust","пыль","noun","A2"),("dwarf","карлик","noun","A2"),
    ("dye","краска","noun","A2"),("eager","нетерпеливый","adj","A2"),("earn","зарабатывать","verb","A2"),
    ("ease","лёгкость","noun","A2"),("echo","эхо","noun","A2"),("economic","экономический","adj","A2"),
    ("economy","экономика","noun","A2"),("edge","край","noun","A2"),("edit","редактировать","verb","A2"),
    ("effect","эффект","noun","A2"),("efficient","эффективный","adj","A2"),("effort","усилие","noun","A2"),
    ("elbow","локоть","noun","A2"),("elderly","пожилой","adj","A2"),("elect","избирать","verb","A2"),
    ("election","выборы","noun","A2"),("electricity","электричество","noun","A2"),("electronic","электронный","adj","A2"),
    ("element","элемент","noun","A2"),("embassy","посольство","noun","A2"),("embrace","обнимать","verb","A2"),
    ("emerge","появляться","verb","A2"),("emotion","эмоция","noun","A2"),("emphasis","акцент","noun","A2"),
    ("employ","нанимать","verb","A2"),("employee","сотрудник","noun","A2"),("employer","работодатель","noun","A2"),
    ("empty","пустой","adj","A2"),("enable","позволять","verb","A2"),("encounter","встречать","verb","A2"),
    ("encourage","поощрять","verb","A2"),("endure","выносить","verb","A2"),("enemy","враг","noun","A2"),
    ("energy","энергия","noun","A2"),("engage","привлекать","verb","A2"),("engine","двигатель","noun","A2"),
    ("enhance","улучшать","verb","A2"),("enjoyable","приятный","adj","A2"),("enlarge","увеличивать","verb","A2"),
    ("enormous","огромный","adj","A2"),("enough","достаточно","det","A2"),("ensure","обеспечивать","verb","A2"),
    ("enterprise","предприятие","noun","A2"),("entertain","развлекать","verb","A2"),("enthusiasm","энтузиазм","noun","A2"),
    ("entire","целый","adj","A2"),("entrance","вход","noun","A2"),("environment","окружающая среда","noun","A2"),
    ("envy","зависть","noun","A2"),("episode","эпизод","noun","A2"),("equal","равный","adj","A2"),
    ("equip","оснащать","verb","A2"),("era","эра","noun","A2"),("error","ошибка","noun","A2"),
    ("escape","бежать","verb","A2"),("essay","эссе","noun","A2"),("essential","существенный","adj","A2"),
    ("establish","учреждать","verb","A2"),("estate","имение","noun","A2"),("estimate","оценивать","verb","A2"),
    ("ethnic","этнический","adj","A2"),("evaluate","оценивать","verb","A2"),("eventually","в конечном счёте","adv","A2"),
    ("everyday","повседневный","adj","A2"),("evidence","доказательство","noun","A2"),("evident","очевидный","adj","A2"),
    ("evil","зло","noun","A2"),("evolution","эволюция","noun","A2"),("exact","точный","adj","A2"),
    ("exaggerate","преувеличивать","verb","A2"),("examine","осматривать","verb","A2"),("exceed","превышать","verb","A2"),
    ("excellent","отличный","adj","A2"),("exchange","обмен","noun","A2"),("excited","взволнованный","adj","A2"),
    ("exclude","исключать","verb","A2"),("excuse","извинение","noun","A2"),("execute","выполнять","verb","A2"),
    ("exhaust","истощать","verb","A2"),("exhibit","выставлять","verb","A2"),("exhibition","выставка","noun","A2"),
    ("exist","существовать","verb","A2"),("exit","выход","noun","A2"),("expand","расширять","verb","A2"),
    ("expect","ожидать","verb","A2"),("expensive","дорогой","adj","A2"),("experience","опыт","noun","A2"),
    ("experiment","эксперимент","noun","A2"),("expert","эксперт","noun","A2"),("explain","объяснять","verb","A2"),
    ("explode","взрывать","verb","A2"),("explore","исследовать","verb","A2"),("export","экспорт","noun","A2"),
    ("expose","подвергать","verb","A2"),("express","выражать","verb","A2"),("extend","продлевать","verb","A2"),
    ("extension","расширение","noun","A2"),("extensive","обширный","adj","A2"),("extent","степень","noun","A2"),
    ("external","внешний","adj","A2"),("extra","дополнительный","adj","A2"),("extreme","крайний","adj","A2"),
    ("fabric","ткань","noun","A2"),("factor","фактор","noun","A2"),("faculty","факультет","noun","A2"),
    ("fail","проваливать","verb","A2"),("faint","слабый","adj","A2"),("fair","честный","adj","A2"),
    ("faith","вера","noun","A2"),("faithful","верный","adj","A2"),("fake","поддельный","adj","A2"),
    ("fame","слава","noun","A2"),("familiar","знакомый","adj","A2"),("famine","голод","noun","A2"),
    ("fancy","фантазийный","adj","A2"),("fare","плата за проезд","noun","A2"),("farewell","прощание","noun","A2"),
    ("farm","ферма","noun","A2"),("fascinate","очаровывать","verb","A2"),("fashion","мода","noun","A2"),
    ("fasten","пристёгивать","verb","A2"),("fatal","смертельный","adj","A2"),("fate","судьба","noun","A2"),
    ("fault","вина","noun","A2"),("favor","одолжение","noun","A2"),("fear","страх","noun","A2"),
    ("feasible","осуществимый","adj","A2"),("feast","пир","noun","A2"),("feature","особенность","noun","A2"),
    ("federal","федеральный","adj","A2"),("fee","плата","noun","A2"),("fellow","парень","noun","A2"),
    ("female","женский","adj","A2"),("fence","забор","noun","A2"),("festival","фестиваль","noun","A2"),
    ("fetch","приносить","verb","A2"),("fever","жар","noun","A2"),("fiber","волокно","noun","A2"),
    ("fiction","фантастика","noun","A2"),("figure","фигура","noun","A2"),("file","файл","noun","A2"),
    ("filter","фильтр","noun","A2"),("final","финальный","adj","A2"),("finance","финансы","noun","A2"),
    ("financial","финансовый","adj","A2"),("finger","палец","noun","A2"),("fireplace","камин","noun","A2"),
    ("firm","твёрдый","adj","A2"),("fishing","рыбалка","noun","A2"),("fitness","фитнес","noun","A2"),
    ("flag","флаг","noun","A2"),("flame","пламя","noun","A2"),("flash","вспышка","noun","A2"),
    ("flat","квартира","noun","A2"),("flavor","вкус","noun","A2"),("flee","бежать","verb","A2"),
    ("fleet","флот","noun","A2"),("flesh","плоть","noun","A2"),("flexible","гибкий","adj","A2"),
    ("flight","полёт","noun","A2"),("float","плавать","verb","A2"),("flood","наводнение","noun","A2"),
    ("floor","пол","noun","A2"),("flour","мука","noun","A2"),("flow","поток","noun","A2"),
    ("fluent","беглый","adj","A2"),("fluid","жидкость","noun","A2"),("focus","фокус","noun","A2"),
    ("fog","туман","noun","A2"),("fold","складывать","verb","A2"),("folk","народный","adj","A2"),
    ("follower","последователь","noun","A2"),("following","следующий","adj","A2"),("fond","любящий","adj","A2"),
    ("foolish","глупый","adj","A2"),("footstep","шаг","noun","A2"),("forbid","запрещать","verb","A2"),
    ("forecast","прогноз","noun","A2"),("foreigner","иностранец","noun","A2"),("forge","кузница","noun","A2"),
    ("forgive","прощать","verb","A2"),("formal","формальный","adj","A2"),("format","формат","noun","A2"),
    ("former","бывший","adj","A2"),("formula","формула","noun","A2"),("fortune","состояние","noun","A2"),
    ("fossil","окаменелость","noun","A2"),("fountain","фонтан","noun","A2"),("fragile","хрупкий","adj","A2"),
    ("frame","рама","noun","A2"),("fraud","мошенничество","noun","A2"),("freedom","свобода","noun","A2"),
    ("freeze","замерзать","verb","A2"),("freight","груз","noun","A2"),("frequency","частота","noun","A2"),
    ("frequent","частый","adj","A2"),("fridge","холодильник","noun","A2"),("frighten","пугать","verb","A2"),
    ("frost","мороз","noun","A2"),("frown","хмуриться","verb","A2"),("frustrate","расстраивать","verb","A2"),
    ("fuel","топливо","noun","A2"),("function","функция","noun","A2"),("fund","фонд","noun","A2"),
    ("fundamental","фундаментальный","adj","A2"),("funeral","похороны","noun","A2"),("fur","мех","noun","A2"),
    ("furnish","обставлять","verb","A2"),("furniture","мебель","noun","A2"),("further","дальше","adv","A2"),
    ("fuss","суета","noun","A2"),("gallery","галерея","noun","A2"),("garbage","мусор","noun","A2"),
    ("garlic","чеснок","noun","A2"),("gasoline","бензин","noun","A2"),("gather","собирать","verb","A2"),
    ("gauge","датчик","noun","A2"),("gaze","взгляд","noun","A2"),("gear","шестерёнка","noun","A2"),
    ("gender","гендер","noun","A2"),("generate","генерировать","verb","A2"),("generation","поколение","noun","A2"),
    ("generous","щедрый","adj","A2"),("genetic","генетический","adj","A2"),("genius","гений","noun","A2"),
    ("genuine","подлинный","adj","A2"),("gesture","жест","noun","A2"),("ghost","призрак","noun","A2"),
    ("giant","гигант","noun","A2"),("gift","подарок","noun","A2"),("ginger","имбирь","noun","A2"),
    ("glimpse","проблеск","noun","A2"),("globe","глобус","noun","A2"),("gloom","мрак","noun","A2"),
    ("glory","слава","noun","A2"),("glove","перчатка","noun","A2"),("glue","клей","noun","A2"),
    ("golf","гольф","noun","A2"),("gorgeous","великолепный","adj","A2"),("govern","управлять","verb","A2"),
    ("grace","грация","noun","A2"),("grade","оценка","noun","A2"),("gradual","постепенный","adj","A2"),
    ("grain","зерно","noun","A2"),("grand","грандиозный","adj","A2"),("grant","даровать","verb","A2"),
    ("grape","виноград","noun","A2"),("grasp","хватать","verb","A2"),("grass","трава","noun","A2"),
    ("grateful","благодарный","adj","A2"),("gravity","гравитация","noun","A2"),("greedy","жадный","adj","A2"),
    ("greet","приветствовать","verb","A2"),("grief","горе","noun","A2"),("grill","гриль","noun","A2"),
    ("grin","ухмылка","noun","A2"),("grip","хват","noun","A2"),("grocery","бакалея","noun","A2"),
    ("gross","валовой","adj","A2"),("guarantee","гарантия","noun","A2"),("guard","охранник","noun","A2"),
    ("guess","угадывать","verb","A2"),("guest","гость","noun","A2"),("guidance","руководство","noun","A2"),
    ("guilt","вина","noun","A2"),("gulf","залив","noun","A2"),("gum","жвачка","noun","A2"),
    ("gym","спортзал","noun","A2"),("habit","привычка","noun","A2"),("habitat","среда обитания","noun","A2"),
    ("haircut","стрижка","noun","A2"),("hallway","коридор","noun","A2"),("ham","ветчина","noun","A2"),
    ("hammer","молоток","noun","A2"),("handful","горсть","noun","A2"),("handle","ручка","noun","A2"),
    ("handy","удобный","adj","A2"),("happen","случаться","verb","A2"),("harbor","гавань","noun","A2"),
    ("hardly","едва","adv","A2"),("hardware","аппаратура","noun","A2"),("harm","вред","noun","A2"),
    ("harmony","гармония","noun","A2"),("harvest","урожай","noun","A2"),("haste","спешка","noun","A2"),
    ("hatred","ненависть","noun","A2"),("haunted","с привидениями","adj","A2"),("headache","головная боль","noun","A2"),
    ("headline","заголовок","noun","A2"),("headquarters","штаб","noun","A2"),("heal","исцелять","verb","A2"),
    ("health","здоровье","noun","A2"),("heap","куча","noun","A2"),("hearing","слух","noun","A2"),
    ("heaven","небо","noun","A2"),("heel","каблук","noun","A2"),("height","высота","noun","A2"),
    ("helmet","шлем","noun","A2"),("herb","трава","noun","A2"),("heritage","наследие","noun","A2"),
    ("hero","герой","noun","A2"),("hesitate","сомневаться","verb","A2"),("highlight","подчёркивать","verb","A2"),
    ("highway","шоссе","noun","A2"),("hike","поход","noun","A2"),("hint","намёк","noun","A2"),
    ("hip","бедро","noun","A2"),("hire","нанимать","verb","A2"),("historic","исторический","adj","A2"),
    ("hobby","хобби","noun","A2"),("hollow","полый","adj","A2"),("honest","честный","adj","A2"),
    ("honey","мёд","noun","A2"),("honor","честь","noun","A2"),("hook","крючок","noun","A2"),
    ("hopeful","надёжный","adj","A2"),("horizon","горизонт","noun","A2"),("horn","рог","noun","A2"),
    ("horror","ужас","noun","A2"),("horsepower","лошадиная сила","noun","A2"),("host","хозяин","noun","A2"),
    ("hostile","враждебный","adj","A2"),("household","домохозяйство","noun","A2"),("housewife","домохозяйка","noun","A2"),
    ("hug","объятие","noun","A2"),("humanity","человечество","noun","A2"),("humble","скромный","adj","A2"),
    ("humor","юмор","noun","A2"),("hunger","голод","noun","A2"),("hurricane","ураган","noun","A2"),
    ("hybrid","гибрид","noun","A2"),("hymn","гимн","noun","A2"),("ice cream","мороженое","noun","A2"),
    ("ideal","идеальный","adj","A2"),("identical","идентичный","adj","A2"),("identify","опознавать","verb","A2"),
    ("idiom","идиома","noun","A2"),("idle","праздный","adj","A2"),("ignorance","невежество","noun","A2"),
    ("ignore","игнорировать","verb","A2"),("illegal","незаконный","adj","A2"),("illness","болезнь","noun","A2"),
    ("illustrate","иллюстрировать","verb","A2"),("image","образ","noun","A2"),("imagination","воображение","noun","A2"),
    ("imitate","подражать","verb","A2"),("immigrant","иммигрант","noun","A2"),("impact","влияние","noun","A2"),
    ("implement","внедрять","verb","A2"),("implication","следствие","noun","A2"),("imply","подразумевать","verb","A2"),
    ("import","импорт","noun","A2"),("impose","налагать","verb","A2"),("impress","впечатлять","verb","A2"),
    ("improve","улучшать","verb","A2"),("incident","инцидент","noun","A2"),("include","включать","verb","A2"),
    ("income","доход","noun","A2"),("increase","увеличение","noun","A2"),("incredible","невероятный","adj","A2"),
    ("independence","независимость","noun","A2"),("index","индекс","noun","A2"),("indicate","указывать","verb","A2"),
    ("individual","индивидуальный","adj","A2"),("indoor","в помещении","adj","A2"),("induce","побуждать","verb","A2"),
    ("industrial","промышленный","adj","A2"),("industry","промышленность","noun","A2"),("inevitable","неизбежный","adj","A2"),
    ("infected","заражённый","adj","A2"),("inflation","инфляция","noun","A2"),("influence","влияние","noun","A2"),
    ("inform","информировать","verb","A2"),("ingredient","ингредиент","noun","A2"),("inherit","наследовать","verb","A2"),
    ("initial","первоначальный","adj","A2"),("injury","травма","noun","A2"),("inland","внутренний","adj","A2"),
    ("inn","гостиница","noun","A2"),("inner","внутренний","adj","A2"),("innocent","невинный","adj","A2"),
    ("inquire","спрашивать","verb","A2"),("insect","насекомое","noun","A2"),("insert","вставлять","verb","A2"),
    ("inside","внутри","prep","A2"),("insist","настаивать","verb","A2"),("inspect","осматривать","verb","A2"),
    ("inspire","вдохновлять","verb","A2"),("install","устанавливать","verb","A2"),("instance","случай","noun","A2"),
    ("instinct","инстинкт","noun","A2"),("institute","институт","noun","A2"),("instruct","инструктировать","verb","A2"),
    ("instrument","инструмент","noun","A2"),("insurance","страховка","noun","A2"),("integrate","интегрировать","verb","A2"),
    ("intend","намереваться","verb","A2"),("intense","интенсивный","adj","A2"),("interact","взаимодействовать","verb","A2"),
    ("interest","интерес","noun","A2"),("interfere","вмешиваться","verb","A2"),("interior","интерьер","noun","A2"),
    ("intermediate","средний","adj","A2"),("internal","внутренний","adj","A2"),("international","международный","adj","A2"),
    ("internet","интернет","noun","A2"),("interpret","интерпретировать","verb","A2"),("interrupt","перебивать","verb","A2"),
    ("interval","интервал","noun","A2"),("interview","интервью","noun","A2"),("introduce","представлять","verb","A2"),
    ("invade","вторгаться","verb","A2"),("invent","изобретать","verb","A2"),("invest","инвестировать","verb","A2"),
    ("investigate","расследовать","verb","A2"),("invite","приглашать","verb","A2"),("involve","вовлекать","verb","A2"),
    ("iron","утюг","noun","A2"),("irrelevant","неуместный","adj","A2"),("isolate","изолировать","verb","A2"),
    ("issue","выпуск","noun","A2"),("item","предмет","noun","A2"),("jacket","куртка","noun","A2"),
    ("jail","тюрьма","noun","A2"),("janitor","дворник","noun","A2"),("jar","банка","noun","A2"),
    ("jazz","джаз","noun","A2"),("jealous","ревнивый","adj","A2"),("jeans","джинсы","noun","A2"),
    ("jelly","желе","noun","A2"),("jersey","джерси","noun","A2"),("jet","реактивный","noun","A2"),
    ("jewel","драгоценность","noun","A2"),("jewelry","ювелирные изделия","noun","A2"),("jog","бегать трусцой","verb","A2"),
    ("journal","журнал","noun","A2"),("journalist","журналист","noun","A2"),("joyful","радостный","adj","A2"),
    ("judgment","суждение","noun","A2"),("juicy","сочный","adj","A2"),("jungle","джунгли","noun","A2"),
    ("junior","младший","adj","A2"),("jury","присяжные","noun","A2"),("justice","справедливость","noun","A2"),
    ("justify","оправдывать","verb","A2"),("keen","острый","adj","A2"),("kettle","чайник","noun","A2"),
    ("keyboard","клавиатура","noun","A2"),("kidnap","похищать","verb","A2"),("kidney","почка","noun","A2"),
    ("kindness","доброта","noun","A2"),("kingdom","королевство","noun","A2"),("kiosk","киоск","noun","A2"),
    ("kitchen","кухня","noun","A2"),("kite","воздушный змей","noun","A2"),("kneel","стоять на коленях","verb","A2"),
    ("knit","вязать","verb","A2"),("knob","ручка","noun","A2"),("labor","труд","noun","A2"),
    ("ladder","лестница","noun","A2"),("lakeside","берег озера","noun","A2"),("lamp","лампа","noun","A2"),
    ("landscape","пейзаж","noun","A2"),("lane","полоса","noun","A2"),("lantern","фонарь","noun","A2"),
    ("laptop","ноутбук","noun","A2"),("laser","лазер","noun","A2"),("laundry","прачечная","noun","A2"),
    ("lavatory","туалет","noun","A2"),("lawn","газон","noun","A2"),("lawsuit","иск","noun","A2"),
    ("lawyer","юрист","noun","A2"),("layer","слой","noun","A2"),("layout","план","noun","A2"),
    ("leader","лидер","noun","A2"),("leadership","руководство","noun","A2"),("leaflet","листовка","noun","A2"),
    ("league","лига","noun","A2"),("leak","течь","noun","A2"),("lean","наклоняться","verb","A2"),
    ("leap","прыжок","noun","A2"),("leather","кожа","noun","A2"),("lecture","лекция","noun","A2"),
    ("legal","законный","adj","A2"),("legend","легенда","noun","A2"),("leisure","досуг","noun","A2"),
    ("lemon","лимон","noun","A2"),("lemonade","лимонад","noun","A2"),("length","длина","noun","A2"),
    ("lens","линза","noun","A2"),("leopard","леопард","noun","A2"),("lesson","урок","noun","A2"),
    ("lettuce","салат","noun","A2"),("liable","ответственный","adj","A2"),("liberal","либеральный","adj","A2"),
    ("liberty","свобода","noun","A2"),("librarian","библиотекарь","noun","A2"),("license","лицензия","noun","A2"),
    ("lifestyle","образ жизни","noun","A2"),("lifetime","жизнь","noun","A2"),("lightning","молния","noun","A2"),
    ("likely","вероятный","adj","A2"),("limit","предел","noun","A2"),("limited","ограниченный","adj","A2"),
    ("limousine","лимузин","noun","A2"),("line","линия","noun","A2"),("linear","линейный","adj","A2"),
    ("linen","льняной","noun","A2"),("liner","лайнер","noun","A2"),("linger","задерживаться","verb","A2"),
    ("link","связь","noun","A2"),("liquid","жидкость","noun","A2"),("liquor","ликёр","noun","A2"),
    ("list","список","noun","A2"),("literary","литературный","adj","A2"),("literature","литература","noun","A2"),
    ("litter","мусор","noun","A2"),("livestock","скот","noun","A2"),("living","проживание","noun","A2"),
    ("load","груз","noun","A2"),("loan","заём","noun","A2"),("lobby","вестибюль","noun","A2"),
    ("lobster","омар","noun","A2"),("local","местный","adj","A2"),("locate","размещать","verb","A2"),
    ("location","место","noun","A2"),("lock","замок","noun","A2"),("lodge","домик","noun","A2"),
    ("log","бревно","noun","A2"),("logic","логика","noun","A2"),("logical","логичный","adj","A2"),
    ("lonely","одинокий","adj","A2"),("loop","петля","noun","A2"),("loose","свободный","adj","A2"),
    ("lord","господь","noun","A2"),("lorry","грузовик","noun","A2"),("lotion","лосьон","noun","A2"),
    ("lounge","гостиная","noun","A2"),("loyal","верный","adj","A2"),("luggage","багаж","noun","A2"),
    ("lumber","древесина","noun","A2"),("lump","кусок","noun","A2"),("lunar","лунный","adj","A2"),
    ("luxury","роскошь","noun","A2"),("lyrics","текст песни","noun","A2"),
]


def _gen_example(word: str, pos: str) -> str:
    w = word.lower()
    if pos == "verb":
        return f"I {w} every day."
    elif pos == "noun":
        return f"The {w} is important."
    elif pos == "adj":
        return f"It is very {w}."
    elif pos == "adv":
        return f"She speaks {w}."
    elif pos == "prep":
        return f"Look {w} the book."
    elif pos == "pron":
        return f"{word.capitalize()} is here."
    elif pos == "conj":
        return f"I like tea {w} coffee."
    elif pos == "num":
        return f"I have {w} books."
    else:
        return f"This is {w}."


def get_frequency_words2() -> list[tuple]:
    result = []
    for word, trans, pos, cefr in _W2:
        example = _gen_example(word, pos)
        result.append((word, trans, pos, example, cefr))
    return result
