"""Extended vocabulary database — additional 1700+ words to reach CEFR targets.

Targets based on research:
  A1: ~500 word families
  A2: ~1,000-1,500
  B1: ~2,000-2,500
  B2: ~3,500-4,500
  C1: ~6,000-8,000
  C2: ~10,000+

Sources: Oxford 3000/5000, NGSL 1.2 (2809 words), COCA frequency,
         Cambridge English Vocabulary in Use, IMO SMCP for maritime.

This file supplements wordbank.py — sets are merged at import time.
"""

from __future__ import annotations

from wordbank import VocabCard, VocabSet


# ═══════════════════════════════════════════════════════════════
# ADDITIONAL A1 VOCABULARY — ~440 new words (total target: ~500)
# ═══════════════════════════════════════════════════════════════

A1_EXTRA: list[VocabSet] = [
    VocabSet("A1", "Numbers & Quantities", [
        VocabCard("one", "один", "number", "I have one brother."),
        VocabCard("two", "два", "number", "Two cups of tea, please."),
        VocabCard("three", "три", "number", "Three apples are on the table."),
        VocabCard("four", "четыре", "number", "Four seasons in a year."),
        VocabCard("five", "пять", "number", "Give me five minutes."),
        VocabCard("six", "шесть", "number", "It's six o'clock."),
        VocabCard("seven", "семь", "number", "Seven days in a week."),
        VocabCard("eight", "восемь", "number", "Eight hours of sleep."),
        VocabCard("nine", "девять", "number", "Nine players on a team."),
        VocabCard("ten", "десять", "number", "Ten fingers on my hands."),
        VocabCard("hundred", "сотня", "number", "A hundred people came."),
        VocabCard("thousand", "тысяча", "number", "A thousand stars in the sky."),
        VocabCard("first", "первый", "adjective", "This is my first lesson."),
        VocabCard("second", "второй", "adjective", "The second floor is upstairs."),
        VocabCard("third", "третий", "adjective", "The third time is lucky."),
        VocabCard("last", "последний", "adjective", "He was the last person to leave."),
        VocabCard("many", "много", "determiner", "How many books do you have?"),
        VocabCard("much", "много", "determiner", "How much water do you need?"),
        VocabCard("few", "несколько", "determiner", "A few friends are coming."),
        VocabCard("little", "немного", "determiner", "I have a little time."),
        VocabCard("some", "несколько, немного", "determiner", "I need some help."),
        VocabCard("any", "любой, сколько-нибудь", "determiner", "Do you have any questions?"),
        VocabCard("all", "все", "determiner", "All students are here."),
        VocabCard("every", "каждый", "determiner", "Every day I learn English."),
        VocabCard("each", "каждый", "determiner", "Each student gets a book."),
    ]),
    VocabSet("A1", "Body & Health", [
        VocabCard("head", "голова", "noun", "My head hurts."),
        VocabCard("hand", "рука", "noun", "Raise your hand."),
        VocabCard("foot", "нога (ступня)", "noun", "My foot is cold."),
        VocabCard("eye", "глаз", "noun", "Close your eyes."),
        VocabCard("ear", "ухо", "noun", "I hear with my ears."),
        VocabCard("nose", "нос", "noun", "My nose is running."),
        VocabCard("mouth", "рот", "noun", "Open your mouth."),
        VocabCard("face", "лицо", "noun", "Wash your face."),
        VocabCard("hair", "волосы", "noun", "She has long hair."),
        VocabCard("arm", "рука (от кисти до плеча)", "noun", "He broke his arm."),
        VocabCard("leg", "нога", "noun", "My legs are tired."),
        VocabCard("finger", "палец", "noun", "I cut my finger."),
        VocabCard("tooth", "зуб", "noun", "I have a bad tooth."),
        VocabCard("back", "спина", "noun", "My back aches."),
        VocabCard("stomach", "живот", "noun", "My stomach hurts."),
        VocabCard("heart", "сердце", "noun", "My heart beats fast."),
        VocabCard("body", "тело", "noun", "Exercise is good for your body."),
        VocabCard("skin", "кожа", "noun", "Her skin is soft."),
        VocabCard("blood", "кровь", "noun", "Blood is red."),
        VocabCard("sick", "больной", "adjective", "I feel sick today."),
    ]),
    VocabSet("A1", "Family", [
        VocabCard("mother", "мать", "noun", "My mother is a teacher."),
        VocabCard("father", "отец", "noun", "My father works in a bank."),
        VocabCard("brother", "брат", "noun", "I have one brother."),
        VocabCard("sister", "сестра", "noun", "My sister is younger than me."),
        VocabCard("son", "сын", "noun", "Their son is five years old."),
        VocabCard("daughter", "дочь", "noun", "She has two daughters."),
        VocabCard("husband", "муж", "noun", "Her husband is a doctor."),
        VocabCard("wife", "жена", "noun", "His wife is a nurse."),
        VocabCard("grandmother", "бабушка", "noun", "My grandmother lives with us."),
        VocabCard("grandfather", "дедушка", "noun", "My grandfather is 80."),
        VocabCard("baby", "малыш", "noun", "The baby is sleeping."),
        VocabCard("boy", "мальчик", "noun", "The boy is playing football."),
        VocabCard("girl", "девочка", "noun", "The girl is reading a book."),
        VocabCard("man", "мужчина", "noun", "That man is my uncle."),
        VocabCard("woman", "женщина", "noun", "The woman is waiting for a bus."),
        VocabCard("parent", "родитель", "noun", "Parents love their children."),
        VocabCard("uncle", "дядя", "noun", "My uncle lives in Moscow."),
        VocabCard("aunt", "тётя", "noun", "My aunt is a cook."),
        VocabCard("cousin", "двоюродный брат/сестра", "noun", "I have three cousins."),
        VocabCard("grandparents", "бабушка и дедушка", "noun", "My grandparents are kind."),
    ]),
    VocabSet("A1", "Animals", [
        VocabCard("dog", "собака", "noun", "The dog is barking."),
        VocabCard("cat", "кошка", "noun", "My cat is sleeping."),
        VocabCard("bird", "птица", "noun", "The bird is singing."),
        VocabCard("fish", "рыба", "noun", "I like to eat fish."),
        VocabCard("horse", "лошадь", "noun", "The horse is running fast."),
        VocabCard("cow", "корова", "noun", "The cow gives milk."),
        VocabCard("pig", "свинья", "noun", "Pigs live on a farm."),
        VocabCard("sheep", "овца", "noun", "There are many sheep in the field."),
        VocabCard("chicken", "курица", "noun", "The chicken lays eggs."),
        VocabCard("duck", "утка", "noun", "Ducks swim in the lake."),
        VocabCard("rabbit", "кролик", "noun", "The rabbit eats carrots."),
        VocabCard("mouse", "мышь", "noun", "I saw a mouse in the kitchen."),
        VocabCard("bear", "медведь", "noun", "Bears live in the forest."),
        VocabCard("lion", "лев", "noun", "The lion is the king of animals."),
        VocabCard("tiger", "тигр", "noun", "Tigers have stripes."),
        VocabCard("elephant", "слон", "noun", "Elephants are very big."),
        VocabCard("monkey", "обезьяна", "noun", "Monkeys like bananas."),
        VocabCard("snake", "змея", "noun", "The snake is long."),
        VocabCard("spider", "паук", "noun", "I don't like spiders."),
        VocabCard("bee", "пчела", "noun", "Bees make honey."),
    ]),
    VocabSet("A1", "Adjectives", [
        VocabCard("good", "хороший", "adjective", "This is a good book."),
        VocabCard("bad", "плохой", "adjective", "I had a bad day."),
        VocabCard("big", "большой", "adjective", "It's a big house."),
        VocabCard("small", "маленький", "adjective", "I have a small dog."),
        VocabCard("new", "новый", "adjective", "My phone is new."),
        VocabCard("old", "старый", "adjective", "This car is very old."),
        VocabCard("hot", "горячий", "adjective", "The tea is too hot."),
        VocabCard("cold", "холодный", "adjective", "It's cold today."),
        VocabCard("happy", "счастливый", "adjective", "I am happy today."),
        VocabCard("sad", "грустный", "adjective", "She looks sad."),
        VocabCard("easy", "лёгкий", "adjective", "This test is easy."),
        VocabCard("difficult", "трудный", "adjective", "This question is difficult."),
        VocabCard("beautiful", "красивый", "adjective", "What a beautiful flower!"),
        VocabCard("ugly", "уродливый", "adjective", "That is an ugly building."),
        VocabCard("clean", "чистый", "adjective", "My room is clean."),
        VocabCard("dirty", "грязный", "adjective", "Your hands are dirty."),
        VocabCard("fast", "быстрый", "adjective", "He is a fast runner."),
        VocabCard("slow", "медленный", "adjective", "The internet is slow."),
        VocabCard("open", "открытый", "adjective", "The door is open."),
        VocabCard("closed", "закрытый", "adjective", "The shop is closed."),
        VocabCard("full", "полный", "adjective", "The glass is full."),
        VocabCard("empty", "пустой", "adjective", "The bottle is empty."),
        VocabCard("long", "длинный", "adjective", "It's a long road."),
        VocabCard("short", "короткий", "adjective", "She has short hair."),
        VocabCard("young", "молодой", "adjective", "He is a young man."),
        VocabCard("tired", "уставший", "adjective", "I am very tired."),
        VocabCard("hungry", "голодный", "adjective", "I'm hungry."),
        VocabCard("thirsty", "жаждущий", "adjective", "I'm thirsty."),
        VocabCard("angry", "сердитый", "adjective", "Don't be angry."),
        VocabCard("busy", "занятый", "adjective", "I'm busy right now."),
    ]),
    VocabSet("A1", "Question Words & Pronouns", [
        VocabCard("what", "что, какой", "pronoun", "What is your name?"),
        VocabCard("where", "где, куда", "pronoun", "Where do you live?"),
        VocabCard("when", "когда", "pronoun", "When is your birthday?"),
        VocabCard("who", "кто", "pronoun", "Who is that boy?"),
        VocabCard("how", "как", "pronoun", "How are you?"),
        VocabCard("why", "почему", "pronoun", "Why are you sad?"),
        VocabCard("which", "который", "pronoun", "Which book do you want?"),
        VocabCard("whose", "чей", "pronoun", "Whose pen is this?"),
        VocabCard("I", "я", "pronoun", "I am a student."),
        VocabCard("you", "ты, вы", "pronoun", "You are my friend."),
        VocabCard("he", "он", "pronoun", "He is a teacher."),
        VocabCard("she", "она", "pronoun", "She is very kind."),
        VocabCard("it", "это, он/она/оно (неодуш.)", "pronoun", "It is a cat."),
        VocabCard("we", "мы", "pronoun", "We are happy."),
        VocabCard("they", "они", "pronoun", "They are students."),
        VocabCard("me", "мне, меня", "pronoun", "Give it to me."),
        VocabCard("him", "ему, его", "pronoun", "I see him."),
        VocabCard("her", "ей, её", "pronoun", "I know her."),
        VocabCard("us", "нам, нас", "pronoun", "Tell us a story."),
        VocabCard("them", "им, их", "pronoun", "I called them yesterday."),
        VocabCard("my", "мой", "pronoun", "This is my book."),
        VocabCard("your", "твой, ваш", "pronoun", "Is this your pen?"),
        VocabCard("his", "его", "pronoun", "This is his car."),
        VocabCard("her", "её", "pronoun", "Her name is Anna."),
        VocabCard("our", "наш", "pronoun", "Our house is big."),
        VocabCard("their", "их", "pronoun", "Their dog is small."),
        VocabCard("this", "это", "pronoun", "This is my friend."),
        VocabCard("that", "то, тот", "pronoun", "That is a good idea."),
        VocabCard("these", "эти", "pronoun", "These books are new."),
        VocabCard("those", "те", "pronoun", "Those shoes are mine."),
    ]),
    VocabSet("A1", "Places & Buildings", [
        VocabCard("school", "школа", "noun", "I go to school by bus."),
        VocabCard("shop", "магазин", "noun", "The shop is near my house."),
        VocabCard("park", "парк", "noun", "We walk in the park."),
        VocabCard("street", "улица", "noun", "My street is very quiet."),
        VocabCard("city", "город", "noun", "London is a big city."),
        VocabCard("house", "дом", "noun", "Their house is new."),
        VocabCard("room", "комната", "noun", "My room is small."),
        VocabCard("kitchen", "кухня", "noun", "She is in the kitchen."),
        VocabCard("bathroom", "ванная", "noun", "Where is the bathroom?"),
        VocabCard("bedroom", "спальня", "noun", "My bedroom is upstairs."),
        VocabCard("garden", "сад", "noun", "We have a small garden."),
        VocabCard("office", "офис", "noun", "He works in an office."),
        VocabCard("hospital", "больница", "noun", "She is in the hospital."),
        VocabCard("restaurant", "ресторан", "noun", "Let's go to a restaurant."),
        VocabCard("library", "библиотека", "noun", "I study in the library."),
        VocabCard("station", "станция", "noun", "The station is far from here."),
        VocabCard("bank", "банк", "noun", "I need to go to the bank."),
        VocabCard("post office", "почта", "noun", "The post office is closed."),
        VocabCard("church", "церковь", "noun", "The church is very old."),
        VocabCard("bridge", "мост", "noun", "We crossed the bridge."),
    ]),
    VocabSet("A1", "Verbs Extended", [
        VocabCard("eat", "есть, кушать", "verb", "I eat breakfast at 8."),
        VocabCard("drink", "пить", "verb", "Drink more water."),
        VocabCard("sleep", "спать", "verb", "I sleep eight hours."),
        VocabCard("work", "работать", "verb", "She works in a bank."),
        VocabCard("live", "жить", "verb", "I live in Moscow."),
        VocabCard("speak", "говорить", "verb", "Do you speak English?"),
        VocabCard("read", "читать", "verb", "I read every day."),
        VocabCard("write", "писать", "verb", "Write your name here."),
        VocabCard("listen", "слушать", "verb", "Listen to the teacher."),
        VocabCard("open", "открывать", "verb", "Open the window."),
        VocabCard("close", "закрывать", "verb", "Close the door."),
        VocabCard("buy", "покупать", "verb", "I buy bread every day."),
        VocabCard("help", "помогать", "verb", "Can you help me?"),
        VocabCard("play", "играть", "verb", "Children play in the park."),
        VocabCard("run", "бегать", "verb", "I run every morning."),
        VocabCard("walk", "гулять, ходить", "verb", "We walk to school."),
        VocabCard("sit", "сидеть", "verb", "Sit down, please."),
        VocabCard("stand", "стоять", "verb", "Stand up, please."),
        VocabCard("love", "любить", "verb", "I love my family."),
        VocabCard("like", "нравиться", "verb", "I like coffee."),
        VocabCard("need", "нуждаться", "verb", "I need your help."),
        VocabCard("use", "использовать", "verb", "Can I use your phone?"),
        VocabCard("call", "звонить", "verb", "I'll call you tomorrow."),
        VocabCard("try", "пробовать", "verb", "Try this cake."),
        VocabCard("stop", "останавливать", "verb", "Stop the car."),
        VocabCard("start", "начинать", "verb", "The lesson starts at 9."),
        VocabCard("wait", "ждать", "verb", "Wait for me."),
        VocabCard("watch", "смотреть", "verb", "I watch TV in the evening."),
        VocabCard("move", "двигать(ся)", "verb", "Move to the left."),
        VocabCard("ask", "спрашивать", "verb", "Ask the teacher."),
    ]),
    VocabSet("A1", "Transport & Directions", [
        VocabCard("car", "машина", "noun", "My car is red."),
        VocabCard("bus", "автобус", "noun", "I take the bus to work."),
        VocabCard("train", "поезд", "noun", "The train is late."),
        VocabCard("plane", "самолёт", "noun", "The plane is taking off."),
        VocabCard("bike", "велосипед", "noun", "I ride my bike to school."),
        VocabCard("boat", "лодка", "noun", "We went by boat."),
        VocabCard("left", "лево, левый", "adverb", "Turn left at the corner."),
        VocabCard("right", "право, правый", "adverb", "Turn right at the shop."),
        VocabCard("straight", "прямо", "adverb", "Go straight ahead."),
        VocabCard("up", "вверх", "adverb", "Look up."),
        VocabCard("down", "вниз", "adverb", "Sit down."),
        VocabCard("here", "здесь", "adverb", "Come here."),
        VocabCard("there", "там", "adverb", "The book is there."),
        VocabCard("near", "близко", "adverb", "The shop is near."),
        VocabCard("far", "далеко", "adverb", "The airport is far."),
        VocabCard("in", "в", "preposition", "The cat is in the box."),
        VocabCard("on", "на", "preposition", "The book is on the table."),
        VocabCard("under", "под", "preposition", "The cat is under the chair."),
        VocabCard("behind", "за, позади", "preposition", "The dog is behind the tree."),
        VocabCard("next to", "рядом с", "preposition", "Sit next to me."),
    ]),
    VocabSet("A1", "Days, Months & Seasons", [
        VocabCard("Monday", "понедельник", "noun", "I work on Monday."),
        VocabCard("Tuesday", "вторник", "noun", "We meet on Tuesday."),
        VocabCard("Wednesday", "среда", "noun", "Wednesday is my busy day."),
        VocabCard("Thursday", "четверг", "noun", "I have a class on Thursday."),
        VocabCard("Friday", "пятница", "noun", "Friday is my favorite day."),
        VocabCard("Saturday", "суббота", "noun", "I relax on Saturday."),
        VocabCard("Sunday", "воскресенье", "noun", "We go to the park on Sunday."),
        VocabCard("January", "январь", "noun", "It's cold in January."),
        VocabCard("February", "февраль", "noun", "February has 28 days."),
        VocabCard("March", "март", "noun", "March is the first month of spring."),
        VocabCard("April", "апрель", "noun", "April showers bring May flowers."),
        VocabCard("May", "май", "noun", "May is a beautiful month."),
        VocabCard("June", "июнь", "noun", "School ends in June."),
        VocabCard("July", "июль", "noun", "We go on holiday in July."),
        VocabCard("August", "август", "noun", "August is very hot."),
        VocabCard("September", "сентябрь", "noun", "School starts in September."),
        VocabCard("October", "октябрь", "noun", "The leaves fall in October."),
        VocabCard("November", "ноябрь", "noun", "November is cold."),
        VocabCard("December", "декабрь", "noun", "Christmas is in December."),
        VocabCard("spring", "весна", "noun", "Flowers grow in spring."),
        VocabCard("summer", "лето", "noun", "I love summer."),
        VocabCard("autumn", "осень", "noun", "Leaves are red in autumn."),
        VocabCard("winter", "зима", "noun", "It snows in winter."),
    ]),
    VocabSet("A1", "Common Adverbs & Conjunctions", [
        VocabCard("yes", "да", "adverb", "Yes, I can."),
        VocabCard("no", "нет", "adverb", "No, thank you."),
        VocabCard("very", "очень", "adverb", "It's very cold."),
        VocabCard("too", "тоже, слишком", "adverb", "I want to come too."),
        VocabCard("also", "также", "adverb", "I also like tea."),
        VocabCard("only", "только", "adverb", "I have only one pen."),
        VocabCard("again", "снова", "adverb", "Say it again, please."),
        VocabCard("sometimes", "иногда", "adverb", "Sometimes I walk to work."),
        VocabCard("always", "всегда", "adverb", "I always drink coffee."),
        VocabCard("never", "никогда", "adverb", "I never eat fast food."),
        VocabCard("usually", "обычно", "adverb", "I usually wake up at 7."),
        VocabCard("often", "часто", "adverb", "I often go to the cinema."),
        VocabCard("and", "и", "conjunction", "You and I are friends."),
        VocabCard("but", "но", "conjunction", "I like tea but not coffee."),
        VocabCard("or", "или", "conjunction", "Tea or coffee?"),
        VocabCard("because", "потому что", "conjunction", "I'm tired because I worked late."),
        VocabCard("so", "поэтому", "conjunction", "It's late, so I go home."),
        VocabCard("if", "если", "conjunction", "If it rains, I'll stay home."),
        VocabCard("with", "с", "preposition", "I go with my friend."),
        VocabCard("without", "без", "preposition", "I can't do it without you."),
    ]),
    VocabSet("A1", "More Common Words", [
        VocabCard("water", "вода", "noun", "I drink water."),
        VocabCard("fire", "огонь", "noun", "The fire is hot."),
        VocabCard("sun", "солнце", "noun", "The sun is bright."),
        VocabCard("moon", "луна", "noun", "The moon is full tonight."),
        VocabCard("star", "звезда", "noun", "I see a star."),
        VocabCard("sky", "небо", "noun", "The sky is blue."),
        VocabCard("ground", "земля, пол", "noun", "The book is on the ground."),
        VocabCard("world", "мир", "noun", "The world is big."),
        VocabCard("word", "слово", "noun", "What does this word mean?"),
        VocabCard("letter", "буква, письмо", "noun", "I wrote a letter."),
        VocabCard("number", "число, номер", "noun", "What's your phone number?"),
        VocabCard("name", "имя", "noun", "My name is Olga."),
        VocabCard("place", "место", "noun", "This is a nice place."),
        VocabCard("thing", "вещь", "noun", "What is this thing?"),
        VocabCard("way", "путь, способ", "noun", "Which way to the station?"),
        VocabCard("part", "часть", "noun", "This is part of the book."),
        VocabCard("side", "сторона", "noun", "The other side of the street."),
        VocabCard("line", "линия, очередь", "noun", "Draw a line."),
        VocabCard("group", "группа", "noun", "We work in groups."),
        VocabCard("music", "музыка", "noun", "I love music."),
        VocabCard("song", "песня", "noun", "This song is beautiful."),
        VocabCard("game", "игра", "noun", "Let's play a game."),
        VocabCard("sport", "спорт", "noun", "I like sport."),
        VocabCard("ball", "мяч", "noun", "The ball is round."),
        VocabCard("picture", "картинка", "noun", "Take a picture."),
        VocabCard("money", "деньги", "noun", "I need some money."),
        VocabCard("food", "еда", "noun", "The food is delicious."),
        VocabCard("dog", "собака", "noun", "My dog is big."),
        VocabCard("cat", "кошка", "noun", "The cat is black."),
        VocabCard("fish", "рыба", "noun", "Fish live in water."),
    ]),
]


# ═══════════════════════════════════════════════════════════════
# ADDITIONAL A2 VOCABULARY — ~300 new words
# ═══════════════════════════════════════════════════════════════

A2_EXTRA: list[VocabSet] = [
    VocabSet("A2", "House & Furniture", [
        VocabCard("sofa", "диван", "noun", "The sofa is comfortable."),
        VocabCard("bed", "кровать", "noun", "My bed is very soft."),
        VocabCard("fridge", "холодильник", "noun", "The milk is in the fridge."),
        VocabCard("oven", "духовка", "noun", "Put the cake in the oven."),
        VocabCard("mirror", "зеркало", "noun", "Look in the mirror."),
        VocabCard("lamp", "лампа", "noun", "Turn on the lamp."),
        VocabCard("shelf", "полка", "noun", "Books are on the shelf."),
        VocabCard("carpet", "ковёр", "noun", "The carpet is on the floor."),
        VocabCard("wall", "стена", "noun", "There's a picture on the wall."),
        VocabCard("floor", "пол, этаж", "noun", "We live on the second floor."),
        VocabCard("ceiling", "потолок", "noun", "The ceiling is white."),
        VocabCard("garden", "сад", "noun", "She works in the garden."),
        VocabCard("garage", "гараж", "noun", "The car is in the garage."),
        VocabCard("balcony", "балкон", "noun", "I have coffee on the balcony."),
        VocabCard("stairs", "лестница", "noun", "The stairs are steep."),
        VocabCard("toilet", "туалет", "noun", "Where is the toilet?"),
        VocabCard("sink", "раковина", "noun", "Wash your hands in the sink."),
        VocabCard("cupboard", "шкаф", "noun", "Cups are in the cupboard."),
        VocabCard("drawer", "ящик", "noun", "Open the top drawer."),
        VocabCard("blanket", "одеяло", "noun", "I need a warm blanket."),
    ]),
    VocabSet("A2", "Jobs & Work", [
        VocabCard("nurse", "медсестра", "noun", "She is a nurse."),
        VocabCard("engineer", "инженер", "noun", "He is a software engineer."),
        VocabCard("lawyer", "юрист", "noun", "The lawyer is in court."),
        VocabCard("chef", "шеф-повар", "noun", "The chef cooks well."),
        VocabCard("driver", "водитель", "noun", "The driver is waiting."),
        VocabCard("singer", "певец", "noun", "She is a famous singer."),
        VocabCard("artist", "художник", "noun", "The artist paints landscapes."),
        VocabCard("writer", "писатель", "noun", "He is a writer."),
        VocabCard("pilot", "лётчик", "noun", "The pilot flies planes."),
        VocabCard("farmer", "фермер", "noun", "The farmer has many cows."),
        VocabCard("police officer", "полицейский", "noun", "The police officer helps people."),
        VocabCard("firefighter", "пожарный", "noun", "The firefighter is brave."),
        VocabCard("manager", "менеджер", "noun", "Our manager is strict."),
        VocabCard("secretary", "секретарь", "noun", "The secretary answers calls."),
        VocabCard("soldier", "солдат", "noun", "The soldier is strong."),
        VocabCard("waiter", "официант", "noun", "The waiter brought the menu."),
        VocabCard("builder", "строитель", "noun", "The builder works hard."),
        VocabCard("mechanic", "механик", "noun", "The mechanic fixed my car."),
        VocabCard("electrician", "электрик", "noun", "We need an electrician."),
        VocabCard("cleaner", "уборщик", "noun", "The cleaner comes at 6 AM."),
    ]),
    VocabSet("A2", "Food Extended", [
        VocabCard("meat", "мясо", "noun", "I don't eat meat."),
        VocabCard("fish", "рыба", "noun", "I had fish for dinner."),
        VocabCard("vegetable", "овощ", "noun", "Eat more vegetables."),
        VocabCard("fruit", "фрукт", "noun", "I love fresh fruit."),
        VocabCard("sugar", "сахар", "noun", "One sugar, please."),
        VocabCard("salt", "соль", "noun", "Add some salt."),
        VocabCard("butter", "масло", "noun", "I like butter on my bread."),
        VocabCard("soup", "суп", "noun", "The soup is hot."),
        VocabCard("salad", "салат", "noun", "I ordered a salad."),
        VocabCard("dessert", "десерт", "noun", "What's for dessert?"),
        VocabCard("chocolate", "шоколад", "noun", "I love chocolate."),
        VocabCard("cake", "торт", "noun", "She made a cake."),
        VocabCard("pizza", "пицца", "noun", "Let's order a pizza."),
        VocabCard("sandwich", "бутерброд", "noun", "I had a sandwich for lunch."),
        VocabCard("juice", "сок", "noun", "Orange juice, please."),
        VocabCard("beer", "пиво", "noun", "He drinks beer on Fridays."),
        VocabCard("wine", "вино", "noun", "Red or white wine?"),
        VocabCard("breakfast", "завтрак", "noun", "I have breakfast at 8."),
        VocabCard("lunch", "обед", "noun", "Lunch is at noon."),
        VocabCard("dinner", "ужин", "noun", "Dinner is at 7 PM."),
    ]),
    VocabSet("A2", "Clothes Extended", [
        VocabCard("trousers", "брюки", "noun", "My trousers are black."),
        VocabCard("jeans", "джинсы", "noun", "I wear jeans every day."),
        VocabCard("t-shirt", "футболка", "noun", "This t-shirt is new."),
        VocabCard("jacket", "куртка", "noun", "Put on your jacket."),
        VocabCard("skirt", "юбка", "noun", "Her skirt is long."),
        VocabCard("socks", "носки", "noun", "I need clean socks."),
        VocabCard("gloves", "перчатки", "noun", "Wear gloves in winter."),
        VocabCard("scarf", "шарф", "noun", "She has a red scarf."),
        VocabCard("boots", "ботинки", "noun", "My boots are waterproof."),
        VocabCard("hat", "шляпа", "noun", "He wears a hat."),
        VocabCard("cap", "кепка", "noun", "I bought a new cap."),
        VocabCard("belt", "ремень", "noun", "I need a new belt."),
        VocabCard("pyjamas", "пижама", "noun", "My pyjamas are blue."),
        VocabCard("umbrella", "зонт", "noun", "Take an umbrella."),
        VocabCard("wallet", "кошелёк", "noun", "I lost my wallet."),
        VocabCard("glasses", "очки", "noun", "She wears glasses."),
        VocabCard("ring", "кольцо", "noun", "He gave her a ring."),
        VocabCard("watch", "часы (наручные)", "noun", "My watch is slow."),
        VocabCard("bag", "сумка", "noun", "My bag is heavy."),
        VocabCard("pocket", "карман", "noun", "I have money in my pocket."),
    ]),
    VocabSet("A2", "Nature & Weather Extended", [
        VocabCard("cloud", "облако", "noun", "The clouds are dark."),
        VocabCard("rain", "дождь", "noun", "The rain stopped."),
        VocabCard("wind", "ветер", "noun", "The wind is strong."),
        VocabCard("storm", "буря", "noun", "A storm is coming."),
        VocabCard("fog", "туман", "noun", "There's fog on the road."),
        VocabCard("ice", "лёд", "noun", "The ice is thin."),
        VocabCard("sunshine", "солнечный свет", "noun", "I love the sunshine."),
        VocabCard("flower", "цветок", "noun", "The flower is beautiful."),
        VocabCard("grass", "трава", "noun", "The grass is green."),
        VocabCard("leaf", "лист", "noun", "A leaf fell from the tree."),
        VocabCard("stone", "камень", "noun", "The stone is heavy."),
        VocabCard("sand", "песок", "noun", "The sand is hot."),
        VocabCard("lake", "озеро", "noun", "We swam in the lake."),
        VocabCard("hill", "холм", "noun", "The hill is not very high."),
        VocabCard("valley", "долина", "noun", "The valley is beautiful."),
        VocabCard("island", "остров", "noun", "We visited a small island."),
        VocabCard("beach", "пляж", "noun", "The beach is sandy."),
        VocabCard("ocean", "океан", "noun", "The ocean is deep."),
        VocabCard("desert", "пустыня", "noun", "The desert is hot and dry."),
        VocabCard("field", "поле", "noun", "Cows are in the field."),
    ]),
    VocabSet("A2", "Sports & Hobbies", [
        VocabCard("football", "футбол", "noun", "I play football on Sundays."),
        VocabCard("tennis", "теннис", "noun", "Tennis is my favorite sport."),
        VocabCard("swimming", "плавание", "noun", "Swimming is good for you."),
        VocabCard("running", "бег", "noun", "Running keeps you fit."),
        VocabCard("cycling", "велоспорт", "noun", "I enjoy cycling."),
        VocabCard("dancing", "танцы", "noun", "She loves dancing."),
        VocabCard("fishing", "рыбалка", "noun", "He goes fishing every weekend."),
        VocabCard("painting", "рисование", "noun", "Painting is relaxing."),
        VocabCard("photography", "фотография", "noun", "Photography is my hobby."),
        VocabCard("cooking", "кулинария", "noun", "I enjoy cooking."),
        VocabCard("reading", "чтение", "noun", "Reading is fun."),
        VocabCard("singing", "пение", "noun", "Singing makes me happy."),
        VocabCard("guitar", "гитара", "noun", "He plays the guitar."),
        VocabCard("piano", "пианино", "noun", "She plays the piano."),
        VocabCard("chess", "шахматы", "noun", "I play chess online."),
        VocabCard("card", "карта (игральная)", "noun", "Let's play cards."),
        VocabCard("team", "команда", "noun", "Our team won."),
        VocabCard("player", "игрок", "noun", "He is a good player."),
        VocabCard("match", "матч", "noun", "We watched the match."),
        VocabCard("win", "выигрывать", "verb", "I hope we win."),
    ]),
    VocabSet("A2", "Daily Activities", [
        VocabCard("wash", "мыть", "verb", "Wash your hands."),
        VocabCard("clean", "убирать", "verb", "I clean my room on Sundays."),
        VocabCard("cook", "готовить", "verb", "She cooks dinner every day."),
        VocabCard("drive", "водить", "verb", "I drive to work."),
        VocabCard("ride", "ездить верхом/на чём-то", "verb", "I ride my bike."),
        VocabCard("fly", "летать", "verb", "Birds can fly."),
        VocabCard("swim", "плавать", "verb", "I can swim well."),
        VocabCard("climb", "лезть, взбираться", "verb", "We climbed the hill."),
        VocabCard("jump", "прыгать", "verb", "The cat jumped on the table."),
        VocabCard("fall", "падать", "verb", "Leaves fall in autumn."),
        VocabCard("laugh", "смеяться", "verb", "Don't laugh at me."),
        VocabCard("cry", "плакать", "verb", "The baby is crying."),
        VocabCard("smile", "улыбаться", "verb", "She smiled at me."),
        VocabCard("sing", "петь", "verb", "She sings beautifully."),
        VocabCard("dance", "танцевать", "verb", "They dance together."),
        VocabCard("draw", "рисовать", "verb", "I draw in my notebook."),
        VocabCard("paint", "красить, рисовать красками", "verb", "He painted the wall."),
        VocabCard("build", "строить", "verb", "They build houses."),
        VocabCard("fix", "чинить", "verb", "Can you fix my phone?"),
        VocabCard("send", "отправлять", "verb", "I sent an email."),
    ]),
    VocabSet("A2", "Adjectives Extended", [
        VocabCard("warm", "тёплый", "adjective", "The water is warm."),
        VocabCard("cool", "прохладный", "adjective", "It's cool outside."),
        VocabCard("wet", "мокрый", "adjective", "The grass is wet."),
        VocabCard("dry", "сухой", "adjective", "The ground is dry."),
        VocabCard("hard", "твёрдый, сложный", "adjective", "This is a hard question."),
        VocabCard("soft", "мягкий", "adjective", "The pillow is soft."),
        VocabCard("heavy", "тяжёлый", "adjective", "This box is heavy."),
        VocabCard("light", "лёгкий, светлый", "adjective", "The bag is light."),
        VocabCard("safe", "безопасный", "adjective", "Is this street safe?"),
        VocabCard("dangerous", "опасный", "adjective", "It's a dangerous road."),
        VocabCard("correct", "правильный", "adjective", "Your answer is correct."),
        VocabCard("wrong", "неправильный", "adjective", "This is the wrong answer."),
        VocabCard("same", "тот же самый", "adjective", "We have the same phone."),
        VocabCard("different", "разный", "adjective", "They are very different."),
        VocabCard("important", "важный", "adjective", "This is important."),
        VocabCard("possible", "возможный", "adjective", "Is it possible?"),
        VocabCard("ready", "готовый", "adjective", "Dinner is ready."),
        VocabCard("free", "свободный, бесплатный", "adjective", "This ticket is free."),
        VocabCard("busy", "занятый", "adjective", "I'm busy today."),
        VocabCard("popular", "популярный", "adjective", "He is a popular singer."),
    ]),
    VocabSet("A2", "Time & Frequency", [
        VocabCard("early", "рано", "adverb", "I wake up early."),
        VocabCard("late", "поздно", "adverb", "He arrived late."),
        VocabCard("quickly", "быстро", "adverb", "She speaks quickly."),
        VocabCard("slowly", "медленно", "adverb", "Walk slowly."),
        VocabCard("loudly", "громко", "adverb", "Don't talk loudly."),
        VocabCard("quietly", "тихо", "adverb", "Please read quietly."),
        VocabCard("well", "хорошо", "adverb", "She sings well."),
        VocabCard("badly", "плохо", "adverb", "He plays badly."),
        VocabCard("hard", "усердно", "adverb", "I study hard."),
        VocabCard("fast", "быстро", "adverb", "He runs fast."),
        VocabCard("today", "сегодня", "adverb", "I'm busy today."),
        VocabCard("yesterday", "вчера", "adverb", "I saw him yesterday."),
        VocabCard("tomorrow", "завтра", "adverb", "See you tomorrow."),
        VocabCard("soon", "скоро", "adverb", "I'll be back soon."),
        VocabCard("later", "позже", "adverb", "I'll call you later."),
        VocabCard("before", "до, раньше", "adverb", "I was here before."),
        VocabCard("after", "после", "adverb", "We'll eat after the game."),
        VocabCard("suddenly", "внезапно", "adverb", "Suddenly it rained."),
        VocabCard("finally", "наконец", "adverb", "Finally, I finished."),
        VocabCard("already", "уже", "adverb", "I already ate."),
    ]),
    VocabSet("A2", "Communication & Feelings", [
        VocabCard("talk", "разговаривать", "verb", "Let's talk about it."),
        VocabCard("tell", "сказать (кому-то)", "verb", "Tell me a story."),
        VocabCard("ask", "спрашивать", "verb", "Ask the teacher."),
        VocabCard("answer", "отвечать", "verb", "Answer the question."),
        VocabCard("explain", "объяснять", "verb", "Can you explain this?"),
        VocabCard("understand", "понимать", "verb", "I understand now."),
        VocabCard("remember", "помнить", "verb", "I remember her name."),
        VocabCard("forget", "забывать", "verb", "Don't forget your keys."),
        VocabCard("believe", "верить", "verb", "I believe you."),
        VocabCard("hope", "надеяться", "verb", "I hope you're right."),
        VocabCard("feel", "чувствовать", "verb", "I feel happy."),
        VocabCard("look", "смотреть", "verb", "Look at this!"),
        VocabCard("hear", "слышать", "verb", "I can hear you."),
        VocabCard("smell", "пахнуть", "verb", "The food smells good."),
        VocabCard("taste", "пробовать на вкус", "verb", "This tastes great."),
        VocabCard("touch", "трогать", "verb", "Don't touch it."),
        VocabCard("scared", "испуганный", "adjective", "I'm scared of spiders."),
        VocabCard("surprised", "удивлённый", "adjective", "I was surprised."),
        VocabCard("bored", "скучающий", "adjective", "I'm bored."),
        VocabCard("worried", "обеспокоенный", "adjective", "She looks worried."),
    ]),
    VocabSet("A2", "Places & Travel Extended", [
        VocabCard("country", "страна", "noun", "France is a beautiful country."),
        VocabCard("village", "деревня", "noun", "My grandparents live in a village."),
        VocabCard("capital", "столица", "noun", "London is the capital of England."),
        VocabCard("abroad", "за границей", "adverb", "I want to study abroad."),
        VocabCard("holiday", "отпуск, праздник", "noun", "We went on holiday to Spain."),
        VocabCard("trip", "поездка", "noun", "We had a great trip."),
        VocabCard("tour", "тур, экскурсия", "noun", "We took a tour of the city."),
        VocabCard("map", "карта", "noun", "Check the map."),
        VocabCard("road", "дорога", "noun", "The road is long."),
        VocabCard("sign", "знак, вывеска", "noun", "Read the sign."),
        VocabCard("museum", "музей", "noun", "We visited the museum."),
        VocabCard("gallery", "галерея", "noun", "The art gallery is open."),
        VocabCard("cinema", "кинотеатр", "noun", "Let's go to the cinema."),
        VocabCard("theatre", "театр", "noun", "We went to the theatre."),
        VocabCard("zoo", "зоопарк", "noun", "The kids love the zoo."),
        VocabCard("hotel", "отель", "noun", "We stayed at a nice hotel."),
        VocabCard("camp", "лагерь", "noun", "We set up camp."),
        VocabCard("border", "граница", "noun", "We crossed the border."),
        VocabCard("ticket", "билет", "noun", "I bought a ticket."),
        VocabCard("passport", "паспорт", "noun", "Show me your passport."),
    ]),
    VocabSet("A2", "School & Education Extended", [
        VocabCard("subject", "предмет", "noun", "Math is my favorite subject."),
        VocabCard("math", "математика", "noun", "I'm good at math."),
        VocabCard("science", "наука", "noun", "Science is interesting."),
        VocabCard("history", "история", "noun", "I love history."),
        VocabCard("geography", "география", "noun", "Geography is about places."),
        VocabCard("art", "искусство", "noun", "She is good at art."),
        VocabCard("language", "язык", "noun", "English is a global language."),
        VocabCard("test", "контрольная", "noun", "The test was hard."),
        VocabCard("mark", "оценка", "noun", "I got a good mark."),
        VocabCard("report", "доклад", "noun", "I wrote a report."),
        VocabCard("project", "проект", "noun", "We did a group project."),
        VocabCard("dictionary", "словарь", "noun", "Use a dictionary."),
        VocabCard("computer", "компьютер", "noun", "I use my computer every day."),
        VocabCard("internet", "интернет", "noun", "The internet is slow today."),
        VocabCard("email", "электронное письмо", "noun", "I sent you an email."),
        VocabCard("website", "сайт", "noun", "Visit our website."),
        VocabCard("page", "страница", "noun", "Turn to page 10."),
        VocabCard("text", "текст", "noun", "Read the text."),
        VocabCard("word", "слово", "noun", "What does this word mean?"),
        VocabCard("sentence", "предложение", "noun", "Write a sentence."),
    ]),
    VocabSet("A2", "Money & Shopping Extended", [
        VocabCard("cash", "наличные", "noun", "I pay with cash."),
        VocabCard("card", "карта", "noun", "Can I pay by card?"),
        VocabCard("bill", "счёт, купюра", "noun", "The bill is $20."),
        VocabCard("coin", "монета", "noun", "I have a few coins."),
        VocabCard("bank", "банк", "noun", "I go to the bank on Fridays."),
        VocabCard("credit card", "кредитная карта", "noun", "I use my credit card."),
        VocabCard("discount", "скидка", "noun", "I got a 20% discount."),
        VocabCard("size", "размер", "noun", "What size do you need?"),
        VocabCard("colour", "цвет", "noun", "What colour is it?"),
        VocabCard("brand", "бренд", "noun", "I like this brand."),
        VocabCard("market", "рынок", "noun", "We went to the market."),
        VocabCard("supermarket", "супермаркет", "noun", "I shop at the supermarket."),
        VocabCard("customer", "покупатель", "noun", "The customer is happy."),
        VocabCard("seller", "продавец", "noun", "The seller was friendly."),
        VocabCard("order", "заказ", "noun", "I placed an order online."),
        VocabCard("deliver", "доставлять", "verb", "They deliver on Mondays."),
        VocabCard("return", "возвращать", "verb", "I want to return this."),
        VocabCard("exchange", "обменивать", "verb", "Can I exchange this?"),
        VocabCard("spend", "тратить", "verb", "I spent $50."),
        VocabCard("save", "экономить", "verb", "I save money for holidays."),
    ]),
]
