"""Extended vocabulary part 2 — B2 extra, Maritime English, Slang & Swear words."""

from __future__ import annotations

from wordbank import VocabCard, VocabSet


# ═══════════════════════════════════════════════════════════════
# ADDITIONAL B2 VOCABULARY — ~200 new words
# ═══════════════════════════════════════════════════════════════

B2_EXTRA: list[VocabSet] = [
    VocabSet("B2", "Advanced Adjectives", [
        VocabCard("controversial", "спорный", "adjective", "It's a controversial topic."),
        VocabCard("convincing", "убедительный", "adjective", "She gave a convincing argument."),
        VocabCard("dramatic", "драматичный", "adjective", "There was a dramatic change."),
        VocabCard("effective", "эффективный", "adjective", "It's an effective method."),
        VocabCard("efficient", "эффективный (КПД)", "adjective", "The system is very efficient."),
        VocabCard("essential", "существенный", "adjective", "Water is essential for life."),
        VocabCard("excessive", "чрезмерный", "adjective", "The price is excessive."),
        VocabCard("genuine", "подлинный", "adjective", "It's a genuine diamond."),
        VocabCard("gradual", "постепенный", "adjective", "There was a gradual improvement."),
        VocabCard("inevitable", "неизбежный", "adjective", "Change is inevitable."),
        VocabCard("intense", "интенсивный", "adjective", "The heat was intense."),
        VocabCard("mild", "мягкий", "adjective", "It's a mild winter."),
        VocabCard("novel", "новый, оригинальный", "adjective", "That's a novel approach."),
        VocabCard("persistent", "настойчивый", "adjective", "She is very persistent."),
        VocabCard("plausible", "правдоподобный", "adjective", "His story is plausible."),
        VocabCard("relevant", "уместный", "adjective", "Is this relevant?"),
        VocabCard("remarkable", "замечательный", "adjective", "It's a remarkable achievement."),
        VocabCard("sufficient", "достаточный", "adjective", "We have sufficient food."),
        VocabCard("valid", "обоснованный", "adjective", "That's a valid point."),
        VocabCard("vague", "неясный", "adjective", "He gave a vague answer."),
    ]),
    VocabSet("B2", "Advanced Verbs", [
        VocabCard("acknowledge", "признавать", "verb", "He acknowledged his error."),
        VocabCard("anticipate", "предвидеть", "verb", "I anticipate no problems."),
        VocabCard("compile", "составлять", "verb", "She compiled a report."),
        VocabCard("comprise", "состоять из", "verb", "The team comprises ten people."),
        VocabCard("conceal", "скрывать", "verb", "He concealed his feelings."),
        VocabCard("constitute", "составлять", "verb", "Women constitute half the staff."),
        VocabCard("demonstrate", "демонстрировать", "verb", "She demonstrated the software."),
        VocabCard("derive", "получать из", "verb", "The word derives from Latin."),
        VocabCard("emphasize", "подчёркивать", "verb", "He emphasized the importance."),
        VocabCard("ensure", "обеспечивать", "verb", "We ensure quality."),
        VocabCard("evaluate", "оценивать", "verb", "We need to evaluate the results."),
        VocabCard("generate", "генерировать", "verb", "Solar panels generate electricity."),
        VocabCard("indicate", "указывать", "verb", "The data indicates a trend."),
        VocabCard("justify", "оправдывать", "verb", "How do you justify this?"),
        VocabCard("modify", "модифицировать", "verb", "We need to modify the plan."),
        VocabCard("obtain", "получать", "verb", "She obtained a degree."),
        VocabCard("overcome", "преодолевать", "verb", "He overcame his fear."),
        VocabCard("perceive", "воспринимать", "verb", "How do you perceive this?"),
        VocabCard("clarify", "уточнять", "verb", "Can you clarify this point?"),
        VocabCard("correspond", "соответствовать", "verb", "The data corresponds to our theory."),
    ]),
    VocabSet("B2", "Abstract Concepts Extended", [
        VocabCard("concept", "концепция", "noun", "It's a difficult concept."),
        VocabCard("context", "контекст", "noun", "In this context, it makes sense."),
        VocabCard("criterion", "критерий", "noun", "What are the criteria?"),
        VocabCard("factor", "фактор", "noun", "Cost is a key factor."),
        VocabCard("feature", "особенность", "noun", "This phone has new features."),
        VocabCard("function", "функция", "noun", "What's the function of this?"),
        VocabCard("issue", "проблема, вопрос", "noun", "It's a controversial issue."),
        VocabCard("principle", "принцип", "noun", "It's a matter of principle."),
        VocabCard("requirement", "требование", "noun", "You need to meet the requirements."),
        VocabCard("standard", "стандарт", "noun", "We have high standards."),
        VocabCard("tendency", "тенденция", "noun", "There's a tendency to overspend."),
        VocabCard("tension", "напряжение", "noun", "There's tension between them."),
        VocabCard("trend", "тенденция", "noun", "This trend is growing."),
        VocabCard("variation", "вариация", "noun", "There's a lot of variation."),
        VocabCard("approach", "подход", "noun", "We need a new approach."),
        VocabCard("assumption", "предположение", "noun", "That's a false assumption."),
        VocabCard("attitude", "отношение", "noun", "Her attitude is positive."),
        VocabCard("awareness", "осведомлённость", "noun", "There's growing awareness."),
        VocabCard("perspective", "перспектива", "noun", "From a different perspective."),
        VocabCard("priority", "приоритет", "noun", "Health is my priority."),
    ]),
    VocabSet("B2", "Social Issues", [
        VocabCard("poverty", "бедность", "noun", "Poverty is a global issue."),
        VocabCard("unemployment", "безработица", "noun", "Unemployment is rising."),
        VocabCard("discrimination", "дискриминация", "noun", "Discrimination is illegal."),
        VocabCard("prejudice", "предубеждение", "noun", "We must fight prejudice."),
        VocabCard("stereotype", "стереотип", "noun", "That's a common stereotype."),
        VocabCard("equality", "равенство", "noun", "We believe in equality."),
        VocabCard("justice", "справедливость", "noun", "We fight for justice."),
        VocabCard("rights", "права", "noun", "Human rights are universal."),
        VocabCard("democracy", "демократия", "noun", "Democracy requires participation."),
        VocabCard("immigration", "иммиграция", "noun", "Immigration is debated."),
        VocabCard("refugee", "беженец", "noun", "They help refugees."),
        VocabCard("housing", "жильё", "noun", "Housing is expensive."),
        VocabCard("healthcare", "здравоохранение", "noun", "Healthcare should be free."),
        VocabCard("education", "образование", "noun", "Education is a right."),
        VocabCard("welfare", "благосостояние", "noun", "The welfare system helps people."),
        VocabCard("crime rate", "уровень преступности", "noun", "The crime rate is falling."),
        VocabCard("homelessness", "бездомность", "noun", "Homelessness is a problem."),
        VocabCard("corruption", "коррупция", "noun", "Corruption destroys trust."),
        VocabCard("censorship", "цензура", "noun", "Censorship limits freedom."),
        VocabCard("inequality", "неравенство", "noun", "Income inequality is growing."),
    ]),
    VocabSet("B2", "Formal Writing & Discourse", [
        VocabCard("moreover", "более того", "adverb", "Moreover, the data supports this."),
        VocabCard("nevertheless", "тем не менее", "adverb", "Nevertheless, we proceeded."),
        VocabCard("nonetheless", "тем не менее", "adverb", "Nonetheless, it's worth trying."),
        VocabCard("subsequently", "впоследствии", "adverb", "Subsequently, he changed his mind."),
        VocabCard("accordingly", "соответственно", "adverb", "We acted accordingly."),
        VocabCard("in addition", "к тому же", "adverb", "In addition, it's affordable."),
        VocabCard("in contrast", "в отличие", "adverb", "In contrast, the other group failed."),
        VocabCard("on the contrary", "наоборот", "adverb", "On the contrary, it helped."),
        VocabCard("with regard to", "что касается", "preposition", "With regard to your request..."),
        VocabCard("in terms of", "с точки зрения", "preposition", "In terms of cost, it's better."),
        VocabCard("as a result", "в результате", "adverb", "As a result, sales increased."),
        VocabCard("in conclusion", "в заключение", "adverb", "In conclusion, we agree."),
        VocabCard("to sum up", "подводя итог", "adverb", "To sum up, it was successful."),
        VocabCard("broadly speaking", "в целом", "adverb", "Broadly speaking, it's true."),
        VocabCard("generally speaking", "вообще", "adverb", "Generally speaking, kids learn fast."),
        VocabCard("strictly speaking", "строго говоря", "adverb", "Strictly speaking, it's incorrect."),
        VocabCard("in other words", "иначе говоря", "adverb", "In other words, it's broken."),
        VocabCard("that is to say", "то есть", "adverb", "That is to say, we agree."),
        VocabCard("for instance", "например", "adverb", "For instance, take Paris."),
        VocabCard("namely", "а именно", "adverb", "Two people, namely John and Mary."),
    ]),
]


# ═══════════════════════════════════════════════════════════════
# MARITIME ENGLISH — IMO SMCP + nautical terms (80 entries)
# Based on IMO Resolution A.918(22) Standard Marine Communication Phrases
# ═══════════════════════════════════════════════════════════════

MARITIME_ENGLISH = [
    {"term": "vessel", "meaning": "судно", "example": "The vessel is approaching the port.", "category": "general"},
    {"term": "port", "meaning": "левый борт / порт", "example": "Turn to port.", "category": "navigation"},
    {"term": "starboard", "meaning": "правый борт", "example": "The light is on the starboard side.", "category": "navigation"},
    {"term": "bow", "meaning": "нос судна", "example": "The bow is pointing north.", "category": "structure"},
    {"term": "stern", "meaning": "корма", "example": "The stern is at the back.", "category": "structure"},
    {"term": "aft", "meaning": "кормовой (направление)", "example": "Move aft.", "category": "navigation"},
    {"term": "forward", "meaning": "носовой (направление)", "example": "Go forward.", "category": "navigation"},
    {"term": "helm", "meaning": "штурвал", "example": "Take the helm.", "category": "navigation"},
    {"term": "heading", "meaning": "курс", "example": "Our heading is 045 degrees.", "category": "navigation"},
    {"term": "bearing", "meaning": "пеленг", "example": "The bearing is 270 degrees.", "category": "navigation"},
    {"term": "knot", "meaning": "узел (скорость)", "example": "We are doing 12 knots.", "category": "navigation"},
    {"term": "nautical mile", "meaning": "морская миля", "example": "The distance is 5 nautical miles.", "category": "navigation"},
    {"term": "cable", "meaning": "кабельтов (0.1 мили)", "example": "We are 3 cables away.", "category": "navigation"},
    {"term": "draft", "meaning": "осадка", "example": "The vessel's draft is 6 meters.", "category": "structure"},
    {"term": "anchor", "meaning": "якорь", "example": "Drop the anchor.", "category": "equipment"},
    {"term": "mooring", "meaning": "швартовка", "example": "We are ready for mooring.", "category": "operations"},
    {"term": "berth", "meaning": "причальное место", "example": "We are approaching the berth.", "category": "operations"},
    {"term": "tug", "meaning": "буксир", "example": "Two tugs are assisting.", "category": "operations"},
    {"term": "pilot", "meaning": "лоцман", "example": "The pilot is on board.", "category": "operations"},
    {"term": "pilotage", "meaning": "лоцманская проводка", "example": "Pilotage is compulsory.", "category": "operations"},
    {"term": "fairway", "meaning": "фарватер", "example": "Keep to the fairway.", "category": "navigation"},
    {"term": "channel", "meaning": "канал (судоходный)", "example": "Enter the channel carefully.", "category": "navigation"},
    {"term": "harbour", "meaning": "гавань", "example": "We are entering the harbour.", "category": "operations"},
    {"term": "dock", "meaning": "док", "example": "The ship is in dry dock.", "category": "operations"},
    {"term": "cargo", "meaning": "груз", "example": "The cargo is dangerous goods.", "category": "cargo"},
    {"term": "container", "meaning": "контейнер", "example": "Load the containers on deck.", "category": "cargo"},
    {"term": "bulk", "meaning": "насыпной груз", "example": "This is a bulk carrier.", "category": "cargo"},
    {"term": "tanker", "meaning": "танкер", "example": "The tanker is loaded with oil.", "category": "cargo"},
    {"term": "deck", "meaning": "палуба", "example": "All hands on deck!", "category": "structure"},
    {"term": "hold", "meaning": "трюм", "example": "The cargo is in the hold.", "category": "structure"},
    {"term": "bridge", "meaning": "мостик (рулевая рубка)", "example": "Report to the bridge.", "category": "structure"},
    {"term": "engine room", "meaning": "машинное отделение", "example": "Fire in the engine room!", "category": "structure"},
    {"term": "lifeboat", "meaning": "спасательная шлюпка", "example": "Abandon ship to the lifeboats.", "category": "safety"},
    {"term": "life jacket", "meaning": "спасательный жилет", "example": "Put on your life jacket.", "category": "safety"},
    {"term": "distress", "meaning": "бедствие", "example": "We are in distress.", "category": "safety"},
    {"term": "mayday", "meaning": "сигнал бедствия", "example": "Mayday, mayday, mayday!", "category": "safety"},
    {"term": "pan-pan", "meaning": "сигнал срочности", "example": "Pan-pan, pan-pan, pan-pan.", "category": "safety"},
    {"term": "securite", "meaning": "сигнал безопасности", "example": "Securite, securite.", "category": "safety"},
    {"term": "abandon ship", "meaning": "покинуть судно", "example": "Order: abandon ship!", "category": "safety"},
    {"term": "man overboard", "meaning": "человек за бортом", "example": "Man overboard! Starboard side!", "category": "safety"},
    {"term": "fire", "meaning": "пожар", "example": "Fire in the accommodation!", "category": "safety"},
    {"term": "flooding", "meaning": "затопление", "example": "We have flooding in the hold.", "category": "safety"},
    {"term": "collision", "meaning": "столкновение", "example": "We had a collision.", "category": "safety"},
    {"term": "grounding", "meaning": "посадка на мель", "example": "The vessel is aground.", "category": "safety"},
    {"term": "aground", "meaning": "на мели", "example": "We are aground.", "category": "safety"},
    {"term": "adrift", "meaning": "дрейф", "example": "The boat is adrift.", "category": "safety"},
    {"term": "list", "meaning": "крен", "example": "The vessel has a 15-degree list.", "category": "structure"},
    {"term": "trim", "meaning": "дифферент", "example": "Check the trim.", "category": "structure"},
    {"term": "stability", "meaning": "остойчивость", "example": "The vessel's stability is good.", "category": "structure"},
    {"term": "freeboard", "meaning": "надводный борт", "example": "The freeboard is 3 meters.", "category": "structure"},
    {"term": "waterline", "meaning": "ватерлиния", "example": "The waterline is visible.", "category": "structure"},
    {"term": "ballast", "meaning": "балласт", "example": "Take in ballast water.", "category": "operations"},
    {"term": "bilge", "meaning": "трюм (нижняя часть)", "example": "Water in the bilge.", "category": "structure"},
    {"term": "bulkhead", "meaning": "переборка", "example": "Close the watertight bulkhead.", "category": "structure"},
    {"term": "hatch", "meaning": "люк", "example": "Open the hatch covers.", "category": "structure"},
    {"term": "winch", "meaning": "лебёдка", "example": "Operate the winch carefully.", "category": "equipment"},
    {"term": "crane", "meaning": "кран (палубный)", "example": "The crane is loading cargo.", "category": "equipment"},
    {"term": "gangway", "meaning": "трап", "example": "Lower the gangway.", "category": "equipment"},
    {"term": "radar", "meaning": "радар", "example": "Check the radar screen.", "category": "equipment"},
    {"term": "sonar", "meaning": "сонар", "example": "Sonar shows shallow water.", "category": "equipment"},
    {"term": "compass", "meaning": "компас", "example": "Check the compass heading.", "category": "equipment"},
    {"term": "GPS", "meaning": "GPS", "example": "Our GPS position is 45N 030E.", "category": "equipment"},
    {"term": "AIS", "meaning": "АИС (авто-идент. система)", "example": "Check the AIS target.", "category": "equipment"},
    {"term": "VHF", "meaning": "КВ-радио", "example": "Call on VHF channel 16.", "category": "communication"},
    {"term": "GMDSS", "meaning": "ГМССБ", "example": "GMDSS equipment is mandatory.", "category": "communication"},
    {"term": "VTS", "meaning": "СУДС (служба упр. движением)", "example": "Contact VTS for permission.", "category": "communication"},
    {"term": "over", "meaning": "приём (радио)", "example": "Over.", "category": "communication"},
    {"term": "out", "meaning": "конец связи", "example": "Out.", "category": "communication"},
    {"term": "roger", "meaning": "понял", "example": "Roger, understood.", "category": "communication"},
    {"term": "stand by", "meaning": "ждать", "example": "Stand by for orders.", "category": "communication"},
    {"term": "read back", "meaning": "повторить", "example": "Read back the message.", "category": "communication"},
    {"term": "correct", "meaning": "правильно", "example": "Correct.", "category": "communication"},
    {"term": "say again", "meaning": "повторите", "example": "Say again, please.", "category": "communication"},
    {"term": "watch", "meaning": "вахта", "example": "I'm on the 8-to-12 watch.", "category": "operations"},
    {"term": "watchkeeper", "meaning": "вахтенный", "example": "The watchkeeper is on the bridge.", "category": "operations"},
    {"term": "relieve", "meaning": "сменять (на вахте)", "example": "I'm here to relieve you.", "category": "operations"},
    {"term": "course", "meaning": "курс", "example": "Steer course 180.", "category": "navigation"},
    {"term": "waypoint", "meaning": "поворотная точка", "example": "We are approaching waypoint 3.", "category": "navigation"},
    {"term": "ETA", "meaning": "расчётное время прибытия", "example": "Our ETA is 1400 UTC.", "category": "navigation"},
    {"term": "ETD", "meaning": "расчётное время отхода", "example": "ETD is 0600 local time.", "category": "navigation"},
    {"term": "underway", "meaning": "на ходу", "example": "The vessel is underway.", "category": "operations"},
    {"term": "not under command", "meaning": "неуправляемое судно", "example": "We are not under command.", "category": "safety"},
    {"term": "restricted visibility", "meaning": "ограниченная видимость", "example": "Navigate carefully in restricted visibility.", "category": "navigation"},
    {"term": "shallow water", "meaning": "мелководье", "example": "We are entering shallow water.", "category": "navigation"},
]


def maritime_terms_for_category(category: str | None = None) -> list[dict]:
    if category is None:
        return MARITIME_ENGLISH
    return [m for m in MARITIME_ENGLISH if m["category"] == category]


# ═══════════════════════════════════════════════════════════════
# SLANG & SWEAR WORDS — modern slang + swear words (60 entries)
# Educational purpose: learners encounter these in real-life English
# ═══════════════════════════════════════════════════════════════

SLANG_SWEAR = [
    {"term": "awesome", "meaning": "потрясающий", "example": "That movie was awesome!", "level": "slang", "severity": "mild"},
    {"term": "cool", "meaning": "крутой, классный", "example": "That's really cool.", "level": "slang", "severity": "mild"},
    {"term": "dude", "meaning": "чувак, братан", "example": "Hey dude, what's up?", "level": "slang", "severity": "mild"},
    {"term": "gonna", "meaning": "собираюсь (going to)", "example": "I'm gonna call you.", "level": "slang", "severity": "mild"},
    {"term": "wanna", "meaning": "хочу (want to)", "example": "I wanna go home.", "level": "slang", "severity": "mild"},
    {"term": "gotta", "meaning": "должен (have got to)", "example": "I gotta leave now.", "level": "slang", "severity": "mild"},
    {"term": "hang out", "meaning": "тусоваться, проводить время", "example": "Let's hang out this weekend.", "level": "slang", "severity": "mild"},
    {"term": "rip-off", "meaning": "обман, надувательство", "example": "That price is a rip-off.", "level": "slang", "severity": "mild"},
    {"term": "no-brainer", "meaning": "очевидный выбор", "example": "It's a no-brainer.", "level": "slang", "severity": "mild"},
    {"term": "freak out", "meaning": "паниковать", "example": "Don't freak out!", "level": "slang", "severity": "mild"},
    {"term": "screw up", "meaning": "облажаться, испортить", "example": "I screwed up the exam.", "level": "slang", "severity": "mild"},
    {"term": "chill out", "meaning": "расслабиться", "example": "Just chill out, okay?", "level": "slang", "severity": "mild"},
    {"term": "broke", "meaning": "на мели (без денег)", "example": "I'm broke this month.", "level": "slang", "severity": "mild"},
    {"term": "loaded", "meaning": "богатый", "example": "He's loaded.", "level": "slang", "severity": "mild"},
    {"term": "bummer", "meaning": "облом, разочарование", "example": "What a bummer!", "level": "slang", "severity": "mild"},
    {"term": "bucks", "meaning": "баксы (доллары)", "example": "It costs 50 bucks.", "level": "slang", "severity": "mild"},
    {"term": "grab a bite", "meaning": "перекусить", "example": "Let's grab a bite.", "level": "slang", "severity": "mild"},
    {"term": "beat", "meaning": "вымотанный", "example": "I'm beat after work.", "level": "slang", "severity": "mild"},
    {"term": "pissed off", "meaning": "разъярённый", "example": "He was really pissed off.", "level": "slang", "severity": "medium"},
    {"term": "crap", "meaning": "чушь, дрянь", "example": "This movie is crap.", "level": "slang", "severity": "medium"},
    {"term": "suck", "meaning": "быть отстойным", "example": "This weather sucks.", "level": "slang", "severity": "medium"},
    {"term": "shut up", "meaning": "заткнись", "example": "Shut up! I don't believe it!", "level": "slang", "severity": "medium"},
    {"term": "lame", "meaning": "жалкий, отстойный", "example": "That excuse is lame.", "level": "slang", "severity": "mild"},
    {"term": "ditch", "meaning": "бросить, свалить", "example": "He ditched the party.", "level": "slang", "severity": "mild"},
    {"term": "ghost", "meaning": "пропасть (перестать отвечать)", "example": "She ghosted me after one date.", "level": "slang", "severity": "mild"},
    {"term": "flex", "meaning": "хвастаться", "example": "Stop flexing your new car.", "level": "slang", "severity": "mild"},
    {"term": "lit", "meaning": "крутой, огонь", "example": "That party was lit!", "level": "slang", "severity": "mild"},
    {"term": "salty", "meaning": "обиженный, раздражённый", "example": "Don't be salty about losing.", "level": "slang", "severity": "mild"},
    {"term": "toxic", "meaning": "токсичный", "example": "He's in a toxic relationship.", "level": "slang", "severity": "mild"},
    {"term": "cringe", "meaning": "кринж (неловкость)", "example": "That video is so cringe.", "level": "slang", "severity": "mild"},
    {"term": "damn", "meaning": "чёрт", "example": "Damn! I forgot my keys.", "level": "swear", "severity": "mild"},
    {"term": "hell", "meaning": "чёрт, ад", "example": "What the hell are you doing?", "level": "swear", "severity": "mild"},
    {"term": "ass", "meaning": "задница, дурак", "example": "Get your ass over here.", "level": "swear", "severity": "medium"},
    {"term": "asshole", "meaning": "придурок", "example": "He's being an asshole.", "level": "swear", "severity": "strong"},
    {"term": "bastard", "meaning": "сволочь", "example": "He's a lazy bastard.", "level": "swear", "severity": "strong"},
    {"term": "bitch", "meaning": "стерва, сука", "example": "She's being a bitch.", "level": "swear", "severity": "strong"},
    {"term": "son of a bitch", "meaning": "сволочь", "example": "You son of a bitch!", "level": "swear", "severity": "strong"},
    {"term": "shit", "meaning": "дерьмо", "example": "Oh shit, I'm late!", "level": "swear", "severity": "strong"},
    {"term": "bullshit", "meaning": "чушь, враньё", "example": "That's complete bullshit.", "level": "swear", "severity": "strong"},
    {"term": "fuck", "meaning": "много значений (ругательство)", "example": "Fuck! I dropped my phone.", "level": "swear", "severity": "strong"},
    {"term": "fucking", "meaning": "чёртов (усилитель)", "example": "It's fucking cold outside.", "level": "swear", "severity": "strong"},
    {"term": "motherfucker", "meaning": "мразь", "example": "Get out of here, motherfucker!", "level": "swear", "severity": "very_strong"},
    {"term": "wanker", "meaning": "долбоб (брит.)", "example": "He's a complete wanker.", "level": "swear", "severity": "strong"},
    {"term": "bollocks", "meaning": "чушь (брит.)", "example": "That's a load of bollocks.", "level": "swear", "severity": "strong"},
    {"term": "bloody", "meaning": "чёртов (брит.)", "example": "It's bloody freezing!", "level": "swear", "severity": "medium"},
    {"term": "bugger", "meaning": "чёрт (брит.)", "example": "Bugger off!", "level": "swear", "severity": "medium"},
    {"term": "piss", "meaning": "мочиться, бесить", "example": "You're pissing me off.", "level": "swear", "severity": "medium"},
    {"term": "piss off", "meaning": "отвали", "example": "Piss off and leave me alone.", "level": "swear", "severity": "medium"},
    {"term": "dick", "meaning": "придурок", "example": "Don't be a dick.", "level": "swear", "severity": "strong"},
    {"term": "dickhead", "meaning": "долбоб", "example": "He's a total dickhead.", "level": "swear", "severity": "strong"},
    {"term": "prick", "meaning": "мразь", "example": "He's a real prick.", "level": "swear", "severity": "strong"},
    {"term": "twat", "meaning": "придурок (брит.)", "example": "You stupid twat.", "level": "swear", "severity": "strong"},
    {"term": "cunt", "meaning": "очень грубое оскорбление", "example": "(extremely offensive — avoid)", "level": "swear", "severity": "very_strong"},
    {"term": "jackass", "meaning": "осёл, дурак", "example": "Don't be a jackass.", "level": "swear", "severity": "medium"},
    {"term": "screw you", "meaning": "пошёл ты", "example": "Screw you, I'm leaving.", "level": "swear", "severity": "medium"},
    {"term": "fricking", "meaning": "блин (вместо fuck)", "example": "It's fricking awesome.", "level": "swear", "severity": "mild"},
    {"term": "freaking", "meaning": "блин (вместо fucking)", "example": "That's freaking amazing.", "level": "swear", "severity": "mild"},
    {"term": "goddamn", "meaning": "чёртов", "example": "This goddamn traffic!", "level": "swear", "severity": "medium"},
    {"term": "jerk", "meaning": "придурок", "example": "He's such a jerk.", "level": "swear", "severity": "mild"},
    {"term": "moron", "meaning": "идиот", "example": "Don't be a moron.", "level": "swear", "severity": "mild"},
]


def slang_for_severity(severity: str | None = None) -> list[dict]:
    if severity is None:
        return SLANG_SWEAR
    return [s for s in SLANG_SWEAR if s["severity"] == severity]
